:PROPERTIES:
:title: (readwise)昨天中国金融工作会议已经开完了，通常这个会是每五...
:END:

:PROPERTIES:
:author: [[Alex_perception on Twitter]]
:full-title: "昨天中国金融工作会议已经开完了，通常这个会是每五..."
:category: [[tweets]]
:url: https://twitter.com/Alex_perception/status/1719756010318135671
:image-url: https://pbs.twimg.com/profile_images/1692350922599596032/Hz0cOlcE.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-05]]
** 📌
#+BEGIN_QUOTE
昨天中国金融工作会议已经开完了，通常这个会是每五年一次，这次因为疫情所以拖到了六年才开，而这六年的时间已经让中国产生了翻天覆地式的变化了。在对比完两次的通稿之后，我深刻的感觉到了这些年的时光到底加速了什么。
PS：本篇主要是做对比简述，我简化了很多其中表述，不过依旧很长，希望大家喜欢~

大体上咱们先回顾一下中国这几年的在空间环境上的变化。
（1）2016年开始金融去杠杆。同期开启的房地产涨价去库存。
（2）2018中美开启贸易战。
（3）2020年新冠疫情
（4）2020年香港国安法
（5）然后大家也就清楚了，俄乌战争，西方国家采取多元化战略，刻意降低中国在本国供应链中的比例，以降低相关风险。

简单捋捋，16年的去杠杆是有一定成效的，宏观杠杆率在后面几年确实出现了明显下降，但这种抑制的效果并不好，中国经济发展的主要动力是依靠发债（加杠杆）做投资的模式+房地产。只要这个模式不停下来，货币超发就无法缓慢下来，我一直强调货币超发（通货膨胀）会不断削弱居民的消费能力，通胀的体现方式不同：一种是货币横行无忌，市场商品普遍出现涨价。另一种就是咱们国家的模式，通过超发货币搞投资+在住房上创造巨大债务（进一步透支居民未来消费潜力），这种模式的好处是房地产成了货币蓄水池（还有A股这个货币湮灭器），所以不像第一种那么容易辨识，货币超发在原理和实际上都是在转移居民财富，相当于一种隐性税。

之后几条基本都跟贸易相关，这里面涉及到中国这个举债模式为什么能持久的另一个缘故。对外贸易，外商投资给中国带来了非常明显的好处，比如说：外汇收入，技术合作，外资进入中国创造就业等等好处。这些既给中国带来了货币超发的稳定器——外汇，也给中国制造业竞争力带来一定的技术基础。当然这些我都是很简略的捋捋，如果大家去查统计局，现在外贸对中国GDP的贡献越来越低都已经萎缩到30%以下，可能很多人会懵，那么大的贸易额怎么才创造了这么点GDP？这点多亏统计局的兄弟们日夜奋斗，一方面在消费的口径上逐步修改，另一方面中国货币超发的过狠了，相比于外贸而言国内的基建和房地产实在是太庞大了。这是最终外贸+外资看似下降的一个原因，但要是换个角度，外贸+外资的重要性相比于基建和房地产而言，这是更能让中国往前发展的力量。

基于之前的背景展开分析，为了方便展示我就一条一条展开，这样大家看得清楚。
（1）本次金融工作会议最基础，也是最应该优先看懂的是全文出现了4次的：“强调必须坚持党中央对金融工作的集中统一领导”。要往下理解其他意思，必须要先抓住一个线头，要不然东一榔头西一棒子根本什么都看不出来。——对比2017年的时候只出现过1次，而且是在倒数第三自然段。这是最根本也是最大的改变，在23年通稿的开头有一句：“坚定不移走中国特色金融发展之路”。听到这句话我当时大概猜测也是党管一切了，然而结果也是如此。
而且今年对党的领导有了新的细节，其中多次提到做好金融工作要保持政治性，或者队伍要保持纯洁性。怎么理解？这不是简单的说都是自己人就完事了，而是因为都是自己人，所以采取的政策会被100%乃至过量执行，以后千万别觉得有什么事儿按照经济规律是不能做的，只有党的要求和党的方向，往后延伸一下再想想就是，现在的经济一旦停止放水就是休克，那么未来在不顾及技术性的条件下，大概率货币会一路以超发的姿态走向崩溃。这中间别有什么技术性建议，没有意义。

（2）23年通稿在综述部分强调：“坚持深化金融供给侧结构性改革，坚持统筹金融开放和安全”。供给侧改革很清楚的思路，就是要把金融的总闸牢牢掌握在中央手中，降低了地方的权力，同时打击市场的作用，这点在后面有体现。——这是17年稿子中所没有，那会儿还提倡跟市场融合呢。后面统筹开放和安全，实际如果对比17年的话，今年意思是开放的前景是国家安全，之前并没有过分强调安全这个概念。总而言之，这是要清退非自己人收拢权力并试图躲赖掉一些麻烦，下面有分析到。

（3）如果看17年的通稿，习主席对金融工作是有四条原则：第一，回归本源，服从服务于经济社会发展。金融要把为实体经济服务作为出发点和落脚点，全面提升服务效率和水平，把更多金融资源配置到经济社会发展的重点领域和薄弱环节，更好满足人民群众和实体经济多样化的金融需求。第二，优化结构，完善金融市场、金融机构、金融产品体系。要坚持质量优先，引导金融业发展同经济社会发展相协调，促进融资便利化、降低实体经济成本、提高资源配置效率、保障风险可控。第三，强化监管，提高防范化解金融风险能力。要以强化金融监管为重点，以防范系统性金融风险为底线，加快相关法律法规建设，完善金融机构法人治理结构，加强宏观审慎管理制度建设，加强功能监管，更加重视行为监管。第四，市场导向，发挥市场在金融资源配置中的决定性作用。坚持社会主义市场经济改革方向，处理好政府和市场关系，完善市场约束机制，提高金融资源配置效率。加强和改善政府宏观调控，健全市场规则，强化纪律性。

但是今年的讲究可以说是变了很多。第一，17年是服务于经济社会发展，服务实体，并把资源配置发展重点和薄弱环节。但是17年它并没有强调党管一切，如果站在党管一切这句话之下你再看看今年的原文：“金融要为经济社会发展提供高质量服务。要着力营造良好的货币金融环境，切实加强对重大战略、重点领域和薄弱环节的优质金融服务。”——看着话都没怎么变，但前提变了一切就都变了，简单来说什么环节薄弱，什么是重大战略，定义由党来做了。不过今年的方向倒是明确了，主要集中在：“把更多金融资源用于促进科技创新、先进制造、绿色发展和中小微企业，大力支持实施创新驱动发展战略、区域协调发展战略，确保国家粮食和能源安全等。”——中小微三个字可以忽略，其他的就是重点了，而且切记啊要看的是自己人的，而非外人的。

关于第三条监管，今年对监管的强化可是说非常重视，而且跟17年时的概念都不一样了。虽然目的都是：“牢牢守住不发生系统性金融风险的底线”。——17年的方式是坚定的去杠杆的，执行稳健的货币政策，处理好稳增长，调结构，控总量的关系。 ——今年货币已经不是风险，之前工作思路写明是要继续放水，这点押后再说。
并且强调国有企业去杠杆是重中之重。——这次没有了。国有企业这几年全是做大做优做强的方向，怎么还能去杠杆。
还有就是严控地方政府债务增量，终身罪责，倒查责任。——今年是：“建立防范化解地方债务风险长效机制，建立同高质量发展相适应的政府债务管理机制，优化中央和地方政府债务结构。”——简答来说，知道地方债务没办法了，怎么办？短债换成长债，即便再着急的情况，中央也不会毫无顾忌的出手帮忙。这样至少可以保护中央这个主体的名义“信誉”，而且中国自古央地就不是完全一条心呐。

那反过来说今年的风险是什么？（写过的就直接略过了，要不然忒长了）
第一是：“及时处置中小金融机构风险”，这是通稿直接说明的。对比17年的时候：“推动国有大银行战略转型，发展中小银行和民营金融机构。”——这是非常鲜明的对比啊，你再结合一下第一段的党管一切？不难明白未来如果中小金融机构如果暴雷了，千万别指望国家能帮助你们啊！！！我特意加了三个叹号啊。

第二是房地产，这次将房地产置于金融风险的段落已经非常明确的给它定位，未来这就是待爆的雷。17年稿子整体是去杠杆，所以即便没有提房地产，但整体方向是清晰地。今年的稿子，“健全房地产企业主体监管制度和资金监管”——这句是针对从预售到完工过程中资金管理的，此前房地产商不是经常会挪用本该被监管的资金再去拿地吗，现在这种加杠杆作死的行为肯定是不能让了。“一视同仁满足不同所有制房地产企业合理融资需求”——这会儿不分国企和民企的意思是因为真的爆雷之后相互传染，下面一句：“防范风险跨区域、跨市场、跨境传递共振。”其中所担忧正是连锁反应。所以能让他们坚持就坚持。最后那句构建房地产发展新模式，大概率是针对8月份国务院就出台的那个房改文件，但现在还没给到公众。
对此我们之前做过一个推断，大概率政府想在以后区分出一个盈利多的商品房，和一个盈利少的保障房。但是他们绝对不可能完全放弃这条道，原因很简单，这条道路上捆绑了太多利益和风险，不是说放弃就能放弃的。

第三：“；把握好快和稳的关系，在稳定大局的前提下把握时度效，扎实稳妥化解风险”。这句话的意思也简单，17年没有这个表述，而且这个“时度效”的表述非常浓缩啊，简单翻译一下是“时间，程度，效率”，整体意思就是化解风险的整体进程要根据大局的情况来做动态调整，但风险肯定不会看着爆，根据实际情况灵活处理。——这里面隐含实际上是一个难度的问题，处理风险意味着肯定是先出事了，怎么处理关乎稳定大局，不能最后搞出冲击道德底线的事儿对吧。

关于第四条原则市场导向。17年的稿子很明确的写出了：“发挥市场在金融资源配置中的决定性作用。坚持社会主义市场经济改革方向，处理好政府和市场关系，完善市场约束机制，提高金融资源配置效率。加强和改善政府宏观调控，健全市场规则，强化纪律性。”——这非常明确的表现出当时政府对金融与市场关系的看法，当时的政府希望借助市场的力量来调节分配，但23年的稿子中直接来个了180度大反转，现在是政府要主导一切，这势必会削弱金融实际帮助实体的效率，这种选择性和偏向性就会越来越明显。

（4）对于货币的方向，今年的表述是：“始终保持货币政策的稳健性，更加注重做好跨周期和逆周期调节，充实货币政策工具箱。”——这话落脚点在“更加注重”上，这与17年整体去杠杆的思路就是完全相反的。再结合最后一段总结的：“要完善金融宏观调控，准确把握货币信贷供需规律和新特点，加强货币供应总量和结构双重调节。”这就更加明确的将货币政策方向指出了——实际就是放水，但朝着党希望的方向。现在中国经济不放水也不行，现在每个月的M2都在10%左右，为什么？现在经济增长完全就是靠投资死撑，一旦货币超发一断，经济立马进入休克状态。目前的局面可比17年难多了，在这个条件下它完全没可能是奔着稳健性去的。

（5）“完善机构定位，支持国有大型金融机构做优做强，当好服务实体经济的主力军和维护金融稳定的压舱石，严格中小金融机构准入标准和监管要求”。23年的稿子中对中小金融机构的态度是严防死守，包括后续新进都要严格审查，这很显然是在加强国家对金融的垄断，这点与17年有明显不同——“要改善间接融资结构，推动国有大银行战略转型，发展中小银行和民营金融机构。”当年虽然也不是真的多支持中小银行和民营金融，但至少给了口子。但是这两年随着河南村镇银行和其他一些危险的地方银行，几个大理财公司相继开始出问题，这都让国家意识到如果自己不能亲自管着，到时候出了问题自己都不知道就糟糕了。

（6）关于今年提出的：“发挥保险业的经济减震器和社会稳定器功能”，相比17年也有一句差不多的：“要促进保险业发挥长期稳健风险管理和保障的功能”。——两者什么差距？多了俩定语。国家重要文件没有废话，每个字都是有意义的，描述详细就意味着定位明确，从字面意思上不难理解，保险资金中有些长期资金关键时刻可以充当救市资金嘛，但问题是救市不是填窟窿，这无疑给保险公司的未来埋下了极大的祸根，哎，但至少现在还不会怎么招儿，不过看到这大家也应该明白未来的选择了。

（7）增强上海国际金融中心的竞争力和影响力，巩固提升香港国际金融中心地位。——这句话17年没有，也是= =香港成为国际金融中心遗址是后面的事儿了，这个是很明确的要捧上海了。从香港向上海的过度，实际上对于以前围绕和依托香港金融功能的地区都会经受一段时间的阵痛期，毕竟原有的安排都得重新安排了。

（7）发挥好中央金融工作委员会的作用，切实加强金融系统党的建设。发挥好地方党委金融委员会和金融工委的作用，落实属地责任。——关于这段话的意思，我的理解是中央要实际指导地方的金融工作了，简单来说，由于不同地方的自然禀赋，人口条件，商贸情况均不同，在一些比较差的地区的地方官为了政绩只能靠发债胡搞基建，但这么下去肯定是不行的。我认为中央的意思并不是遏制花钱，而是往哪花钱，实际契合开头所说的提升金融服务实体的效率。

全文还有一些地方我还需要再结合其他文稿揣摩思考，今天趁着热乎先把能看明白的部分写出来了。有一部分要求比如搞好外贸之类的，这不是金融能做到的，有很多问题的根源在与政治体制，或者其他国家的态度，这不是说你放水还是收紧能改变的，不是这么玩的。金融不是万能的。
这次稿子在我看来是一个：“回收权力，筑起高墙”的行为。从17年到23年中国和全球的变化之大也不是当年能完全预料到的，这种变化在金融工作方面也体现的淋漓尽致，很多当年的诉求和希望在今天又重新闭合了，这次会议文稿之后对于人民币，金融方向，经济预期大致清楚了。金融是一个无比强大的工具，是现代人类一个杰出的发明，它的存在甚至加速了人类的社会发展，但它也打开潘多拉的魔盒，我一直认为工具本身不存在善恶之分，但管理工具的人就未必了，中国金融工具的管理者已经厌倦了现在的模式，也认为能有今天的“危险”正是放开参与者造成的，这些都能从本次工作会议的文稿中明确的感受到。
疫情期间，曾经跟我的搭档试着推演过中国的未来，现在这些未来正在一步一步地实现，金融问题还不同于中美关系，实际上即便中美关系正常，就中国政府举债投资+房地产模式也已经走到尽头，这一切的终点就是居民财富被抽干的时候。无非就是疫情+脱钩让中国早了几年面对危机，是福不是祸是祸躲不过，让我们一起见证未来吧。 
#+END_QUOTE
    date:: [[2023-11-02]]
*** from _昨天中国金融工作会议已经开完了，通常这个会是每五..._ by @Alex_perception on Twitter
*** [View Tweet](https://twitter.com/Alex_perception/status/1719756010318135671)