:PROPERTIES:
:title: (readwise)06 | 股票的风险真的很大吗？
:END:

:PROPERTIES:
:author: [[youzhiyouxing.cn]]
:full-title: "06 | 股票的风险真的很大吗？"
:category: [[articles]]
:url: https://youzhiyouxing.cn/n/materials/187
:image-url: https://readwise-assets.s3.amazonaws.com/static/images/article4.6bc1851654a0.png
:END:

* Highlights first synced by [[Readwise]] [[2023-12-05]]
** 📌
#+BEGIN_QUOTE
在这里，我们先不辩驳「股市风险很大」这样的说法对还是不对，应该怎么理解。我们先来做这样一个思考题：

> 假设有一种资产，它占用资金巨大，动不动就七八位数，你要是没钱的话还得去借钱买；
> 
> 另外，这类资产遇到各种风吹草动，也可以在半年一年里跌个 30% ，账面上一下少了好几百万，而且好几年都涨不回来；
> 
> 同时，这个资产流动性也很一般，也就是说，你着急的时候想卖都卖不出去，而真有钱想抄底买入的话，可能好几个月都没人卖给你。

那么，你觉得这种资产的风险大吗？

有些同学可能已经想到了，这不就是房子吗。那么，在我们国家买房的风险大吗？我想大多数人的答案都会是，感觉并不是很大，至少比买股票的风险小多了。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwp65kq3kv3s50sk6abqtx)
** 📌
#+BEGIN_QUOTE
可是，按照上面的描述，房产也有很多明显的缺陷，而且波动也并不小，那么为什么大部分人会觉得买房总体来说是件风险不高、比较安全的事情呢？

我觉得主要有这么几个原因：

第一，最重要的是，在过去二十年时间里，我们几代中国人见证了房产的大幅上涨和升值。而且这种上涨和升值的逻辑也非常清晰，就是中国整体经济的飞速发展、城市化水平的提高、以及不断发行的货币带来的通货膨胀。

而且在这个过程中，很多家庭也享受到了房产增值带来的巨大福利，和自己生活水平的提高。所以买房已经变成了某种全社会的「信仰」。

过去十几年房产的回报高于股票  
来源：中金公司研究部

而且不只是我们这样，整个东亚民族，甚至包括欧美地区，对买房这件事都抱有很强的信念。之前我们在第一讲就提到过，在全人类社会创造的三百多万亿美元的财富里，大约 2/3 都是以房地产的形式存在的，其中住宅占了 70% 以上。所以，带着这种「房价永远涨」的期待，一时的波动好像也就无所谓了。

发达国家的房产占总资产比重更低  
来源：中金公司研究部

第二，买房要比买股票简单很多。你想想，说起买房，那么需要考虑的就是那几个变量：位置、户型、周边配套设施、开发商物业水平等等，这比买股票要考虑的因素少太多了。

所以，在大部分情况下，买房很难「买错」，而且即使买错了——比如同等价位明明有更好的楼盘和户型，但是你当初没选到——可能别人的房子从 3 万涨到了 5 万，但你的只涨到了 4 万 5，绝对不是一个灾难性的结果。

但如果一只股票选错了，可能就是增值 3 倍和跌成 1/3 的本质区别。从这个角度来说，买房的「风险」的确要小很多。如果用一个比喻的话，可能就是做一道四个选项都正确的选择题，和做数学考试最后一道大题的区别；

最后一个原因，我觉得更有意思。我认为大家觉得买房风险小，是因为房地产市场里并没有一个像股票交易所那样一个实时报价、瞬间买卖的交易系统。所以，即使价格在各种波动，大家也感受不到；或者即使感觉到了，反正也没法立刻卖出去，那就干脆放着无所谓了。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwq6yanphkabzbvmp07w8a)
** 📌
#+BEGIN_QUOTE
首先我们可以确定，*波动并不等同于风险。* 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwr1pfz5292zcrgwck860y)
** 📌
#+BEGIN_QUOTE
这带给了我们一个启示：*对于普通人来说，投资的第一要务，是要投资一个长期向上的市场。*对于相对专业的投资者，他们是有可能在一直震荡、上下反反复复波动的市场中赚到钱的，但对于大多数人，如果你的投资标的长期向上，哪怕中间波动一些，取得正向回报的可能性也是要大很多的。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwrqtsps8ykh5m5c1m6q2z)
** 📌
#+BEGIN_QUOTE
但是权益类资产，却有可能在未来新的一个十年开始表现。

第一，我国经济已经逐步进入了需要依靠科技进步、需要大力发展直接融资的阶段。在这样的背景下，A股市场里优质的公司和企业会越来越多，经过我们之前的课程你应该明白，这是我们收益的根本来源；

第二，随着房地产收益高增速时代的逐渐落幕以及固定收益类产品越来越少，更多的资金会转向到股票市场；

第三，中国的经济在全球依然领先，未来依然有巨大的前景，海外资金也会逐渐提升对中国资产的占比。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwve0ae09ynefsdyjebvb0)
** 📌
#+BEGIN_QUOTE
第二个启示是：*对于投资来说，我们尽量去做简单的题，而少去挑战超出自己能力之外的难题。* 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwvra3bmwnss2hrbt4weqa)
** 📌
#+BEGIN_QUOTE
所以，*投资其实是很反直觉的：挑战高难度、拼命努力钻研，未必能带来相应的回报。*研究个股、投资个股，如果买对了确实可以带来很大的财务回报以及成就感，但如果自己做不到，投资整个市场、并且在自己能够理解的范围内做一些增强收益的动作，并且长期坚持下去，同样是很好的投资方式。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrww7dw7w4kspkde2p99tge)
** 📌
#+BEGIN_QUOTE
当然，投资过程中最糟糕的情况还不是挑战难题造成了亏损，而是这样两种情况：

第一种，由于自己的懒惰、轻信他人或者不做任何的研究，随意就把钱亏了出去——很多人买 P2P 造成血本无归就是这个问题；

第二种，是自欺欺人，明明没有研究清楚的事情，非要骗自己搞清楚了，于是重仓了错误的股票或者产品，导致大幅亏损。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwwbx8871ceytpyzn70fg8)
** 📌
#+BEGIN_QUOTE
所以我们始终觉得，*波动大不是风险、亏损的可能性也不是风险，只有自己不懂装懂、自欺欺人才是最大的风险。*

最后，哪怕一个市场长期向上，我们也很有纪律性地做了自己能力范围之内的事情，我们还是要注意过程中心态的管理。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwxbrqhsz31322g4w7pw8j)
** 📌
#+BEGIN_QUOTE
行为金融学里有个概念叫做「短视损失厌恶（myopic loss aversion）」，是由著名学者理查德·赛勒（Richard Thaler）和施罗莫·贝纳茨（Shlomo Benartzi）提出的。

他们在 1995 年发布的论文里提到了这样一种有趣的现象，就是投资者对于自己的投资账户查看越频繁，通常回报就越低。

因为大多数人忍受不了短期价格波动的影响，总倾向于躲避暂时的浮亏，或者是赚一点钱就赶紧「落袋为安」，这样反反复复的操作不但让自己多交了好多手续费，还损失了更多长期收益。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrwx5n03xxbm4eqn6emr18e)
** 📌
#+BEGIN_QUOTE
看到这一课已经会心一笑，大概率是出自张潇雨老师之手了。 至今还记得得到的个人投资课上讲到股市和房市两个大类资产的相关描述。 1、很多研报都在把当下的中国跟上世纪 80 年代的美国相提并论，诸多经济因素表明，我们可能也站在一轮十年长牛的起点。 但大家也许难相信的是，上世纪这个十年十倍的 80 年代，大部分美国家庭其实并没有赚到钱。 这个十年中美国家庭在股票型资产上的投资比例，从 80 年代的 25%，一路降到了 90 年代的 17%。连指数都涨了 3-4 倍的漫长牛市，分享到国家经济成长成果的人却非常少，更多的钱都被专业的金融机构赚走了。 但如果换个角度看，是非常好理解的，整个 70 年代中东石油危机、升级后漫长浩劫的越战、国家灾难财政政策的一系列问题导致美国经济几乎停滞了整整十年，股市也非常惨淡，十年间道琼斯指数几乎完全不动，市场情绪几乎到达冰点。 这个十年，如果你是一名普通美国人，见证了身边的所有亲朋好友，但凡入市都被按在地上毒打，你敢放心大胆地把家庭资产投入到股市么？你不会的，所以最后你即使试探性放进去一点点，挣到一点小钱也就赶紧跑了，眼睁睁看着人生第一个大机会擦肩而过。 2、大洋彼岸的岛国上，是完全不同的另一个故事。当时的亚洲之光日本战后走过了辉煌的几十年后经济一路崛起攀升到世界第二，一度膨胀到本土公司在纽约到处买楼。连续几十年的好时光让日本家庭对未来充满乐观，身边的财富故事让无数人加着高息杠杆买房。最夸张的时候银座的地价达到了 25W 美元一平。 后面的故事大家也都知道了，这是「失落的 20 年」的开端，无数接盘最高点房产的日本家庭财富毁灭，在崩盘中负债累累。 所以，看起来好像判断在什么时间要买什么品种，还是挺难的呢，一不小心就会万劫不复？因为要准确预测每个大类资产在一段时间内的趋势，太难了。君不见，无数旅鼠羊群般的投资者，在牛市顶部架着两万亿的两融余额进场；君不见，太多人为了等一个回调持币观望，错过了自己所在城市好地段的好上车机会。 然而解决方案其实比想象的简单：多元化我们的资产组合就好了。让资产配置来承受过程中的波动，并与这个国家的经济增长长期相伴。 成年人不做选择题，好城市的好房子、好行业的好公司，都是最优质的资产，都要尽我们的努力去拥抱。 除了分散风险之外，还能保证，周期轮回，起飞的那天，我们资产中的一部分，都可以跟得上这灿烂的时代。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _06 | 股票的风险真的很大吗？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrx0etdqepmm2na0n1m3gqj)