:PROPERTIES:
:title: (readwise)万维钢谈第一性原理 伊隆·马斯克解释 第一性原...
:END:

:PROPERTIES:
:author: [[henices on Twitter]]
:full-title: "万维钢谈第一性原理 伊隆·马斯克解释 第一性原..."
:category: [[tweets]]
:url: https://twitter.com/henices/status/1723919732242260112
:image-url: https://pbs.twimg.com/profile_images/1553267213410349056/quQySPWc.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-05]]
** 📌
#+BEGIN_QUOTE
万维钢谈第一性原理

伊隆·马斯克解释 第一性原理，我们思考老问题，不一定需要使用类比思维考虑前人的做法，直接从最基本的原理出发，可能会找到全新的办法。创业者说第一性原理，精神的主旨为「抛开成见，拒绝套路」，回到最基本的限制条件，重新认识和解决问题。

马斯克使用第一性原理计算电池价值的例子，可能不太正确。电池的根本价值，重要的不是组成它的材料，而是材料的结合方式 - 凝结在它身上的信息。电池身上的信息，是技术和专利，这是几代人智慧的结晶。

从物理学上说，所谓第一性原理，是最基本的物理定律。数学学科的所有内容都是建立在第一性原理上的，从几条公理出发，推导出各种定律，所以数学是百分之百正确的学科。

从第一性原理出发做计算，有时候问题太复杂了，科学家不能使用第一性原理时，通常有两个解法方法：
1）把问题简化，做一些基本假设，忽略一些「次要」条件，这些假设构成一个模型，基于模型的计算，结果可能错误
2）淡化计算，借助历史经验（实验），比如化学和材料科学，大量的知识是实验积累的结果，不是谁从基本物理定律算出来

模型和经验既然不是从第一性原理出发的，就有可能是错的，就有被改进的余地，将来就有可能被取代。而取代它们的，往往是更好的……模型和经验。

马斯克的精神是对的，我们不应被前人的经验束缚，应该改革和创新。但是我们需要知道，什么情况下忽略前人的经验才是理性的行为。
1）有了新的工具：比如有新的工具让你对事物有了全新的理解或更深的理解
2）环境变了：比如今天的基础设施、原材料价格、消费者状况和以前有重大差别，老一套的方法不使用了，你就需要一个全新的商业模式

#note 
#+END_QUOTE
    date:: [[2023-11-13]]
*** from _万维钢谈第一性原理 伊隆·马斯克解释 第一性原..._ by @henices on Twitter
*** [View Tweet](https://twitter.com/henices/status/1723919732242260112)
** 📌
#+BEGIN_QUOTE
万维钢谈第一性原理(2)  

万维钢：作为一个前物理学家，我对第一性原理的第一反应是最基本的物理定律，所以谁跟我说要从第一性原理出发、重新建立一套新东西，我深表怀疑 —— 因为我尊重人类文明。  

SpaceX 为什么可以使用第一性原理 
1. 航天不是一个竞争充分有效的市场：航天基本是 NASA 垄断的领域，NASA 自己基本上只负责设计和科学研究，它会把火箭的制造工程转包给各个小公司 
2. NASA 现在不怎么创新：NASA 在科学探索方面没问题，一直在进步，但它就像其他大型企业一样，得了大企业病。流程会让公司一直按照惯性行事  

《像火箭科学家一样思考》书中，瓦罗尔分析了 SpaceX 使用第一性原理的 6 个办法
\-  尽量不外包，80%的零部件自己生产
-  采购的方式更加灵活：可能到 ebay，废品厂去买二手零部件
-  和大市场对接：利用民用的产业链做火箭 (可能是最重要的一点)
-  回收，尽量重复使用火箭
-  用人不只用航天人才，也到大市场找人：从汽车、手机等快速迭代的领域寻找人才
-  “奥姆卡剃刀”，尽量简化制造流程 
#+END_QUOTE
    date:: [[2023-11-15]]
*** from _万维钢谈第一性原理 伊隆·马斯克解释 第一性原..._ by @henices on Twitter
*** [View Tweet](https://twitter.com/henices/status/1723985589760868829)