:PROPERTIES:
:title: (readwise)主流媒体认为eth未来定将超越btc，eth的社...
:END:

:PROPERTIES:
:author: [[xiangganzi on Twitter]]
:full-title: "主流媒体认为eth未来定将超越btc，eth的社..."
:category: [[tweets]]
:url: https://twitter.com/xiangganzi/status/1633713843087245313
:image-url: https://pbs.twimg.com/profile_images/1494487951614496768/r-eYZSZE.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-05]]
** 📌
#+BEGIN_QUOTE
主流媒体认为ETH未来定将超越BTC，ETH的社区强大的无法被击败的观点是我不能认可的。

我指的不是那些所谓的新公链可以替代ETH，很多同学还是有疑问，我尝试用大白话把其中的结构理清楚，毋庸置疑的ETH本身是非常非常好的项目。

但ETH这次的对手是ETH老师们的组合拳，下面具体说说 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633713843087245313)
** 📌
#+BEGIN_QUOTE
链的老师: BTC

V神早期也是想在比特币链上实现智能合约，btc core 并不认可这个方案才有了ETH，ETH的区块结构，共识早期都借鉴了BTC

但链上去做智能合约的计算真的是好的方向吗？ 

链要跑共识机制，计算能力有限，所以ETH也转移了方向，改方向为区块生成是中心化的（链下计算），验证是去中心化 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633714204376174592)
** 📌
#+BEGIN_QUOTE
这点V神在endgame中也提到了 https://t.co/cCCR5kOhuS

模块化的老师：Celestia，Rollkit

ETH的升级路线其实是很曲折的，V神也并不是真的神，也有很多错的地方，早期V神还认为Plasma是未来方向，ETH要支持分片链让ETH实现百万级的TPS等说法都被V神自身抛弃，最终ETH的选择是模块化的路线。 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633714422702301185)
** 📌
#+BEGIN_QUOTE
去年的ETH升级其实就是共识层与执行层分离，未来的EIP-4844 升级就是实现以太坊的数据可用性层都是模块化方向的升级。

其实这是借鉴的Celestia 的创始人Mustafa Al-Bassam提出数据可用性，模块化区块链的方案，附上Mustafa Al-Bassam和V神在18-19年间写的论文链接https://t.co/U20yNN6KHP 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633714672598929411)
** 📌
#+BEGIN_QUOTE
Mustafa Al-Bassam 现在做了自己模块化区块链项目，专门用来做数据可用性层的celestia，@CelestiaOrg 团队同时也为btc 做了数据可用性这个项目就是@RollkitDev。

Celestia团队为对 Rollkit 的介绍文档：

[https://t.co/Z40dtXKow3](https://t.co/Z40dtXKow3) 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633714767960633350)
** 📌
#+BEGIN_QUOTE
模块化区块链的介绍，再普及一下

可分4层

执行层：交易的执行，以及状态的更改将在这里发送，交易的排序也由执行层负责（现有Layer2本身就是执行层）

数据可用性层：将验证状态迁移所需的交易数据发布,存储。数据可用性的确认，验证状态迁移所需的交易数据的确认（danksharding，Celestia，Eigen） 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633715349064671238)
** 📌
#+BEGIN_QUOTE
结算层：验证最终执行结果以及解决争议。（ETH本身链上的验证合约）

共识层：就状态转换，交易的有效性达成共识，从而提供状态的最终确定性。（ETH的POS, BTC的POW共识等）

想深入学习模块化区块链和数据可用性可以研究我们团队翻译的Celestia白皮书和合并后ETH信标链的文章。 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633715608360726529)
** 📌
#+BEGIN_QUOTE
Celestia 白皮书
https://t.co/liLuMFoQ54

合并后ETH信标链
https://t.co/EBVZhr1Rwt 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633715821917933570)
** 📌
#+BEGIN_QUOTE
zk证明，Layer2，Layer3的老师：Starkware

以太坊未来的另一大主要方向就zk化，其实更精准应该是说有效证明，因为zk这个词更被大家所接受，就还是用zk，这里的zk并不一定要零知识性。

ETH最新的路线图里也指出数据可用性采样，以太坊的数据结构Verkle树，Rollup通通都在zk化 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633716281626198019)
** 📌
#+BEGIN_QUOTE
Starkware 有诸多产品，Starkware 创始人 Eli 本身也是zk证明系统Stark的发明者，ETH的zk化，Layer3的路线，很大程度是借鉴了Starkware团队的思想。
Starkware团队开发的Cairo语言也正在扎根web3世界，Cairo语言不仅仅可以做为智能合约，Cairo 更是第一个为通用计算创建可证明的图灵完备的语言。 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633716747646951424)
** 📌
#+BEGIN_QUOTE
Cairo切入的市场和ETH的Solidity并不相同。Stark 本身比较复杂，也是最近研究较多的部分，后续会独立围绕这一块输出更具体的干货。

比特币的闪电网络Lightning Labs 团队也尝试用Stark和Cairo这一套体系去改进BTC，参考之前推文：

[https://t.co/GDlZs5yRJQ](https://t.co/GDlZs5yRJQ) 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633717002299932672)
** 📌
#+BEGIN_QUOTE
相关产品有@ZeroSync_

[https://t.co/H5ISMLEsQ6](https://t.co/H5ISMLEsQ6)

附上Layer3与Stark的参考资料

V神对L3看法的文章

[https://t.co/9xftuiULpt](https://t.co/9xftuiULpt)

实践Stark证明的文章

[https://t.co/sO2iKyVNvp](https://t.co/sO2iKyVNvp) 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633717319192182786)
** 📌
#+BEGIN_QUOTE
还有一点值得提的ETH虽然也是模块化，但是ETH是啥都做，还要兼容现有ETH，未来ETH升级的技术债务其实会比BTC这一套更多，例如EVM本身不适合zk，部分L2还得牺牲效率去实现zkEVM，抽象账户的升级等等，类似的技术债务还非常多。
参考之前分析ETH升级路线以及ETH存在问题的推文
https://t.co/2RWTkZOwG6 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633718194459525121)
** 📌
#+BEGIN_QUOTE
总的来说ETH的老师们在BTC上的组合，能掀起什么样火花，是挺值得关注的事，当然这一套的运行也是像ETH升级一样需要几年的时间去一步步迭代。

实现后未来的L2，L3们有两个大选择，选择共识更强，安全更高，组合性强的BTC，还是选择社区更大，周边工具成熟，生态丰富，也在不断优化进步的ETH。 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633718513407000576)
** 📌
#+BEGIN_QUOTE
web3的用户也是一样，你信仰BTC还是ETH呢？

终于 ETH有了足够强大的对手！

以上仅仅也是给大家提供一个有趣的新观点，说的不对的地方欢迎喷，欢迎battle🫰 
#+END_QUOTE
    date:: [[2023-03-10]]
*** from _主流媒体认为eth未来定将超越btc，eth的社..._ by @xiangganzi on Twitter
*** [View Tweet](https://twitter.com/xiangganzi/status/1633719206717038594)