:PROPERTIES:
:title: 20｜价值投资：永远不过时的中长期投资策略 (highlights)
:author: [[geekbang.org]]
:full-title: "20｜价值投资：永远不过时的中长期投资策略"
:category: #articles
:url: https://time.geekbang.org/column/article/411242
:END:

* Highlights first synced by [[Readwise]] [[2023-04-11]]
** 什么是价值投资？ ([View Highlight](https://read.readwise.io/read/01gxre5e0m5435gh28cgkzhgts))
** 价值投资的本质很简单，就是拿你手中的财富去交换更有价值的东西。只要你学过一点经济学，肯定知道商品的价值和价格两种属性，以及它们的关系。价值是商品的内在属性，而价格则是从属于价值的，由价值决定的一种货币表现形式。受货币因素、供需关系、投资者心态的影响，价格总是围绕着价值进行上下波动。 ([View Highlight](https://read.readwise.io/read/01gxre5vh0p1ezw7jy4g2m6n82))
** 那到底是什么导致了价格的剧烈波动呢？从大的方面来说，主要有三个原因 ([View Highlight](https://read.readwise.io/read/01gxre6b5fz09nhsat764c9frt))
** 第一个原因是“人性的缺陷”。

有较多投资经验的同学肯定有这样的体会，就是“投资是反人性的”。人性中存在着天生的贪婪和恐惧。在市场狂热的时候，总是希望再涨一些，在市场遇冷的时候，总是担心会不会再创新低。遇到新冠、战争等突发事件，人们往往也会在市场上产生过激的反应。这样的人性缺陷存在于所有的投资活动中，也正因为人的这些非理性因素，导致了所有投资标的都存在价格偏离价值的时刻。 ([View Highlight](https://read.readwise.io/read/01gxre6dfzzbpzgszk5fr4mx1z))
** 第二个原因是宏观经济政策的影响。

市场经济中最有名的概念就是“看不见的手”，这只看不见的手就是经济规律本身，它调控着所有资产的定价。但是无论国内还是国外，政府调控这只“看得见的手”都会时不时地干涉自由市场。比如疫情发生后，美联储发行了天量的美元刺激经济，这就造成了市面上几乎所有投资标的的价格走高。所以毫无疑问，宏观经济政策是影响商品价格、投资标的价格的重要因素。 ([View Highlight](https://read.readwise.io/read/01gxre6h1xpnermayf77hb2fap))
** 第三个原因是投资者自身的资金约束。

市场上的各类投资者，无论是个人投资者，还是机构投资者，他们的钱都不是完全自由的，总会在投资过程中受到这样或那样的约束。比如我们在06 讲中提到过，机构投资者特别容易受短期业绩的影响，不得不卖出一些标的。这些来自市场之外的资金约束，就导致了当资产价格发生变动时，投资者不得不做出一些过激的、不可预期的反应。那么这样过激的反应同样造成了资产价格的过度偏离。 ([View Highlight](https://read.readwise.io/read/01gxre6mtt275rxafkqd5fazeq))
** 如何判断投资标的是不是被低估了？ ([View Highlight](https://read.readwise.io/read/01gxre6vds8yrvjr4gby10ph1s))
** 判断一个投资标的是贵还是便宜，我们要用到的工具就是各种估值指标。其中最常用的就是市盈率 PE（price-to-earnings ratio），它的定义是投资标的的市值与年度净利润的比值。比如贵州茅台当前（2021 年 8 月）的市值是 22600 亿人民币，上一年年度净利润是 467 亿人民币，那么它的市盈率就是 22600/467=48.4 倍。

知道了市盈率，如果没有比较，我们还是难以确定当前的估值是高估还是低估。这个时候估值分位数就是一种合适的工具。当你不知道一个投资标的的估值中枢在哪里时，你可以简单地用它近 5 到 10 年市盈率的中位数来作为中枢。 ([View Highlight](https://read.readwise.io/read/01gxre75cbmy0abvtnqfqv4dza))
** 这里我想特别说明一下：在对个股进行价值投资的操作中，一定要注意区分真假低估，以避免掉进“价值陷阱”。而这个区分的依据，就是你对这只个股基本面的判断。上面的投资者正是基于对茅台基本面的分析进行投资的：他判断茅台在 2014 年的基本面没有发生本质的变化，茅台的品牌影响力情况是非常坚实的，盈利情况也并没有受较大的影响。但是你肯定会遇到股票基本面恶化，价值受损的情况，这时候也需要你做出敏锐的觉察和判断。 ([View Highlight](https://read.readwise.io/read/01gxre7jtpknr0ex12gsgdf8b9))
** 基于价值投资的投资策略 ([View Highlight](https://read.readwise.io/read/01gxreardbqpf7fh5xvf2n082f))
** 这里我选择的投资标的是沪深 300 指数，它代表了中国 A 股市场最大的 300 只股票的整体走势，所以估值相比个股来说更加稳定。下面我们就看一看，利用沪深 300 整体的市盈率估值分位数，通过回测，能否找到一个可行的价值投资策略。

我们要验证的策略逻辑是这样的：当沪深 300 的市盈率估值分位数超过 80% 的时候，我们就平仓，然后等分位数重新落回到 50% 以下时，我们再恢复满仓。这个策略非常简单可执行，我们来看一看它在过去 11 年的表现。 ([View Highlight](https://read.readwise.io/read/01gxreb6c5bv62cp2n3a9bqqed))
** 目前市场上公认的价值投资风格的基金经理，有中庚基金的丘栋荣和中欧基金的曹名长。如果你有兴趣的话，可以了解一下他们管理的基金产品，并通过15 讲实战课介绍的方法，比较一下他们的实际收益到底如何，然后做出自己的决策。 ([View Highlight](https://read.readwise.io/read/01gxreg17wsdpcr493v5rk47dt))
** 价值投资的本质就是利用价格围绕价值波动这一特性，拿你手中的财富去交换更有价值的东西。

价值投资的机会总是会产生的三个原因是：人性的缺陷，宏观经济政策的影响，以及投资者自身的资金约束。

判断投资标的是否被低估的一般方法：使用公司的 PE、PB 等各种估值指标以及估值分位数去判断。

对于没有时间和精力践行价值投资理念的投资者来说，把这个工作外包给价值投资基金经理是一个可行的方法。 ([View Highlight](https://read.readwise.io/read/01gxreptjxy71xj3yeqcv2ym7j))
* New highlights added [[2023-04-11]] at 11:46 PM
** 价值投资的核心就一点，商品的价格围绕它的真实价值上下波动，最终回归到价值本身，所以在股市里价值投资体现在两个方面，低估和成长。低估很好理解，抄底静待价值的回归，如去年年初的茅台；成长就是找到一家能在未来几年利润数倍增长的企业，如去年的宁德时代和隆基股份，利润的增长叠加市场认可度的提升（市盈率的提升）实现了估值的乘数增长，也就是我们所说的戴维斯双击。 从王老师课程中的概念来理解： （1）低估和成长就是“支点投资法”中的那个支点，股票上涨我们要考虑股票本身的逻辑是否兑现，股票下跌要考虑支点是否消失 （2）拓宽自己的能力边界，能找到更多低估的股票，风险承受能力决定我们是否能忍受短期的波动，坚持长期的持股 （3）通过合理的资产配置降低自己持股的风险，大部分的仓位在稳健增长的品类中，用小部分的资金去追逐风险较高的成长股，即守正出奇 ([View Highlight](https://read.readwise.io/read/01gxrf6h641qqj94mmhgzxdanb))
** 比特币没实际投资过没经验。 但是A股抄底三个法宝。 一个是整个行业指数市盈率半分位在20%一下，开始定投分12份买入，这样可以很好的买在一个底部区间。 一个是买指数不碰个股。行业指数分析要比个股简单的多。黑天鹅也少。 一个是一个月不创新低或者有地量再开始买。

作者回复: 感谢分享，都是很实用的方法 1、网格投资法对于散户很实用，可以尝试。 2、根据自己的精力和认知程度来决定买个股还是行业指数 3、很好的底部确认方法。 每次都有干货分享，再赞一个！ ([View Highlight](https://read.readwise.io/read/01gxrf75zsqmhcjar6xhg463w0))
** 用什么工具看历史市盈率？

作者回复: 同花顺等股票分析工具都可以查看。网页端的工具有乌龟量化，可以探索一下。 ([View Highlight](https://read.readwise.io/read/01gxrf7y4j9s0nzc6wrrxpdsr0))
** 抄底应该也算价值投资的应用吧，但是我觉得更多人并没有很好的判断价值而是跟风抄底。 践行价值投资，除了pe/pb，需要考虑的可能还有企业的综合水准、经济大盘等等要素。个人如果不是特别了解那个行业，交给专业的人去做可能更合理、省力了~ ([View Highlight](https://read.readwise.io/read/01gxrf87mj183ez0qgz4w6rx7z))