:PROPERTIES:
:title: 24｜多因子模型：整合不同策略，形成合力的顶层框架 (highlights)
:author: [[geekbang.org]]
:full-title: "24｜多因子模型：整合不同策略，形成合力的顶层框架"
:category: #articles
:url: https://time.geekbang.org/column/article/415181
:END:
tags:: #[[gt/程序员的个人财富课]]

* Highlights first synced by [[Readwise]] [[2023-04-12]]
** 在我的眼中，多因子模型是量化投资中最重要的模型。我这样说有两个原因。第一个原因，是我认为能否熟练使用多因子模型，是区分量化投资高手和初学者的一个重要分界线；第二个原因，是多因子模型蕴含着量化投资的一整套核心思想。这套思想具有很普遍的指导意义，即使你做的不是量化投资，它也能在你最迷惑的时候，帮你拨开迷雾，给你指出明路。 ([View Highlight](https://read.readwise.io/read/01gxrh121b00d0nmmfp26nn704))
** 到底什么是多因子模型？

我们生活的世界是很复杂的，任何一件事情，如果你想做好，就要考虑影响它的各种因素。举个简单的例子，如果你想保持身体健康，那不光要锻炼身体，还得吃得健康，睡觉时间也要合理。这就是一个典型的受多因子影响的问题，只有同时控制好多个变量，才更有可能达到你想要实现的目标。

投资也是一样的。举几个例子来说吧。大家都知道的龙头白马股，基本面确实好，但是估值往往过高。只看估值的话也不行，因为有些估值低的股票，可能所在的行业已经是夕阳行业了，比如被单晶硅淘汰的多晶硅行业。 ([View Highlight](https://read.readwise.io/read/01gxrh1dezqhawfkh4wzyhfdyb))
** 总之，股价未来的走势肯定是由多种因子共同决定的，每种因子实际上都代表一种投资股票的底层策略。要把如此多的因子整合在一起，发挥出最大的作用，就需要我们构建一个具有坚实数学基础的模型，这个模型就是我们说的“多因子模型”。 ([View Highlight](https://read.readwise.io/read/01gxrh1va03x77pa5z1tks3yfd))
** 在股票预测中，有哪些常用的因子？ ([View Highlight](https://read.readwise.io/read/01gxrh241a6e96mpx4x3v3pny6))
** 这里我大致梳理了一下，常见的因子种类包括宏观因子、行业因子、技术面因子、基本面因子、大数据因子等等，至于它们的具体数量就更多了。你应该还记得，我在 19 讲 介绍过一家国际知名的量化投资机构，它挖掘出的有预测能力，还有一定差异化的技术面因子就有 100 多万种。不过，我们当然没有必要全部了解所有具体的因子，只需要清楚每个因子类别的含义就可以了。接下来，我就对上面提到的 5 种常见的因子种类做个具体介绍。 ([View Highlight](https://read.readwise.io/read/01gxrh2eh76ks3baz2b0kbm1m5))
** 宏观因子

宏观因子主要描述了股票对一些宏观变量的敏感性。最常见的宏观因子是贝塔值，它反映的是股票对股票指数的敏感性。一只股票的贝塔值，你可以简单理解成该股票涨跌幅相对于股票指数涨跌幅的倍数。比如说，一只股票对股指的贝塔值是 1.2，那就意味着当指数上涨 1% 的时候，这只股票平均要上涨 1.2%；如果股指下跌 2%，那这只股票平均下跌 2.4%。

还有一些常见的宏观因子，比如股票对油价的敏感性，股票对汇率的敏感性，等等。 ([View Highlight](https://read.readwise.io/read/01gxrh2xgbg9ge32k29rxjksf6))
** 行业因子

行业因子代表了一只个股对相关行业的从属关系。A 股市场的股票，一般被划分成约 30 个一级行业，因此一只个股至少有 30 个行业因子。

股票对各个行业因子的因子值，我们通常只取 0 或 1，取 1 表示股票属于该行业，取 0 表示不属于该行业。当然，在更细致的量化投资中，我们往往会自定义更加细化的行业分类，因子的数值也可以根据相关性的高低取连续值，这就要看我们自己建模时的定义了。 ([View Highlight](https://read.readwise.io/read/01gxrh36y5j3vx6xmq33c3w7sk))
** 技术面因子

技术面因子主要描述了股票近期量价走势展示出来的技术形态特征。常见的技术形态包括“放量上涨”、“双肩顶”、“金叉死叉”等等。技术面因子就是要用股票的量价数据，也就是股票每天的成交量、开盘价、收盘价、最高价、最低价等数据，来构建指标，定量地识别出上述各种技术形态。

这里举几个具体例子。动量因子一般定义为股票最近 1 周、最近 1 个月、最近 3 个月或最近 1 年的涨跌幅，用来描述股价近期是否有显著的上升或下降趋势；波动率因子一般定义为股票最近一段时间每日涨跌幅的标准差，用来描述股价的波动幅度；流动性因子常定义为股票近期的换手率，用来描述股票最近的交易活跃性。 ([View Highlight](https://read.readwise.io/read/01gxrh3ec96005vfpa25w5s7s8))
** 基本面因子

基本面因子主要描述股票的基本面相关情况。例如，ROE 因子描述了股票背后的上市公司最近一年的净资产收益率；成长性因子，描述的是股票近 5 年营收或净利润的平均增速；市值因子描述了股票是大盘股还是中小盘股；估值因子描述了股票价格相对于它的基本面是高估还是低估，等等。 ([View Highlight](https://read.readwise.io/read/01gxrh3jbbw76rxc5y2jdt10wt))
** 大数据因子

最后我要讲的大数据因子，是近些年才出现的新因子类别，因为它的因子值计算依赖于最近才出现的大数据源和大数据分析工具。

你可能想问我：大数据因子可以用来做什么呢？它的用处是很多的，我可以给你举几个例子。

我们在 21 讲 谈趋势跟踪策略时提到过，可以利用投资者的情绪来判断趋势的增强或减弱。如果你想了解其他投资者对一只股票的整体情绪，那你可以用程序实时抓取股吧里的讨论，并用 NLP（自然语言处理）进行语义分析，生成每只股票的市场情绪因子。

你还可以对各个行业公司的招聘信息和薪酬情况进行分析，以此来构造描述各上市公司业务景气度的因子。如果你想预测某些游戏公司的销售情况，还可以利用游戏平台的流水数据，更早更全面地分析出游戏生产商的销售情况，进而构建出游戏公司的销售预测因子。

到这里，我已经介绍了 5 种在多因子模型中经常使用的因子。这里我要强调的是，上面的这些因子并不是我随随便便列出的，而是各大量化投资机构基本都在使用的。量化投资机构正是在这些因子的基础上，构建多因子模型，整合各类投资策略的。 ([View Highlight](https://read.readwise.io/read/01gxrh40trqejpabh71hc0q5ct))
** 公募基金中富国、华泰柏瑞、景顺长城发行的指数增强基金，就是比较典型的多因子框架下运作管理的基金。我在下面的图片中给出了富国中证 500 指数增强基金的价格比，你可以感受下多因子模型在创造稳健超额收益上的效果（具体数据你可以看这个链接）： ([View Highlight](https://read.readwise.io/read/01gxrh46fpekq3nhbv7g0ej491))
** 在 2014 年前后，国内各家公募基金跟各大互联网公司合作，利用各种大数据，发行了多只大数据驱动的基金。比如，广发基金利用百度提供的每只股票的搜索热度大数据，编制成大数据因子，加入到多因子模型中，成立了一只广发中证百度百发策略 100 指数基金；博时基金利用淘宝大数据，成立了一只博时中证淘金大数据 100 指数型基金；南方基金利用新浪财经的大数据，设立了一只南方大数据 100 指数基金。 ([View Highlight](https://read.readwise.io/read/01gxrh4sx062sx8zcr4fpsaqfx))
** 我们怎样训练多因子模型？ ([View Highlight](https://read.readwise.io/read/01gxrh5gcbjt2y434171szsbpb))
** 在线性的多因子模型结构下，我们获得各因子系数的基本操作，就是多元线性回归，回归系数就是每个因子的系数 f1 到 fK。 ([View Highlight](https://read.readwise.io/read/01gxrh5m0khzw2swqf3rc4j750))
** 就像算法工程师们做的各种机器学习模型一样，股票市场上的多因子收益预测模型也需要不断进行更新，所以它的训练是一种滑动训练的思路。用上面的例子来说，就是每天都用最近一年的面板样本，也就是全部股票最近 242 天的数据，来重新拟合模型。并且，还要把最新的因子值输入新训练出来的模型，输出对未来的预测值，这样才能让模型跟得上不断变化的市场。 ([View Highlight](https://read.readwise.io/read/01gxrh62kawtw0pfr2etf3y7cn))
** 在实际训练多因子模型时，一个关键的问题是要事前确定好模型的预测目标，比如是做分钟级别的高频预测，还是天级别的中期预测，抑或是月年级别的长期预测。预测目标是什么，直接决定了训练时数据如何生成，以及因子如何选择。 ([View Highlight](https://read.readwise.io/read/01gxrh691rvkm8bs34yyqjmmnr))
** 这个时候，如果我们把自己当成一个多因子模型，最应该做的是什么呢？就是要列出所有的因子，然后分清主次，给这些因子不同的权重。注意，要把自己最宝贵的时间和精力，分配在最重要的因子上，只有这样才能最大程度地提高成功的概率。 ([View Highlight](https://read.readwise.io/read/01gxrh6t3437axae53ayntx981))
** 多因子模型建立在坚实的数学基础上，是把多个因子整合在一起，发挥出最大作用的投资模型。

在股票投资中，我们考虑的因子主要包括宏观因子、行业因子、技术面因子、基本面因子和大数据因子等。

线性多因子模型的数学形式：r = f1 * X1 + f2 * X2 + … + fK * XK。

线性多因子模型的训练，主要是通过在股票面板样本上进行线性回归完成的。

在进行财富管理时，也可以运用多因子模型的思路：在做事情的时候分清主次，合理分配自己的时间和精力。 ([View Highlight](https://read.readwise.io/read/01gxrh6yfcr3ddx3byjc31ca6t))