:PROPERTIES:
:title: Looking for Hands-on Mac... (highlights)
:author: [[@Saboo_Shubham_ on Twitter]]
:full-title: "Looking for Hands-on Mac..."
:category: #tweets
:url: https://twitter.com/Saboo_Shubham_/status/1605887128746991619
:END:

* Highlights first synced by [[Readwise]] [[2022-12-23]]
** Looking for hands-on machine learning and NLP tutorials. 

Your search ends here! 

(A thread) 👇🧵 ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887128746991619))
** 1. Learn How to Build a Custom Named Entity Recognition (NER) model using @spacy_io 

👉 https://t.co/cRSjKOzNDM ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887150683193344))
** @spacy_io 2. How to Make a Chatbot Using Amazon Lex and AWS Lambda in Python

👉 https://t.co/bjEVo1nwdg ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887172854300673))
** @spacy_io 3. Aspect Based Sentiment Analysis Using BERT 

👉 https://t.co/hS3cdLbHoK ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887195054850048))
** @spacy_io 4. How to use GPT-3 embeddings for Semantic Search, Classification, and Clustering?

👉 https://t.co/LXc8sOpTK4 ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887217267838976))
** @spacy_io 5. How to finetune Transformers Models like BERT on Custom Dataset?

👉 https://t.co/Dt3e2REzPX ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887239413796865))
** @spacy_io Kudos to @pradip_nichite for creating these amazing tutorial videos. Don't forget to give him a follow and subscribe to his youtube channel for more such content. ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887261630922752))
** @spacy_io @pradip_nichite If you found this helpful, two requests:

1. Follow me @Saboo_Shubham_ to read more such content and RT for others to see it as well.
2. Subscribe to my weekly newsletter https://t.co/4CgQ7J2caS to stay updated with all the latest AI developments. ([View Tweet](https://twitter.com/Saboo_Shubham_/status/1605887283747602434))