:PROPERTIES:
:title: readwise/不同能力要看哪些书可以得到提升?
:END:


* metadata
:PROPERTIES:
:author: [[manateelazycat.github.io]]
:full-title: "不同能力要看哪些书可以得到提升?"
:category: [[articles]]
:url: https://manateelazycat.github.io/2023/12/18/how-to-reading/
:image-url: https://rssblog.cn/static/favicon.png
:END:

* Highlights first synced by [[Readwise]] [[2024-01-16]]
** 📌 [[2024-01-16]]
#+BEGIN_QUOTE
•   产品思维： 要多看设计、 材料、 绘画的书， 这样可以培养感性思维。 看电影主要找文艺片看， 一旦感性上来以后， 就知道普通人关心的点在什么地方， 要不永远都是研发的点， 研发的点缺陷在于不是没有能力修复问题， 而是往往方向错了， 用户希望快速过河， 研发容易想搞清楚怎么建设桥更牢固 
#+END_QUOTE\
** 📌 [[2024-01-16]]
#+BEGIN_QUOTE
项目管理： 多看看板或者知名项目管理的材料， 往往都是资源不对齐导致的。 这方面我最大的经验就是， 项目经理一定要在外面被甲方批评， 因为当你被批评的时候， 你做为一个普通人一定是没面子的， 那时候为了自己， 就会想办法找一切资源去搞定事情。 用最快的方式搞定资源协调去解决客户的问题就是最好的项目管理。 项目前期总设计一定要很扎实， 中期实现过程一定要注意正规军打法， 项目后期收敛 bug 和以后面对真实客户， 再正规的流程都是耍流氓自己骗自己， 最快速度修复用户的问题才是最好的流程。 
#+END_QUOTE\
** 📌 [[2024-01-16]]
#+BEGIN_QUOTE
战略： 多读历史书， 最基本的《史记》和《资治通鉴》要读完， 其他的历史书都要没事就读。 当一个人看到几千年的历史就会发现， 我们现代人犯过的错误不是因为我们有了科技就是新问题。 科技只是形式， 人性才是犯错的根本， 而过去人犯了什么错误， 怎么解决的， 一看就知道。 读完历史， 就知道未来怎么走， 该怎么走。 当足够了解自己， 知道自己和团队的基因， 踏踏实实走好未来的每一步， 就是战略。 而战略的根本是要知道足够的历史， 同时了解自己， 克制自己 
#+END_QUOTE\
** 📌 [[2024-01-16]]
#+BEGIN_QUOTE
•   发心： 就读王阳明的《传习录》吧， 我不知道有没有更好的其他书， 我们之所以很多事情没有好结果， 关键就在于最开始的那一念发心不对。 这本书读完以后就不会有读过不同维度的书， 因为不同书的理念不一样在内心相互冲突 
#+END_QUOTE\