:PROPERTIES:
:title: readwise/最近b站看的多 B站上40位宝藏Up主 1_...
:END:


* metadata
:PROPERTIES:
:author: [[Bitturing on Twitter]]
:full-title: "最近b站看的多 B站上40位宝藏Up主 1/..."
:category: [[tweets]]
:url: https://twitter.com/Bitturing/status/1698632403449999453
:image-url: https://pbs.twimg.com/profile_images/1640782991457931264/NiQ4O-sX.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-09-05]]
#+BEGIN_QUOTE
最近B站看的多

B站上40位宝藏Up主

1/https://t.co/huTnVSZTUP

Oeasy的正职是中国传媒大学计算机老师，这可是个宝藏UP主，因为几乎没有他不会的软件！Office三件套、PS、Pr、AE、Ai……都是信手拈来。

全能只是他的特点之一，最有意思的是他的课程还会教你很多哲学知识，比如《道德经》，以至于不少学生调侃，我是来听《道德经》的，顺便学一下PS。《沧海一声笑》的背景音乐也经常是自带笑点。

2/https://t.co/qXvVyQlrIf

都说好图胜千言，但是手残党拍不出好看的照片怎么破？当然是跟着专业人士学习啦~左手Plus就是一位非常专业的摄影Up主，在B站拥有近40W粉丝。在这里你能学到各种专业的摄影知识和拍摄技巧。内容包括人像、风光、旅拍、人文等类型。另外，Up主对手机摄影也有专门的介绍~

3/https://t.co/vcU8YKgYQ5

木鱼水心是bilibili 2018百大UP主之一，在B站坐拥310W+粉丝，在知乎写相关回答的时候，很多人都在评论区强烈推荐这位UP主。他的视频以影评为主，涵盖领域范围较广，热播剧、经典电影、电视剧他都可以信手捏来，而且他的嗓音听着很舒服，声音控们有福啦~

4/https://t.co/gRQbu8kc2j
相比于「木鱼水心」，「电影最TOP」这位UP主的内容更加聚焦，主要集中在两个板块：❶ 细读经典系列：主要解读一些经典电影；❷ 电影最TOP：主要做一些盘点类的内容。比如星爷电影全盘点、十大最经典超级英雄电影盘点等。

5/https://t.co/GJlWTxDXN3

胥渡吧就不用过多介绍了，他们的模仿视频相信很多人在微博或者其他地方都看过，其实他们在B站也有入驻。如果你喜欢看他们的视频，那不妨来B站一次性看个够！

6/https://t.co/cTFqmMHFI0

何止电影在选片的时候，并不会追逐热点电影来吸引眼球，反而经常会挑一些冷门内容进行解读。如果你剧荒，在这也许能淘到不少好片子。

7/https://t.co/PRtp4YXfZl

虽然UP主的名字是虫哥说电影，但是视频内容也会包括一些电视剧。虫哥讲解风格比较幽默搞怪，视频也是以娱乐、搞笑为主，看着乐呵乐呵，解解压还是蛮好的。

8/https://t.co/V91cH68krW

如果你喜欢看吐槽类的电影解说，那么这位刘老师不容错过，尤其是他的代表作之一：逆天吐槽《纯洁心灵：逐梦演艺圈》，一口自带笑点的东北话，全程无尿点，让你从头笑到尾。

9/https://t.co/xbY3l9Qxdf

这是一对羡煞旁人的浙大学霸情侣Up主！在B站坐拥150W+粉丝！你可以在他们的视频中学到各种实用的学习方法。比如如何自律？如何提升记忆力？如何背单词？……

《在家自律性都能暴涨200%的小技巧分享》
《我是如何戒掉手机玩命学习的》
《让记忆效率提升300%的心理学小技巧》

10/https://t.co/Cb0hvME9WB
一条正弦，一位非常自律的学习Up主，在B站分享了很多学习方面的心得。
代表作：

#如何记笔记#系列，内容涉及到地理、物理、历史、语文等，Up主都毫无保留、超级细致地进行了讲解。

11/https://t.co/jl3YfkHeur

高中物理渣到爆，该如何自救？来，B站坤哥助你一臂之力。这是一位专讲高考物理知识的Up主，因为讲解通俗易懂，深受小粉丝们的爱戴~

12/https://t.co/dAZOGgW9O3
大宽物理一位专攻高中物理的UP主。

13/https://t.co/ZwheLfVHFH
猴博士爱讲课
一位既会微积分、大学物理、力学、电工，又会C语言的学霸Up主。要想考试不挂科，你需要猴博士这样短平快的课程。短短几小时，手把手带你过一遍课程。考试的时候至少点东西可以写（编）了……

14/https://t.co/0kqLpMQvBH
美丽科学-BOS
说到化学，很多人的反应就是充满了危险，或者是难闻的气味。但也有很多人就是喜欢化学反应的奇妙，甚至还专门建立了一个网站，相应的内容在B站也有上传，带你从微观的角度体验神奇的化学世界。

比如这个硝酸钾和氯化铵的结晶过程 ，在微观世界实在是太美了！

代表作：《报告老师！你可能给我们做了假实验》

15/https://t.co/ozgEBS0EEi
一位化学科普UP主，带你认识神奇的化学世界。
代表作：《疯狂化学2：元素奇迹》

16/https://t.co/8hortvFWRz
“华农一笑，生死难料”、“山上有火，所里有我”，看华农兄弟的视频，你一定要打开弹幕，类似这样的金句会频繁刷到，只能说网友们实在是太有才了！另外，在视频里你能看到华农兄弟吃动物的一千种理由：“这只竹鼠长得太丑”、“这只鸡淋了雨，可能会生病”、“这只香猪老喜欢打架”……最后的统一结局就是：只好把它烤（炖）了。

17/https://t.co/f0V3FqkbB3
人人短视频精选
一个专注短视频搬运的B站UP主，内容以动画类为主，时长一般控制在10分钟之内。在这里你能看到很多国内外优秀的动画短片，以及部分创意十足的广告等。

18/https://t.co/7Lc6qxxS7m
动画学术趴
专注分享精品短动画的UP主，更新非常勤快，目前在B站的投稿量已经999+。跟其他动漫UP主不同的是，这里面的大多数作品来自各大高校的毕设作品。如果你喜欢看这类动画小短片，不妨关注一下。

19/https://t.co/TpcEwvIFJq
动画少数派上传的内容中有不少讽刺、恶搞类的动画短片，尤其是「HISHE系列」的搬运视频，充满黑色幽默和脑洞。

20/https://t.co/L7cqaVINRz
哔哩哔哩纪录片
很多人不知道的是，B站目前已经是中国最大的纪录片出品方之一。如果你喜欢看纪录片，那认准官方账号准没错。

比如在「瑰宝艺术」频道，就有当年大热的《我在故宫修文物》 。

21/https://t.co/BPADs9APJc
猛犸君侯
一位提供国外最新纪录片资源的Up主。目前的投稿数量高达5,200+，而且画质感人，几乎全部为高清视频，大多数视频都配有中文或英文字幕。

22/https://t.co/FqKBmhGFp9
CCTV 9 纪录频道官方账号，品质必须有保证。比较经典的纪录片有《如果国宝会说话》（豆瓣评分：9.4）、《航拍中国》（豆瓣评分：9.2）。

尤其是《航拍中国》，官方当初在拍摄的时候可是下了血本！拍摄时动用了16架载人直升机、57架无人机，总行程近15万多公里，以另一种视角看祖国壮丽的山河。平常再普通不过的景物，一旦到了高空，完全变成了另一番景象！

23/https://t.co/3bX8RjHhkE
纪录片之家字幕组
这位B站Up主上传的资源简直太感人了！不仅数量多，而且视频质量极高，字幕做得超级棒，双语对照，看着就是爽！

24/https://t.co/igIs7ovGky
一席是一个专注演讲分享的UP主。
听君一席话，胜读十年书。如果从方便理解的角度讲，你可以把一席理解为中国人自己的TED。它经常会邀请各界名人来做分享，且每期分享都配有完整的文字稿，这是非常难得的地方。

除了入驻B站，他们也有自己的网站和APP（各大应用商店均可下载）

https://t.co/8ZzPRk5tDg

25/https://t.co/bchP85F59x
精选了TED上的部分演讲视频，内容都是中英对照。
TED精选演讲

《只要20小时，你就能学会任何事情》
《真正拉开你与周围人之间差距的，是自学能力》
《睡眠到底有多重要，看完不敢熬夜了！》

26/https://t.co/0MZPkbjYCG
折纸的白叔
小时候大家一定玩过折纸吧？纸船、飞机、千纸鹤，肯定都玩过。只是长大了玩得也少了，但这位白叔将这项爱好一直坚持到了现在，曾经还担任了折纸吧的吧主，所以在这个领域是大神一样的存在。如果你想重新拾起这项爱好，又或是培养自己小孩的动手能力，那这个Up主可千万别错过~

27/https://t.co/YXLJaWXW4p
芳斯塔芙
专门做古生物科普的B站UP主。

28/https://t.co/tUe4eWjH6m
表象的本质
经常科普一些物理、化学方面的知识。

29/https://t.co/Z5XvcrhqeE
混乱博物馆
有哪些物质具有剧毒？彩虹为什么是弯的？……如果你也对我们生活的世界充满好奇，那这个Up主值得关注。

30/https://t.co/YtrFNGmKM8
「飞碟说」是B站人气非常高的Up主，出品的视频紧跟社会热点和一些有趣的冷知识，而且是以动画的形式进行呈现，制作水准很高，文案水平也很高。科普类的东西最怕的就是沦于说教，「飞碟说」却巧妙地做到了科普性和趣味性的完美结合。

旗下出品的《飞碟一分钟》和《飞碟说》都是其非常有特色的栏目~

31/https://t.co/BKDkg8CTOb
老撕来撕思维研究室
自称是一个不正经的历史老师，经常给大家普及一些中小学课本里的冷知识，同时也会就校园、社会话题表达自己的观点。总之，是个非常有趣有料的Up主啦~

32/https://t.co/cveun7jxFN
A路人
一位超级逗比的英语Up主，粉丝亲切地称呼他为老大。在B站坐拥210W+粉丝，出品的《洋屁教室》系列视频别提有多火了，用鬼畜的方式帮大家解决了很多典型烦人的英语语法问题。

代表作：《洋屁教室----让英语做你的舔狗》

33/https://t.co/2BJUapzeUq
口语老炮儿马思瑞
不愧自称老炮儿，这位来自美国的Up主说的中文实在是太棒了！他的英语口语教学视频也是另辟蹊径，出品了一系列明星口语分析视频，从发音、用词、语法角度切入。目前被拆解的国内明星和企业家有：刘亦菲、成龙、吴亦凡、马云等。相比于枯燥的教学，这种寓教于乐的教学方式更容易被人接受。

代表作：《明星英语口语分析》系列视频

34/https://t.co/JEKUpj8vcY
葉（叶）子先生酱
一名日语UP主。叶子之前是沪江网校的人气日语老师，来到B站后，也是非常受欢迎，她会从零基础开始教你如何学日语。

代表作：【日语课程】标日初级精讲BY萌萌哒葉子先生》

35/https://t.co/OVPaY30ql8 
韩语养乐多老师
一位韩语教学UP主，视频内容主要以韩语歌曲教学为主。另外，也会有一些韩语发音的教程。老师的声音很好听，颜值也不错，颜控们有福了~

代表作：《韩语发音教学2017新版【合集】》

36/https://t.co/TrC3UWMoRs
《非正式会谈》是一档「国际范儿」的文化访谈节目，每一期有11位来自各个国家的青年和四位补刀专业户：大左、杨迪、陈铭、陈超，在各种欢声笑语中对一些热门话题或者当下青年所关心的话题展开讨论。

37/https://t.co/9ZudE6fJn9
大漠叔叔真实的身份是一位海南警察，所以在他的视频里你经常能看到一些跟警务相关的科普内容，但风格一点儿也不严肃刻板，反而充满了诙谐与幽默，所以看起来自然也不会觉得是在说教。

38/老师好我叫何同学
https://t.co/K4WCsDaZne
之前有一个关于5G测速的讲解视频刷爆网络：《一看就懂！用水讲明白为什么5G更快》，在B站也曾占领日排行第1的位置。这个视频就是这位1999年出生的何同学制作的，他在B站出品了很多科技测评视频，是一位非常有才华的小伙子。

39/https://t.co/VBf6WK3de1
「科技美学」是一个数码UP主，目前在B站有近200万的粉丝量，主要对一些最新的数码产品进行测评，内容主涉及手机、平板、电脑等，比如现在刚发布的华为Mate30 Pro、小米9 Pro 5G等。如果你在入手前有疑惑，不妨来看看专业人士的测评咯~

40/https://t.co/QS7E6dvVyp
「手工耿」是一位脑洞超大的手工UP主。像平常说到手工，我们第一时间想到的可能就是皮具或者一些木制品。但耿哥的画风非常奇特，经常出奇奇怪怪的作品，比如：自制倒立洗头机、自制胸口碎大石套装，很多网友戏称：耿哥出品，必属废品。他独特的视频风格在B站也收割了一大波粉丝，目前关注人数已经220W+。 
#+END_QUOTE\