:PROPERTIES:
:title: readwise/07 | 投资多久才算长期？
:END:


* metadata
:PROPERTIES:
:author: [[youzhiyouxing.cn]]
:full-title: "07 | 投资多久才算长期？"
:category: [[articles]]
:url: https://youzhiyouxing.cn/n/materials/188
:image-url: https://readwise-assets.s3.amazonaws.com/static/images/article1.be68295a7e40.png
:END:

* Highlights first synced by [[Readwise]] [[2023-12-20]]
** 📌
#+BEGIN_QUOTE
不过更有意思的是，当时间拉长到十年以上这个区间，持有股票的最差收益率，已经开始比持有债券和国债更高了。到了二十年以上，你可以获得的最差收益率也是正的。也就是说，在这个时间尺度上，只要持有不动，你毫无亏钱的可能。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxb3tt0fq6sxxxn39ct033][View Highlight]]
** 📌
#+BEGIN_QUOTE
不知道你有没有发现，这些如今人尽皆知的好公司、白马股、核心资产，股价的发展过程并不是线性的。它们往往是蛰伏很多年，然后在一两年的短时间内完成主要的涨幅。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxctd64vewcp27n6k11bdx][View Highlight]]
** 📌
#+BEGIN_QUOTE
「轮动」对投资的影响

长期投资之难，还体现在另外一个重要的方面，就是*市场总是「轮动」的。* 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxeyeet1r1xzdktxx3e27r][View Highlight]]
** 📌
#+BEGIN_QUOTE
举个例子。如果我们回看历史，会发现美股市场在 1970 年代和 1980 年代的表现简直有天壤之别。在 1970 年代，美国经历了一系列的危机事件，比如越战升级、布雷顿森林体系瓦解、中东石油危机等等。而从 1969 年末到 1979 年末这整整十年时间，美国的道琼斯工业指数和标普500指数起起伏伏，十年下来几乎没怎么涨，如果算上通货膨胀甚至是亏损的。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxf9b05vwyy2zjwt8cgae3][View Highlight]]
** 📌
#+BEGIN_QUOTE
但整个 1980 年代，黄金的价格跌了一半之多。所以，*没有某类资产能永远表现最好，这就是所谓资产表现的轮动。*

同样，*在一个资产类别里，投资风格也可以轮动。*比如从 2009～2020 年这段美股大牛市中，所谓的成长股表现非常出色，而价值股表现则非常凄惨，可以说惨到了历史最低水平。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxg91dj06kxhrxk3g556np][View Highlight]]
** 📌
#+BEGIN_QUOTE
说了这么多轮动，它对我们长期投资的影响是什么呢？我觉得有两个非常大的影响：

第一，*如果当前市场最受到追捧的那个主题，和你喜欢或者擅长的主题不一致，那么再坚定的人，也会对自己的持仓产生怀疑。*比如你可能对汽车、地产很熟悉，但看不懂各种热门的科技公司在做什么，可能就会想，市场还会轮动到我这边吗？我是不是要放弃现在的持仓，切换到其他地方呢？这种过程中的未知感和不确定感，其实是非常难熬的；

第二，*更关键的是，哪怕你的投资表现不错，但市场上总会有表现更好的、更热门的东西。*比如你可能在一两年里跟随大盘上涨了 40%～50%，已经是很好的收益了，但别的人可能投了蔚来、拼多多、特斯拉、比特币，结果一两年翻了五倍十倍……看到别人赚得比自己多总是更难受的，这也会对我们的长期投资造成影响。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxgzyrkmryw5ayax614t9r][View Highlight]]
** 📌
#+BEGIN_QUOTE
我们通过投资获得的收益，和这三个因素有关：本金、时间和收益率。

*收益 = 本金 ×（1 + 收益率）^ 时间* 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxh97akd8pma38y9y6crem][View Highlight]]
** 📌
#+BEGIN_QUOTE
因此，对我们来说，可能更重要的事情是，放下焦虑、专注在工作和生活上，在我们自己不断变得更好的同时，去收获更多的工资、股权等其它收入。与此同时，做好资产配置，根据自己的兴趣慢慢地拓展能力圈，在合理的范围内提高我们能获得的收益率。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxhhyvg5kkm01medarf4k3][View Highlight]]
** 📌
#+BEGIN_QUOTE
这就是，为什么我们需要，长期主义。 我们会在足够安全的位置下注，等待市场给予确定性的回报。至于它什么时候来，反而不是需要那么时时刻刻关心的事。 想掌握所有事情的所有因果，运筹帷幄，指点江山，这背后的本质是希望自己全知全能，或者至少是一个聪明人。 而投资的世界中，可能先不把自己当成是一个聪明人，而是通过提升认知后，相信并长期践行一些朴素的道理，会更好。 1997年，亚马逊创始人贝佐斯写下了第一封致股东的信。这个后来成为了世界首富的人，在这封信里，留下了一句定海神针级别的话： ——It’s all about long term. 一场 1.6 万亿市值的增长之旅就此开始。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxmtr3m637t121ary0r5vb][View Highlight]]
** 📌
#+BEGIN_QUOTE
应该如何界定短期、中期和长期，知名投资人冯柳，曾经做过一段精彩的论述，说的是∶ 一般来说，大家对短线、中线、长线的定义是以时间长短来进行划分，三五天走的是短线，抱牢股票放几年的为长线。这种分类没错，但却没有意义，对操作没有帮助。下面我要用的分类方法不是以表观时间进行划分，而是以其操作内涵来表现，也就是说，我所定义的短线可以做几个月也叫短线，中线可以只做几天也叫中线，为什么要这样呢?这是为了帮助大家对各种操作进行理解，从而选择适合自己能力的策略以及纠正那些与策略不相符的错误。 什么是短线?短线就是尊重市场、依势而为，它没有多少标的物的选择限制，只讲究高买然后更高地卖，对利润不设要求，但对亏损严格禁止，有3点以上赢利把握就可入场。它不要求对企业基本面的熟悉掌握，但需要良好的市场嗅觉和严格的纪律。其关键的一点是顺势，也就是说，如果势道不改，就可以一直持股，像过去的科技股牛市时，往往一涨就是几个月，这种时候你虽然报着短线的想法入场，但万不可因利润超过了想象或时间超过了预期而过早退场。所以说，敢于胜利、怯于失败是短线操作的精髓! 而中线就不一样了，它需要对基本面有充分掌握，对价格估值系统有良好的认识，它的标的物应该是那些经营相对稳定、没有有大起大落的企业，当市场低估时买进，高估时卖出，讲究的是低买高卖，预期利润目标在 20%以上方可入场，同时设 8%的止损位。它要求你是价格的发现者，勇于做大多数人所不敢做的事，要求你理解市场但不完全跟从市场。 那长线呢?很多人认为这是最容易做的，只要买进不动就可以了，其实这完全是误解。在所有的操作策略中，长线的要求最高。他需要对企业有着极为深刻的认识，对自己有着更为坚强的控制，他了解积累和成长的非凡威力，清楚把握企业未来数年的发展趋势，以投资的心态分享企业的成长。他的标的物是千里挑一，他对利润的要求是数以10 倍计，在这样的机会面前它不会惧怕任何亏损，不会设置除基本面外的任何止损指标，因为在十倍增长的股票面前，哪怕 50%以上的亏损都是微不足道的，对它来说，买进不卖是最好的策略，自信、尊重客观价值、不理会乃至勇于对抗市场是必备的投资品质，日常 20%30%的波动在这样的前景面前是不应去考虑的，不要放弃在大牛股上的布局，不在大牛股上做空是永远需牢记的训条。只有这样，股票才能够真正成为改变一生的东西。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _07 | 投资多久才算长期？_ by youzhiyouxing.cn
*** [[https://read.readwise.io/read/01grrxpp7mpwp9cdp7e12prd84][View Highlight]]