:PROPERTIES:
:title: readwise/番外三｜有哪些能够持续学习的参考资料和相关网站？
:END:

* metadata
:PROPERTIES:
:author: [[geekbang.org]]
:full-title: "番外三｜有哪些能够持续学习的参考资料和相关网站？"
:category: [[articles]]
:url: https://time.geekbang.org/column/article/420187
:tags:[[gt/程序员的个人财富课]],
:image-url: https://static001.geekbang.org/resource/image/34/31/34bbdf7f6b5ef0871b214fd098d34931.jpg
:END:
* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
建立理财观：《富爸爸穷爸爸》 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
投资指数基金：《漫步华尔街》 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
了解对冲基金历史：《富可敌国：对冲基金与新精英的崛起》 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
机器学习入门：《机器学习》 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
价值投资圣经：《巴菲特致股东的信》 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
巴菲特从来不使用艰深的术语或模型，而是用平实却深刻的语言来讲道理，所以这些资料也基本没有阅读门槛。但是，因为这些信内容丰富，信息量很大，需要你投入大量时间消化理解。如果你有精力，最好是读英文版的。我把中英文版本的资料链接都放在了这里，你可以根据自己的需要来学习。

巴菲特致股东的信（1957 至今，中文）

巴菲特致股东的信（1977-2020，英文原文） 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
深度学习的经典教材：《神经网络与深度学习》

对于那些有一定机器学习基础，希望进一步研究的同学，我和王喆推荐阅读复旦大学邱锡鹏老师的《神经网络与深度学习》。 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
行业分析框架：各券商研究所的研究报告

券商就是证券公司，大型券商一般都有自己的研究所，它们的研究报告质量往往高于普通财经媒体推送的文章。

但是，由于这些报告的目标读者是基金公司的专业投研人员，所以对普通投资者不太友好。想要转行到投资行业的同学，还是需要投入一定精力去学习的。我在下面给出了几家券商研究所的官网链接，你可以去搜索并尝试更多券商的研究服务，通过比较来选择自己的学习资源。

国泰君安证券研究所

海通证券研究所

华创证券研究所 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
多因子模型：Barra USE3 handbook（美国股票风险模型手册第 3 版）

这个手册是由 BARRA 公司发布的，该公司是量化投资技术提供商，量化投资的先驱。这个手册的篇幅不太长，一共几十页，但它详细介绍了股票市场多因子模型的理论框架和实证细节。而且，介绍时描述规范清晰，没有陷入无意义的细节，很适合作为你转入专业量化投资行业时的起步项目。我当时开始做量化投资的时候，花了 8 个月把 USE3 的架构在 A 股数据上适配实现，这个项目做完了，也基本上入门了。 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
因子投资：《因子投资：方法与实践》

在我看来，这是近年来最好的讲解多因子模型的专著，不仅思想深刻，表述也准确生动。这本书很适合那些想要深入研究多因子模型，并开发因子投资策略的同学。 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
量化分析圣经：《主动投资组合管理》

这本书的两位作者是量化投资行业的先驱者，并且都曾经担任 BARRA 公司的研究总监。它的内容相对较深，描述也偏实践，介绍了许多深刻的真知，书中的很多论述精彩而透彻。这本书被奉为量化组合投资的业界“圣经”。

不过，该书有些章节撰写得深度不一，初学者阅读起来可能会觉得吃力。所以我推荐的阅读方法是：首次阅读时，不必纠结看不懂的细节，只要不影响后续阅读就跳过；有一定基础后，再反复阅读本书，每次阅读都会获得新的体会。 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
tushare有数据 
#+END_QUOTE\