:PROPERTIES:
:title: readwise/Looking for Hands-on Mac...
:END:


* metadata
:PROPERTIES:
:author: [[Saboo_Shubham_ on Twitter]]
:full-title: "Looking for Hands-on Mac..."
:category: [[tweets]]
:url: https://twitter.com/Saboo_Shubham_/status/1605887128746991619
:image-url: https://pbs.twimg.com/profile_images/1670107849815478273/Q3oUhtHM.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
Looking for hands-on machine learning and NLP tutorials. 

Your search ends here! 

(A thread) 👇🧵 
#+END_QUOTE\
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
1. Learn How to Build a Custom Named Entity Recognition (NER) model using @spacy_io 

👉 https://t.co/cRSjKOzNDM 
#+END_QUOTE\
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
@spacy_io 2. How to Make a Chatbot Using Amazon Lex and AWS Lambda in Python

👉 https://t.co/bjEVo1nwdg 
#+END_QUOTE\
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
@spacy_io 3. Aspect Based Sentiment Analysis Using BERT 

👉 https://t.co/hS3cdLbHoK 
#+END_QUOTE\
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
@spacy_io 4. How to use GPT-3 embeddings for Semantic Search, Classification, and Clustering?

👉 https://t.co/LXc8sOpTK4 
#+END_QUOTE\
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
@spacy_io 5. How to finetune Transformers Models like BERT on Custom Dataset?

👉 https://t.co/Dt3e2REzPX 
#+END_QUOTE\
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
@spacy_io Kudos to @pradip_nichite for creating these amazing tutorial videos. Don't forget to give him a follow and subscribe to his youtube channel for more such content. 
#+END_QUOTE\
** 📌 [[2022-12-22]]
#+BEGIN_QUOTE
@spacy_io @pradip_nichite If you found this helpful, two requests:

1. Follow me @Saboo_Shubham_ to read more such content and RT for others to see it as well.
2. Subscribe to my weekly newsletter https://t.co/4CgQ7J2caS to stay updated with all the latest AI developments. 
#+END_QUOTE\