:PROPERTIES:
:title: readwise/今天说一个不开发也能独立的故事。 曾经有一段时...
:END:


* metadata
:PROPERTIES:
:author: [[Yangyixxxx on Twitter]]
:full-title: "今天说一个不开发也能独立的故事。 曾经有一段时..."
:category: [[tweets]]
:url: https://twitter.com/Yangyixxxx/status/1751070566113792207
:image-url: https://pbs.twimg.com/profile_images/1651419607780188160/CFQ-LX55.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-02-06]]
** 📌 [[2024-01-28]]
#+BEGIN_QUOTE
今天说一个不开发也能独立的故事。

曾经有一段时间，自习室这个形态的产品很火，什么timing，学而思，人人网，costduy，各种开始做在线自习室的。

但投入开发就需要大量的研发资源，而且还需要音视频流资源，这些变动成本是无法降低的。那用户来了到底能不能赚钱呢？其实你也是不知道的。

换做是你，你会怎么做？跑去市场分析？纠结投入成本？往往大部分人，都会死在这里。我们看看高手是怎么做的：

最好的办法参考“榛子会发光”搭建云自习。

她是个物理学phd，平时做做留学文书。自己利用Trello+Zoom 搭建了云自习。

方法也很简单，Trello上做出板块，比如每日打卡（记录当天的todo和完成情况），收获分享，以及交流交友。

做了这些基础动作就够了吗？你想验证的，其实统统都能验证：

她不仅做了这些，还构建了一些完成任务后的积分玩法，自己做排行榜，发电子勋章给用户。

有一个24小时的Zoom一直开着，全体静音不断轮播视频流。

然后她去知乎，在公众号，在各种能曝光给大学生（留学生）的地方，去散播这个云自习，靠她自己一个人，每天就有几千人访问这个Trello，zoom在线经常小100。

再后来为了增加会员制度，迁移去了discord，在discord里更能一体化完成这些事情，并通过discord的频道会员进行收费。

这一切都没有做过任何“开发”
但却通过这个获得了“留学文书流量”，以及忠实的“会员付费”用户。

当你看见别人做成功了，你觉得有希望，自己想去尝试，因为别人已经验证完了，但你不知道的是，别人系统的运营过程是什么。如果只看产品表象，大量的产品是同质化的，为什么成功的却只有二三？

回过头来，就算你做了开发，搞出来了app，你能像她一样，持续不断写软文，曝光，找到“想自习”的人，不断设置运营策略，发积分，做排名，发电子勋章，一步步做起来吗？

或许你做完之后，仍然回归到了“我该怎么推广”这一话题上来。

那为什么不能先推广起来呢？

如果有一件事情，你不会做，只有两种选择：
1、学会它
2、找一个会做的人

————————

历史总是出奇的相似

后来有个哥们，体验了clubhouse之后问我，是不是可以做线上英语角？

我就把这个故事讲了一遍给他。

如果你不是小红书，b站这种流量池，想单靠一个多人在线语音聊天室的功能玩通这个模式，我就问了他几个问题：

1、你试过用yy语音 或者腾讯会议 或者discord等其他方式进行过尝试吗？
2、单纯语音和可以投屏，对用户场景有本质影响吗？
3、去哪里获客？
4、练什么口语内容？聚焦哪里？
5、人们都想找英语好的人练英语，这里面是否存在供需问题？还是说只要张嘴，对方行不行已经无所谓了？那不在意对方水准，只是想张嘴的人是什么样的人？
6、如果两个英语都差的人，能坚持练几天？

基于他无法回答这几个问题，哥们听从了建议，自己开始跑去做初步尝试了：

1、先尝试雅思口语，多少用户有一些英语基础，只是可能表达不出来
2、建了个qq群
3、建了一个腾讯配对表单，可以在线按时间和主题找语伴
4、小红书开始发“求雅思口语搭子”
5、把人搞到群里
6、大家开始进腾讯会议

为了了解情况，还建议大家把录屏上传到表单里方便复习回听

通过这种最简单的运营策略，帮助朋友收集了种子用户，了解了具体的画像情况和在线英语角的产品形态可能存在的问题。

看吧，很多时候，都可以无开发启动独立项目。重点在于，你对这个事情有多大的渴望，你究竟想不想通过这件事帮助到别人，而不是想着怎么赚钱。 
#+END_QUOTE\