:PROPERTIES:
:title: readwise/Logseq 是个好工具，就是学习曲线有点陡峭。...
:END:


* metadata
:PROPERTIES:
:author: [[henices on Twitter]]
:full-title: "Logseq 是个好工具，就是学习曲线有点陡峭。..."
:category: [[tweets]]
:url: https://twitter.com/henices/status/1722422760465379364
:image-url: https://pbs.twimg.com/profile_images/1553267213410349056/quQySPWc.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-11-10]]
#+BEGIN_QUOTE
Logseq 是个好工具，就是学习曲线有点陡峭。我就走了很多弯路，Logseq 的高阶用法是利用 query 建立自己的工作流 （workflow），但是入门还是建议从基础功能的使用开始 （日志，双链，大纲，本地存储 ）。                              
                                                                                                    
关于 Logseq 的使用，community 用户 Luhmann 写了不少高质量的 Logseq 文章，阅读一遍一定会有收获。https://t.co/CSuObYoGFZ

Luhmann 在Logseq forum 的经典文章还有下面两篇，三个强大的工具和三个选择，非常得好。                 
                                                                                                    
Three power-tools I wish I’d known about when I started using Logseq                                
https://t.co/nzOU1YRdkZ
                                                                                                    
\- Templates                                                                                         
- Aliases                                                                                           
- Page-tags                                                                                         
                                                                                                    
Three Choices New Users Need to Make                                                                
https://t.co/fNhcV49yai                              
                                                                                                    
- First choice: to use a daily journal or not?                                                      
- Second Choice: tags, hierarchy, or page-tags?                                                     
- Third choice: One graph for everything, or multiple graphs?                                       
                                                                                                    
我自己也写过 Logseq 三篇，现在由于笔记系统上手熟练，输出反倒不如从前，有点惭愧。                    
                                                                                                    
Logseq 试用报告 
https://t.co/7Ls9rOE6lx 
Logsdq 使用小结（二）                                                                  
https://t.co/OjjyocOZIq                                                                  
Logseq 使用小结（三）
https://t.co/xkkKD8rLJj 
#+END_QUOTE\
** 📌 [[2023-11-10]]
#+BEGIN_QUOTE
工具仅仅是工具，记笔记的态度比笔记方法、第二大脑这些重要的多，这是我更深层次的体会。

其实工具并不是那么重要，最重要的还是平时要记录，要定期输出。IT 界有一个著名的段子，你以为你是在写 blog 其实你只是在折腾 wordpress ：）

https://t.co/jwAZb8DWZS 
#+END_QUOTE\