:PROPERTIES:
:title: readwise/在 ChatGPT 刚出来的时候，很多大学就禁止...
:END:


* metadata
:PROPERTIES:
:author: [[dotey on Twitter]]
:full-title: "在 ChatGPT 刚出来的时候，很多大学就禁止..."
:category: [[tweets]]
:url: https://twitter.com/dotey/status/1749288702067564801
:image-url: https://pbs.twimg.com/profile_images/561086911561736192/6_g58vEs.jpeg
:END:

* Highlights first synced by [[Readwise]] [[2024-01-22]]
** 📌 [[2024-01-22]]
#+BEGIN_QUOTE
在 ChatGPT 刚出来的时候，很多大学就禁止使用 ChatGPT、GitHub Copilot 等 AI 辅助工具，防止学生作弊，而哈佛大学意识到，如果不利用 AI 的强大潜力来丰富学生的学习过程，那将错失一个宝贵机遇，这是非常可惜的。所以他们积极的基于 GPT 开发了一套 AI 辅助教学工具，尝试在计算机科学教育中应用生成式人工智能！

这套工具包括三部分功能：

1) “解释高亮代码”，用于解释选中的代码；
解释高亮代码是一个 VSCode 插件，为学生提供代码啊解释

2) 代码风格评估工具 style50 的增强版；
也是一个 VSCode 插件，它像人类教师一样提供代码改进优化的指导，帮助学生更清晰地理解和实践代码的语法优化。

3) CS50 小黄鸭，一个能够通过多个平台回答课程相关问题的聊天机器人。
CS50 小黄鸭的名字来源于小黄鸭调试法（一种调试代码的方法，耐心地向一只小黄鸭解释每一行程序的作用，以此来激发灵感与发现问题），它可以类似于ChatGPT聊天，也可以自动回复论坛上的学生提问，还可以作为 VSCode 插件辅助编程。

从技术上来说，对于有 LLM 开发经验的来说并不神奇，聊天是基于 OpenAI 的 ChatComplition API，回答问题是基于 RAG（检索增强生成），把教材和上课的字幕嵌入，学生提问时根据相似度检索，找到相关的课件或者讲课字幕，然后让 AI 整理回复！

https://t.co/xR15ndgNFX 通过一个可视的爱心计数器来限制使用频率。每位学生初始有 10 颗爱心，每隔三分钟可以恢复一颗。每次与 CS50 小黄鸭互动都会消耗一颗爱心，这样可以防止滥用行为。这样做还有助于降低运行 https://t.co/xR15ndgNFX 的成本。大约每位学生每月 1.90 美元，每条提示词大约 0.05 美元。

从学生的反馈来看，是非常积极和正面的！部分学生反馈节选：

> “简直难以置信，就像有一个私人辅导老师一样...我特别欣赏 AI 机器人回答问题时的客观公正，即使是最简单的问题也不会被小觑。它展现出了超乎寻常的耐心。”

> “我真的很感谢这些 AI 工具，特别是在当前 AI 在编程中越来越普及的背景下。能够提前适应与 AI 工具的协同工作，感觉很棒，而不是觉得这些工具在阻碍我们。CS50 课程推出自己的 AI 版本也很让人欣赏，因为仅仅使用像 chatGPT 这样的工具可能会削弱学习效果。”

> “AI 工具对我帮助很大。它们向我解释了一些我不太清楚的概念，并教会了我解决特定问题所需的新知识。AI 工具不仅给了我足够的提示让我独立尝试，还帮我分析错误及可能遇到的问题。”

当然也存在一些问题，主要问题还是“幻觉”，在课程相关的问题，存在一定的错误率，尤其是软件工程相关问题，正确率仅为 48%！不过 CS50 课程相关的问题，准确率有 88%，另外随着时间的推移，CS50 的大纲也有变化，而 GPT-4 的模型的训练时间相对要滞后。

哈佛大学下一步将会继续完善他们的 AI 教学工具，例如批改作业，另外也会将课程从 CS50 扩展到其他学科！

完整内容可以参考：https://t.co/pFCXbE9jWk 
#+END_QUOTE\