:PROPERTIES:
:title: readwise/Collections - Qdrant
:END:


* metadata
:PROPERTIES:
:author: [[qdrant.tech]]
:full-title: "Collections - Qdrant"
:category: [[articles]]
:url: https://qdrant.tech/documentation/concepts/collections/
:image-url: https://qdrant.tech/images/social_preview.png
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-07-03]]
#+BEGIN_QUOTE
Distance metrics are used to measure similarities among vectors. The choice of metric depends on the way vectors obtaining and, in particular, on the method of neural network encoder training.

Qdrant supports these most popular types of metrics:

•   Dot product: `Dot` - [https://en.wikipedia.org/wiki/Dot_product](https://en.wikipedia.org/wiki/Dot_product)
•   Cosine similarity: `Cosine` - [https://en.wikipedia.org/wiki/Cosine_similarity](https://en.wikipedia.org/wiki/Cosine_similarity)
•   Euclidean distance: `Euclid` - [https://en.wikipedia.org/wiki/Euclidean_distance](https://en.wikipedia.org/wiki/Euclidean_distance) 
#+END_QUOTE\
** 📌 [[2023-07-03]]
#+BEGIN_QUOTE
For search efficiency, Cosine similarity is implemented as dot-product over normalized vectors. Vectors are automatically normalized during upload 
#+END_QUOTE\
** 📌 [[2023-07-03]]
#+BEGIN_QUOTE
Collection with multiple vectors

*Available as of v0.10.0*

It is possible to have multiple vectors per record. This feature allows for multiple vector storages per collection. To distinguish vectors in one record, they should have a unique name defined when creating the collection. 
#+END_QUOTE\
** 📌 [[2023-07-03]]
#+BEGIN_QUOTE
Collection aliases

In a production environment, it is sometimes necessary to switch different versions of vectors seamlessly. For example, when upgrading to a new version of the neural network.

There is no way to stop the service and rebuild the collection with new vectors in these situations. Aliases are additional names for existing collections. All queries to the collection can also be done identically, using an alias instead of the collection name.

Thus, it is possible to build a second collection in the background and then switch alias from the old to the new collection. Since all changes of aliases happen atomically, no concurrent requests will be affected during the switch. 
#+END_QUOTE\