:PROPERTIES:
:title: readwise/做出海业务，最懵圈的就是海外公司设立和收款了。摸...
:END:


* metadata
:PROPERTIES:
:author: [[readyfor2025 on Twitter]]
:full-title: "做出海业务，最懵圈的就是海外公司设立和收款了。摸..."
:category: [[tweets]]
:url: https://twitter.com/readyfor2025/status/1747915433456672964
:image-url: https://pbs.twimg.com/profile_images/1746102064730742784/jsnSJgwq.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-01-19]]
** 📌 [[2024-01-19]]
#+BEGIN_QUOTE
做出海业务，最懵圈的就是海外公司设立和收款了。摸索了一个月，完成了美国公司注册、税号申请、开户、收款、税务代理。
以下是详细流程和knowhow，帮你节省至少50个小时。
1 选择注册代理机构。
选择了firstbase，从注册、税号、到开户一条龙。价格不是最优，但整体流程透明，客服的反馈也及时。这类平台挺多，stripe也有Atlas，更多平台可以看这个推文 ：https://t.co/q1hhLigK42 
#+END_QUOTE\
** 📌 [[2024-01-19]]
#+BEGIN_QUOTE
2 选择公司类型
选择了有限责任公司（LLC）。
目前非美国公民在美国可以开立有限责任公司LLC、股份制有限公司（C-Corp）。只要你没有后续公开融资的安排，LLC是最合适的公司类型，适合初次出海的选择，优势：成立的费用低，审批简单；运行成本低，不像C-Corp要求繁琐的运行规范；税收灵活，避免了双重征税，因此给税局的报表较少，将来的维护成本也低。 
#+END_QUOTE\
** 📌 [[2024-01-19]]
#+BEGIN_QUOTE
3 选择哪个州
选择了怀俄明州（Wyoming）。
结合LLC比较热门的选择地：特拉华州、怀俄明州、内华达州，怀俄明州的优势最明显：注册成本、维护成本低，没有企业所得税、个人所得税或特许经营税，销售税率也很低，企业主的报告义务最少。 
#+END_QUOTE\
** 📌 [[2024-01-19]]
#+BEGIN_QUOTE
4 在firstbase注册的主要环节
①录入公司名称、类型、注册地、股东信息（需要上传护照、驾照-须翻译）。注册代理费＄399，我拿了推广链接，有95折优惠。
②选择税务代理：通过网站提交税务报表，帮你进行申报，＄299/年。可以找本地华人事务所，有专们的客服，中文沟通。
③美国地址和邮箱代理：必须要有美国真实地址，并需要代理机构帮助提供信函的转寄服务，＄350/年 。这步需要跟公证公司视频连线，出示护照，并有简单的英文对话，证明是你本人，并同意把邮箱给代理机构复杂。
④以上跑完，系统会自动提交联邦税号EIN（相当于企业的身份证）的申请，等了大概40天，EIN才下来，有些人时间会短很多，挺随机的。 
#+END_QUOTE\
** 📌 [[2024-01-19]]
#+BEGIN_QUOTE
5 银行开设公司账户
选择firstbase推荐的水星银行，全程自助线上受理，大概2-3天账号就下来了（储蓄账户，非信用账户）。在美国想开大行的账户，手续繁琐且对账户日均余额要求高。水星银行申请容易、KYC也比较简单，日均余额起点低，咨询了美国的朋友，这个水星严格说不算银行，但暂时没啥风险。 
#+END_QUOTE\
** 📌 [[2024-01-19]]
#+BEGIN_QUOTE
6 成立后的税务问题
选择美国华人开的税务代理， 价格看税务复杂度，需要审核后来报价（含联邦申报+年审）。了解到的一些初步信息：
① 公司亏损=不用缴税，需要申报。
② 收入不要谎报。国税局irs对收入数据很清晰，平台上只要填了EIN(公司税号），数据都是可以被反查。
③ 支出是国税局irs无法详细查到的。可以使用代理服务，产品成本增加等方式给自己增加成本，不需要发票。有合同，或者交易记录就可以。
④ 缴税，前两年可以亏损，一般建议第三年交一点税，第三年做可以做微利。缴税是利润的21%。
⑤ 消费税的问题：尽量不代收消费税，stripe可以不代收。美国各州的消费税征收阈值在10万刀收入或200笔交易以上，个别州更高，暂时不用管。 
#+END_QUOTE\