:PROPERTIES:
:title: readwise/番外一｜王喆对话李腾：程序员对基金经理的灵魂十问（上）
:END:


* metadata
:PROPERTIES:
:author: [[geekbang.org]]
:full-title: "番外一｜王喆对话李腾：程序员对基金经理的灵魂十问（上）"
:category: [[articles]]
:url: https://time.geekbang.org/column/article/417482
:tags:[[gt/程序员的个人财富课]],
:image-url: https://static001.geekbang.org/resource/image/93/39/93584ba0f52ae7363c68ccd315fb6639.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
这时候就是在考验你的耐心了。不要看着别人炒股赚钱了，就急着上车，以至于慌不择路地选择了一些质量很低劣的学习资源。这里我想强调的是什么呢？世界这么大，投资机会年年有、到处有，也不必急于一时。你首先要做的，不是赶上某某专家推荐的那趟车，而是快马加鞭地通过持续学习建立自己的认知优势。这一点，我们在这门课的 01 讲 就已经说过了：“对自己的认知，尤其是对自己能力边界和风险承受能力的清晰认知，是比找到一个顶级投资策略，或抢手的投资标的更关键的事。” 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
最后提一句，如果要学习巴菲特，建议优先学一手资料。比如，读巴菲特每年给股东的公开信，这个时间绝对值得投入。 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
问题五：专业投资者怎么评价索罗斯和他的投资理论？ 
#+END_QUOTE\
** 📌 [[2023-04-14]]
#+BEGIN_QUOTE
李：索罗斯当然是一位伟大的宏观交易大师。我想我们应该学习他的思考方式，而不是盲目地模仿他的宏观对冲交易，因为他的很多优势也是我们无法复制的。

我们在 23 讲 还提到了他用宏观对冲基金狙击英镑的故事，就拿这个举例吧。索罗斯的这次巨大成功，是基于他自身的两个优势的。第一个是他本身就有经济学的专业功底，并且进行了大量的研究。正是在这个基础上，他做出了一个极强的判断，就是英镑会贬值。这时候，就连英国政府自己都不敢做出这样的判断，还在砸钱维护英镑汇率。他的第二个优势，是他有足够的能力和资源，可以借入上百亿美元的资金，也就是加杠杆去做空英镑，然后进一步触发这个英镑贬值的进程。

索罗斯的这两点我自己是做不到的。我很少能对一些宏观问题有如此之强的判断，另外我也没有本事从银行那儿借来上百亿美元的贷款。不过，索罗斯在进行宏观对冲交易的时候，依据的一些基本逻辑其实没有那么高深，我们可以在经济学或者市场中学到。只是你要做得无比娴熟，有极高的置信度。只有做到这个水平，你才敢于加杠杆，然后去下重注，博取一个巨额的收益。

而且，索罗斯这种加杠杆去赌一件事的操作风格，对我们普通人来说其实风险是非常大的。一旦做错，就可能倾家荡产。有些盲目加杠杆的人，可能做之前都没有想好一个基本的问题：一旦出现了意料之外的事情，自己有没有能力处理？我们身边也有很多这样的事情：有人贷款去赌一只龙头股，结果这只龙头股后来发生意外的暴跌，就把他所有的本金和贷款都跌光了。这样，他不仅原始积累没有了，还背上了巨额的债务，整个家庭的财务状况都面临着风险。 
#+END_QUOTE\