:PROPERTIES:
:title: readwise/《套利的五大模型揭秘》（上篇） 之前有分享过我...
:END:


* metadata
:PROPERTIES:
:author: [[MetaHunter168 on Twitter]]
:full-title: "《套利的五大模型揭秘》（上篇） 之前有分享过我..."
:category: [[tweets]]
:url: https://twitter.com/MetaHunter168/status/1685016863070380044
:image-url: https://pbs.twimg.com/profile_images/1452926589495173127/_BdMNLsz.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-20]]
** 📌
#+BEGIN_QUOTE
《套利的五大模型揭秘》（上篇）

之前有分享过我在web3的投资逻辑，基本只做高赔率和确定性的机会，在保障胜率的情况下如何拓宽手牌范围，在不确定性的市场中又如何寻找到确定性，这是值得长期去思考的事情。

1/n
一、套利的必备技能
套利板块是属于兵家必争之地了，常说的投研-技术-资金-人力四个维度上，无论是defi、nft还是gamefi市场的套利主要用到的是投研和技术这两个维度，在套利方面对这两把武器的要求都比平时撸毛的难度要高很多。

2/n
经常研究套利的朋友应该知道一个市场是否值得套利主要关注的指标是交易量和交易频率，只有这两个指标达标了，才有研究的意义。当然如果一个交易市场符合发展趋势，也可以提前研究，比如brc20，今天我尽量用人话把nft市场的五大套利模型来拆解清楚。

3/n
二、套利的五大模型
1.blur捡漏策略
背景:在过去的大半年里很多人都在刷blur的积分，但经常发现有人挂错价，比如小数点输错、数量和价格输反等等，这时候就会出现套利机会，别人的犯错就是我们的机会。
套利策略:这个套利策略需要手里持有现货，一般会挑选两类标的，一是排名靠前的蓝筹，二是新上线的nft，因为这两种都意味着交易量和交易频率足够大且一定时间内可持续。

4/n
举例1:用图1来举例，当时猴地的地板价为1.76E，这个地址想要去bid出价1.74E，结果手滑输入成了17.4E（且数量输入了四五个，这得刷多少分才能回本啊），一旦提交后就没机会再撤单了，这时候就看谁的机器人更智能，能花最少的gas，0区块抢来这单了。这里有一个问题，如果拉高gas抢跑失败是不是套利失败反而还亏gas了？

5/n
一般抢购的方式有三种，正常拉gas、mev或flashbots，mev和flashbots都可以利用以太坊的原子性来做到如果这笔套利失败，交易可以回滚，全当这笔交易没有发生过，这样形成了一个天然的反脆弱模型，抢不到不扣gas，抢到了才扣。

6/n
举例2：图2里RENGA这个nft,当时的地板价为1.14E，这个人出价直接bid了20E，我还特地去看了他的推特，这个老外blur发币时获得了5.5W枚blur，可能只够弥补这一笔他bid错价格的损失。这里想说一下，其实blur刷分没那么容易，这里的坑千千万，无论是之前bid到被做局的项目、bid错价格，被机器人砸、等等太多的坑，尤其是二期的坑再次升级了，你自己多地址刷刷交易量，项目方都会直接给你骷髅头。
7/n
2.blur/opensea的差价套利
背景:当一个市场出现多家交易平台时，就会出现同一标的不同平台有差价的情况，nft平台的前五名都可以自由组合去研究这里的差价机会，这里需要把他们的机制都研究透。

8/n
套利策略:
这个策略不需要持有现货，但需要监听全平台的nft实时价格变化，比如把程序设置个公式opensea/blur-版税-gas＞1，理论上过滤出的nft就可以从os买入，blur卖出，这里blur卖出nft有一个一小时的冷冻期，新买入的nft一小时后才可以卖，需要承担这一小时的波动，所以可以把公式稍微调的保守一点，比如＞1.03以上的时候再买入，这和交易一样，看的是总体盈亏，不能看单笔，只要整体胜率高就可以。

9/n
举例:以下两张图就是这个套利模型的实践，为了方便公式的动态调整，我们之前也开发了前端中控台方便实时管理，如果去年blur的一期交易激励积分的时候用这个策略，会赚的盆满钵满。当前的nft市场比较低迷，我相信当市场再次爆发或有新叙事时，这些套利模型就可以继续派上用场。

10/n
总结：以上分享的套利策略是随着市场动态变化的，不一定所有策略都一直有效，我更多希望的是把背后的思考逻辑给大家讲清楚。觉得有价值的朋友可以点赞转发，下周会更新另外三个套利策略，以后也会经常分享套利与技术相关的文章。 
#+END_QUOTE
    date:: [[2023-07-29]]
*** from _《套利的五大模型揭秘》（上篇） 之前有分享过我..._ by @MetaHunter168 on Twitter
*** [[https://twitter.com/MetaHunter168/status/1685016863070380044][View Tweet]]