:PROPERTIES:
:title: readwise/08 | 投资应该集中还是分散？
:END:

:PROPERTIES:
:author: [[youzhiyouxing.cn]]
:full-title: "08 | 投资应该集中还是分散？"
:category: [[articles]]
:url: https://youzhiyouxing.cn/n/materials/189
:image-url: https://readwise-assets.s3.amazonaws.com/static/images/article4.6bc1851654a0.png
:END:

* Highlights first synced by [[Readwise]] [[2023-12-18]]
** 📌
#+BEGIN_QUOTE
比如我们都知道的股神巴菲特，一向是持仓非常集中，几千亿美元的资金可能就投在十来个公司上面。很多专业投资者，比如中国的高毅资产、景林资产，走的也是深度研究后重仓少数公司的打法。还有一种「重仓」也很有趣，很多普通中国家庭的超过 70%、80% 的资产，都在一间房子上面，这其实也是一种变相的「重仓」，很多人也因为这种「集中」积累了很多财富。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrxtn42m6dst48bc63dqx49)
** 📌
#+BEGIN_QUOTE
相反，不少知名的投资人，是靠很大程度的分散持仓获得大量收益的。最经典的一个例子应该是彼得·林奇。在担任富达麦哲伦基金经理的 13 年期间，他获得了年化 29% 的回报。不过的他的投资风格并不是集中持股，在《战胜华尔街》等几本著作里他都提到过，自己的投资组合经常是有几百只股票同时存在的。但是，超常的勤奋让他对非常多的公司都有着超出市场平均水平的认知，所以也成就了麦哲伦基金当年的神话。

所以，既然集中和分散都可以成功，那么我们应该怎么选呢？

答案也很简单，我们把刚才的问题补上一个主语，问题就清晰了——*投资的时候，「你」更适合集中还是分散呢？这才是真正需要思考的事情。* 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrxva1hdd7t1g6zn5ya6v6x)
** 📌
#+BEGIN_QUOTE
站在 2020 年末，这家公司市值千亿，现金流稳健，全球已经有超过三万家门店。从 1992 年上市算起，星巴克的股价上涨了三百多倍，年化回报率接近 23%。

但就是这样一个家喻户晓的公司，如果你回看历史，有大量的时间，它的股价不是在下跌，就是在小幅震荡。

从 2015 末到 2018 年下半年，公司股价都在四五十美元这个区间波动；

再往前的话，其实从 1997 到 2004 年，星巴克股价都算不上有什么大起色；

2005～2007 年倒是涨上去了，但随之 2008～2009 的金融危机又被打回原形。

在这期间，假设你真的重仓了这个公司，其中的煎熬是可想而知的。

类似的例子还有很多，我们就不一一列举了。

总体来说，重仓或者集中的难度有三个：

*第一，在价格表现低迷的时候，你是不是还能在至暗时刻坚持自己的「信仰」；*

*第二，在其他股票其他资产表现出色的时候，你是不是能耐得住寂寞；*

*第三，在价格开始回归价值，你的判断的确兑现了的时候，是不是能选择好卖出的时机。*

如果你 15 美元买了星巴克，后来跌到 5、6 块钱没有卖，那么到了 30 美元的时候你会不会卖掉呢？如果卖掉，后面 30 美元涨到 100 美元这段利润就和你彻底无关了。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrxwmk1ef924zjna7xr4dws)
** 📌
#+BEGIN_QUOTE
*除了资产层面的分散，我们还要做到行业层面的分散。*一个典型的例子，就是投资了很多餐饮公司，但疫情来了全部损失惨重。另外，上一讲我们也说过「行业风格轮动」的现象，如果投资的行业过于集中，可能就会在轮动来临时经受更大的考验。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrxy392svw4z1tw9x2ybs4y)
** 📌
#+BEGIN_QUOTE
投资中的「本土偏见」

*除了行业风险，另外一个很常见的风险，是地理风险。*比如投资界里有个概念叫做「Home bias」，翻译过来就是「本土偏见」，指的就是投资者更倾向于把钱投资在本土，而不是全球市场的现象。

「本土偏见」是一个全球性的普遍现象。比如我们之前研究过加拿大普通投资者的数据，他们的股票部分，有 70% 左右都投给了本土市场。但实际上加拿大股票总市值占全球股市还不到 3% 。显然，加拿大「散户」超配了自己国家的股票，而如果加拿大的股市表现不佳，或者邻国美国的股市涨势更好的话，这些人就错失了赚钱的机会。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grrxyxh8c2embnb3nzahergg)
** 📌
#+BEGIN_QUOTE
举个身边的例子。我有一个高净值客户的朋友，在他的眼中，世界充满了风险，所以他在力所能及的范围内，做到了最大程度的分散。比如他是不少基金的 LP（背后出资人），虽然他是一个价值投资的信徒，但他投资的基金，有价值风格、有动量风格、有绝对收益风格、也有量化套利风格——因为「你也不知道某个三年五年里哪个策略能跑出来」。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grry03j76c4g3q2sxxbf28h8)
** 📌
#+BEGIN_QUOTE
庞大的现金流让伯克希尔只能重仓甚至直接收购部分巨头公司，其仓位却分布在了相关性较低的几大板块，多达 46 家优秀的企业上。同时另一面，由于伯克希尔已经拥有了不断产生浮存金的保险公司、净资产不断增长的能源霸主、现金流永续增长的消费和金融巨子，并拥有良好的信誉和随时大笔举债的能力，所以它并不需要像普通人或者机构一样去配置债券等收益更低的类现金资产来拼凑一个资产配置组合（事实上它已经拥有更好的）。 「持有一大笔现金，坐等一场金融危机」是巴菲特投资风格的形容，这里的「一大笔现金」，我会理解它就是分散配置中的另一种品种。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grry1w56egs6tns4chnqewxq)
** 📌
#+BEGIN_QUOTE
分散的概念我们更容易理解，从最简单的 55 股债平衡模型，到 5-6 支品种的极简组合，再到大部分朋友跟车的集合大中小盘、行业指数、海外公司、黄金石油等丰富种类资产的长赢计划，都是分散的资产配置，也相对更适合普通的投资人。 潇雨老师的个人投资课曾经讲过：资产配置更多解决的是收益的波动幅度，而不是收益本身；资产组合的收益主要由组合中的大类资产的长期表现来决定；在构建适合自己的分散组合的同时，低成本、长期持有和不懂不动这些原则同样需要谨记。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grry2mf7h1tzteq2jkc9rqzq)
** 📌
#+BEGIN_QUOTE
今年开始学习理财，跟了一些大v也有自己瞎买的，在逐渐学习的过程中完善我的资产配置，总结参考e大的统计类别，我的配置股票占比73% 债券占比27%。股票分为a股占比66.4% 海外占比6.5%。a股又分别为 主动基金27.5%、行业基金16.7%、大盘9.4%、中小盘6.26%、价值6%。我觉得达到了分散且均衡的效果。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grry43jkkrn05qkr7haxq1dg)
** 📌
#+BEGIN_QUOTE
同时也意识到自己在债券方面的薄弱，本以为债券是一个很好的平滑波动的工具，其实债券也是有投资时机的，而对于今年上半年的行情来说，其实只投股票基金就可以了，下半年才是加债券的机会。希望未来自己的心态能够提升，能够逐渐容忍更高的波动率。 
#+END_QUOTE
    date:: [[2023-02-09]]
*** from _08 | 投资应该集中还是分散？_ by youzhiyouxing.cn
*** [View Highlight](https://read.readwise.io/read/01grry4vdm2r0dna9ec7dm2qxq)