:PROPERTIES:
:title: readwise/Adam d'Angelo 如何通过 POE 将...
:END:


* metadata
:PROPERTIES:
:author: [[dotey on Twitter]]
:full-title: "Adam d'Angelo 如何通过 POE 将..."
:category: [[tweets]]
:url: https://twitter.com/dotey/status/1771712077507313896
:image-url: https://pbs.twimg.com/profile_images/561086911561736192/6_g58vEs.jpeg
:END:

* Highlights first synced by [[Readwise]] [[2024-04-08]]
** 📌 [[2024-03-24]]
#+BEGIN_QUOTE
Adam D'Angelo 如何通过 POE 将 AI 带给大众

前言

本文是对 Quora CEO Adam D'Angelo 的一段视频采访文稿的整理。在采访中，Adam 分享了他对 AI 发展的看法，以及如何通过 POE 平台将 AI 带给大众。以下是对话内容的整理。

社交网络作为 AI 的补充

Adam: 我在职业生涯早期就对 AI 非常感兴趣，那时的技术还不够成熟。与此同时，社交网络开始蓬勃发展。社交网络技术可以看作是 AI 的一种替代，通过互联网将人们连接起来，让他们完成各种任务。考虑到当时 AI 还未完全准备好，社交网络就成为了应用技术的主要领域。

POE: 将 AI 带给大众

Sarah: 能否为我们解释一下 POE 是怎么工作的？你是怎么发现它的？你又是怎么与它互动的？

Adam: POE 可以成为人们接触 AI 的一个渠道，让他们能够接触到来自各种公司和研发者的 AI 产品。你可以在 POE 上与各种可用的模型进行交流，我们还有许多人基于这些模型开发的其他产品。我们提供一个开放的 API，任何人都可以接入。

AI 的未来是多模型和多模态的

David: 一种理论认为只需要一个模型就能为每个人提供所需的全部解决方案。另一种理论认为未来会有大量不同的模型用于不同的应用场景。POE 的理念就是相信未来是多元化的，你为什么这样认为？

Adam: 我认为在创建这些模型时涉及许多权衡，你需要决定用什么数据进行训练，要进行怎样的微调，模型期望用户给出怎样的指令，以及你对用户使用模型的预期设定。正如早期互联网产生了各种各样的应用，我们也会看到 AI 有相同的趋势。POE 可以成为一个统一的接口，让人们与任何模型进行交流。

模型是产品吗？

David: 许多人可能会说 AI 模型在很大程度上就是产品。你预见将会有哪些突破，会改变人们与这些产品互动的方式，从而推动新类型产品的创建？

Adam: 如果你想让模型服务全球消费者，你需要开发各种应用，处理各国的计费和税务问题，其中的工作量是巨大的。对许多公司来说，建立 API 或接入 POE，以此快速触达消费者可能是更好的选择。

为创作者构建 AI 基础设施

David: 在 POE 上，创作者已经构建了一些什么有趣和创新的东西？

Adam: 目前很多人对图像模型如 Stable Diffusion, SDXL 等感兴趣。还有一家名为 Playground 的公司在 POE 上提供了一个强大的图像编辑模型。能让这些长尾创作者有机会创作自己独特风格的模型真的很酷。提供基础设施和支持，让用户和创作者做他们擅长的事，是一个好方法。

应对平台转变

David: 你在 Facebook 担任 CTO 时正值社交媒体兴起和平台向移动端转移，你对这次转变和当前的 AI 浪潮有何看法？

Adam: 当平台结构发生重大变化时，你需要重新思考很多事情，这需要非常强的领导力。这次我们更早识别出了 AI 的趋势，提前开始进行实验性操作。从中我们获得了信心，意识到 Quora 核心产品过于围绕出版模型构建。而 AI 和大语言模型则不受时间限制。因此我们决定创建 POE 这个全新的以聊天为主的产品。

分享人类和计算机生成的知识

Adam: 我们希望 POE 和 Quora 能整合在一起，把 Quora 的人性化元素更多地融入 POE，也把全部核心数据集融入 POE 的机器人中。随着模型不断进步，我们已经开始让 POE 的 AI 生成 Quora 上的答案。Quora 的模式会更适应 AI。无论是 Quora 还是 POE，都是你可以获取答案的地方，有时答案来自人类专家，有时则来自 AI。

互联网上的知识分享

David: 关于互联网的发展，你有何看法？人们会与具有不同特性和专业领域的 AI 机器人互动，其中穿插着真人吗？

Adam: 我认为人类始终会在某些方面发挥作用。有些知识并不在网络上，没有一个大语言模型能拥有那样的知识。我预计会出现这样一种产品或用户体验，其中大语言模型会帮助你整理信息来源，并确切引述专家或原始出处，而不只是综合所有信息，给你一些无法确切知道来源的信息。

规模化对 AI 的益处

David: 在大语言模型的 AI 领域，你还对哪些重大进步感到兴奋？

Adam: 我个人最期待的就是规模的扩大。我的预测是，尽管需要克服一些问题，但现在有如此多有才华的人在推进这项技术，而且有大量资金支持。我相信我们将继续见证指数级的进步，这将持续很多年。

在规模或特性差异化上竞争

David: 为了训练前沿模型，你需要数十亿美元和多年时间，这导致只有少数玩家能处于前沿。那么生成式 AI 市场的最终结构会是怎样的？

Adam: 我认为，如果你落后最前沿半年甚至更长，那将非常糟糕。要么你通过保持在最前沿进行规模竞争，要么通过特性差异化进行竞争。在后一种情况下，你可能并不需要最前沿的模型，而是将某种特殊元素与模型结合。你或许可以运用 OpenAI API 再结合你提供的某种独特工具，这样也能成就一门很好的生意。

错误容忍度成为创业公司的契机

David: 最后我想问，你对那些想在 AI 领域创业的人有什么建议？

Adam: 如果我现在开始新的创业，我会花大量时间熟悉模型，尝试把它们与各种东西结合。你可以给模型提供很多不同的输入，人们的需求范围非常广。不断尝试是找寻新想法和建立一个能创造真正价值的初创公司的最好方式。

此外，那些深入人心的大公司可能有非常强大的品牌，从不犯错误。而一个创业公司可以说，虽然这可能只需十分之一或百分之一的价格，但有一定概率会出错。实际上很多人更喜欢这样。但对已经做大的公司来说，这是个问题，因为他们不能损害品牌形象。错误容忍度可以成为创业公司的一个契机。

原始视频：https://t.co/parBFSZrSc<video controls><source src="https://video.twimg.com/amplify_video/1771711343373991936/pl/iXaiVnobcc-Fdjpt.m3u8?tag=14&container=cmaf" type="application/x-mpegURL"><source src="https://video.twimg.com/amplify_video/1771711343373991936/vid/avc1/480x270/KDde4UohRJyd0hK2.mp4?tag=14" type="video/mp4"><source src="https://video.twimg.com/amplify_video/1771711343373991936/vid/avc1/640x360/7lPjJjatfB67JHBY.mp4?tag=14" type="video/mp4"><source src="https://video.twimg.com/amplify_video/1771711343373991936/vid/avc1/1280x720/2d6r_T6vknW_986A.mp4?tag=14" type="video/mp4">Your browser does not support the video tag.</video> 
#+END_QUOTE\