:PROPERTIES:
:title: readwise/趁着新年，我最近表达欲爆棚，就嘴毒把不那么开心的...
:END:


* metadata
:PROPERTIES:
:author: [[DoraraCatPaw on Twitter]]
:full-title: "趁着新年，我最近表达欲爆棚，就嘴毒把不那么开心的..."
:category: [[tweets]]
:url: https://twitter.com/DoraraCatPaw/status/1754732191114993724
:image-url: https://pbs.twimg.com/profile_images/1324636185394774016/UjgcK8IJ.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-02-06]]
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
趁着新年，我最近表达欲爆棚，就嘴毒把不那么开心的话都说完了，过年才干净祥和，新的一年好好生活，向自己希望的生活进发，与世界上每一个平凡的自己共勉。 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
我从六七年前过来，疫情几年或许是因为被物理意义困在了坡，让我从之前学校专业一流，环境整洁干净的表象下更进一步地在理解这个花园城邦的内核以及对于自身发展的思考。 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
实话讲，现在坡给我的观感就是一个广义的洗钱中心……不只是字面上意义的洗钱，还帮两地都不方便的大陆爱国华侨洗身份，洗企业，洗数据安全，洗显卡。它确实受益于这两年两极化的一个趋势以及HK受到的冲击，自己也擅长于营造一种烈火烹油的繁华景象， 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
很多同胞接触很多的公众号对坡的宣传又给人一种“来坡人人有工作，人人有affordable的房屋，可以安居乐业”的愿景。但是他们却都有意无意忽略了一个事实，这个愿景是需要加限定词的，那就是前提你要是“本地人”才可以实现这一切，本身我对坡高度本土保护自己国民没意见，还略羡慕。 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
但是，很多时候大家都是等登陆了才发现，哇…这行限定小字我没注意。那么后疫情时代面临的是什么情况呢？ 非本地人语境下，你的工签居留与公司深度绑定，本身职场细分赛道在这儿的晋升跳槽就不明朗，US/EU对应的大IT公司名头都很大但是招的技术高级职位从来不多，常见于前端，安卓，或者极少数后端 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
相对本土的小创业公司，有过工作经验的都不倾向于进去花简历，而疫情前后上升势头本身很猛的shopee,grab,foodpanda这几家疫情后各方面因素也是基本没有那个继续高歌猛进的势头了。另一部分咱们近两年听到的很多出海的中资呢？他们在来的时候一个主要目的就是中高管过来解决移民税收财产安置， 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
这就导致中资在2021-2022发了大量EP 给自己人且你能预计到的高职级hc基本职场位置都已经卡死，本地很喜欢跳槽加薪，如果你想平跳，自己的方向又不愿意太过妥协那么你会发现同行业能让你跳来跳去的公司掰着指头数也就3-5家还大概率没有EP 名额 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
另一方面上述出来的部分中高层或者高级净值人士可能很多在国内是已经有资产或者可以置换部分国内一线房产来这儿配置住所。然后加上疫情时间坡全面建筑停工，直接导致的观感就是房租暴涨 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
那么假设是EP月入1w sgd附近，普遍情况就是你需要花20%的薪水在住宿上而且很可能还只是一个小小的单间不是小套～需要时刻警惕房东会不会给自己找茬从克扣押金到逼你提租等不一而足，因为本地就是非常倾斜房东而非租客，供需失衡情况下就更是了（小额法庭可以上，但赢不了，就拿回来200-300吧） 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
同时说吃，这个节奏的打工人基本不用想自己天天煮，那么想吃非常一般的杂菜饭大概5新一顿（那个基本都是些冻品鱼丸鱼饼预制鸡块油炸，蒸蛋，配上点炒青菜，或者卤菜豆干），如果想吃点沙县小吃面啊炒饭麻辣烫之类的小吃算小馆子吧～大概10-20sgd。那如果周末想下馆子呢？现在的价格加上9%税和10%服务费 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
基本一顿下来俩人也就80-100上下了。外加行，大部分跟我一样的单身人口其实都是公共交通，一个月接近80刀。那么算算…如果无法接受苦行僧的生活，一个月这样的群租房+地摊饮食+偶尔消费。差不多就会花掉你的一半薪水……这个比例高吗？我相信对于很多超高薪过来的大佬，这点钱比起省下的个税洒洒水， 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
但是对于你我这样平凡的个体，这样的生活又值吗？我觉得自己不值。这一切都还是在你没有任何烧钱的爱好的基础上…如果你爱好就散步逛公园那可以，但是如果我还想有点别的爱好呢？不是说每年两三次每次四五天到东南亚国家感受一下新币带来的超级购买力和疯狂发泄就完了。生活是一种持续的体验 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
另外说移民……诚然这两年会发现IT 很容易PR，登陆两三年就拿到的比比皆是。但是在批的时候坡政府就已经想好了你的salary cap定下，等你远超了才批，那你是不会威胁到它的bto祖屋福利系统的，除开能拿PR这个单一身份 ，真正的私宅市场那个收入比，也不好说比HK 和大陆超一线房价好到哪里 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
且同期批的都是差不多的移民……以后到买房生育上学每一个坎仍然是无止境的同质化竞争，都不提现在职场上还多了很多“大陆卷不过，来坡卷你”的天纵英才，以及国内一线小升初太卷，来这鸡娃 a level的虎爸虎妈。 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
再说难听一点……祖屋是便宜，但是限定词是对本地人便宜，你来这儿打工个税是低，但是其他这些刚性开支，职业限制，租房倾斜政策，曾几何时真的不是一种针对你的隐性税收吗？ 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
从很早就来坡的我一开始真的挺开心的也挺知足的，我是真的相信的新加坡政府说的“融入当地，建设家园”，我去义务教编程，认真做科研，追求自己的学术理想～但是或许疫情发酵和加速了这一系列的过程，我从一开始坚持自己，到互联网实在不行打不过就加入卷 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
再到观察到sg表面说的融入考察etc,实际仍然是“金钱永不眠”那套看钱看资产看条件的一个博弈游戏……我确实感觉累了，也确实对这里的近几年来的技术发展状态和技术投机心态深深失望，或许失望最深的，是那个曾经眼里有光对技术充满执着追求对这个城邦充满归属感的自己😞。 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
我深深地反省轻信且存有侥幸的自己，深深地对过去那个努力但是不成熟的自己感到抱歉。新的一年我会继续充满野心充满斗志向前努力，不过这次我会靠自己，向着自己理想的生活去前进，去经营。希望今年或许明年，我可以有足够的实力和运气，离开这里 🕒 
#+END_QUOTE\
** 📌 [[2024-02-06]]
#+BEGIN_QUOTE
这个po有我很强的个人负面情绪在里面，同时也有职业年龄各方面的主观限定。喜欢坡的和来这儿时机不错过的很舒服的也都有也不少～小红书很多这样的同温层，如果你想分享幸福喜悦，可以去那儿抱团交流，建议尽量不要在这秀或者跟我说3k sgd完全够一家人美美过一个月etc，我会很烦，提前谢过。 
#+END_QUOTE\