:PROPERTIES:
:title: readwise/昨天晚上看了《奥本海默》，电影总体不错。但是有点...
:END:

:PROPERTIES:
:author: [[mtrainier2020 on Twitter]]
:full-title: "昨天晚上看了《奥本海默》，电影总体不错。但是有点..."
:category: [[tweets]]
:url: https://twitter.com/mtrainier2020/status/1683331397820506113
:image-url: https://pbs.twimg.com/profile_images/1653584496460197889/7cJQMLho.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-18]]
** 📌
#+BEGIN_QUOTE
昨天晚上看了《奥本海默》，电影总体不错。但是有点简单化那段时间的历史与事实了，尤其是后半段。
1. 苏联的间谍网一直有效渗透着阿拉莫斯国家实验室。
2. 苏联一直掌握着美国核武器的研究进展。甚至比杜鲁门知道的还早。
3. 苏联的间谍网，为苏联节省了至少10-20年的时间，以及大量的科研经费。而且造成了后来的各种核扩散。
基本的路径就是，苏联-->中国-->巴基斯坦-->朝鲜，伊朗，等等国家。
4. 冷战的起点就是苏联间谍网的暴露。

这段历史，中文社区基本上很少有人梳理。一切的起点就是著名的古琴科事件。

Gouzenko Affair
1943年起在渥太华的苏联驻加拿大使馆工作。1945年9月5日他带着密码本和109份关于苏联在西方谍报活动的文件叛逃到加拿大皇家骑警队。这迫使加拿大组建了皇家谍报活动调查委员会。逮捕了39名间谍嫌疑人，其中18人被法庭定罪，包括加拿大共产党唯一的国会议员。

要是苏联没有间谍门的帮助，甚至都不知道原子弹的原理，不知道用铀做的。这些扫盲的科普工作是，艾伦·纳恩·梅（ Alan Nunn May）做的。这位Alan是由古琴科的文件第一个被抓出来的间谍。后来这个Alan被判了十年。但是Alan 只是小喽罗，不能接触到核心机密。那苏联肯定还有其他的卧底。
美国通过分析电报，在1949年才发现了蛛丝马迹，发现了真正的大鱼：真正给苏联带来top secret的间谍是，英国人Klaus Fuchs。这个人的故事也可以讲非常多，不过他是属于无间道。。。他是德国人，逃难去了英国，然后因为专业领域的能力又被调去了美国，结果他内底是苏联特工。这个人基本上把曼哈顿计划和盘托出给了苏联。

美国顺藤摸瓜，找到了，Fuchs的交通员，美国化学家哈利·戈尔德（Harry Gold）。而Gold的上线就是苏联驻纽约副领事雅科夫列夫。

FBI在搜查Gold家里的时候，发现Gold在阿拉莫斯除了Fuchs外还有一个下线。
FBI那就开始审讯。
Gold在候审期间，说，除了与Fuchs联系外，还曾奉命与一位美国士兵联系，和他一起去取洛斯阿拉莫斯工程的原子能资料。这个士兵25岁，他不知道名字，只有一些外形描述：非常健壮，身高5英尺7英寸，长着黑头发。
根据这个线索，FBI开列了一个20人名单，又让Gold分别从照片上指认，戈尔德挑出了一张。此人叫戴维•格林格拉斯，他同他的姐夫朱利叶斯•罗森堡一起，在布鲁克林工程公司干活。
罗森堡夫妇终于浮出了水面。
而原子弹工程中最关键的部分，内引爆装置模型草图以及一些情报都是由戴维和罗森堡夫妇传递给苏联的。（在电影中奥本海默他们不停尝试的就是内引爆装置的设计和调整）。罗森堡夫妇是少数被直接电椅处决的间谍。
整个苏联在曼哈顿计划中的间谍网，远比这个还要大。有的最近几年才曝光。

Theodore Hall， 美国人，是洛斯阿拉莫斯最年轻的物理学家。他向苏联情报部门详细描述了“胖子”钚弹以及提纯钚的几种工艺。之后他移居英国。直到20世纪末，他的间谍身份才被揭露。尽管他后来向记者和家人承认了这一点，但他从未因间谍活动而受到审判
George Koval是美国出生的白俄罗斯移民家庭 的儿子，后来回到苏联加入了格鲁乌。他以代号德尔玛的身份从橡树岭国家实验室和代顿项目获得了有关胖子身上使用的海胆雷管的信息钚弹。2007年因为普金追授他俄罗斯联邦英雄”才暴露身份。
Oscar Seborer  负责核试验地震效应分析部门—1951年叛逃苏联，并获得红星勋章。他化名“史密斯”，于 2015 年去世。他的身份直到 2019 年才被公开披露。

因为美国原子弹机密被盗，美国启动了联邦忠诚调查委员会，调查美国内部的威胁。如果结合有些国家的技术来源，几十年后回过头来看，美国的紧张与愤怒并不是没有由来的。奥本海默这部电影完全没有展现当时的大环境。

在新的时代中，苏联已经消亡了，俄罗斯的情报网基本上完蛋了，要理想没理想，要钱没钱，要认同没认同。而新苏联有几乎不限量的资金，有民族主义意识形态的的召唤。而美国似乎还没有准备好。 
#+END_QUOTE
    date:: [[2023-07-24]]
*** from _昨天晚上看了《奥本海默》，电影总体不错。但是有点..._ by @mtrainier2020 on Twitter
*** [View Tweet](https://twitter.com/mtrainier2020/status/1683331397820506113)