:PROPERTIES:
:title: readwise/\#程序员 \#养生 我个人脱发严重，最近一个月在喝...
:END:


* metadata
:PROPERTIES:
:author: [[lencx_ on Twitter]]
:full-title: "\#程序员 \#养生 我个人脱发严重，最近一个月在喝..."
:category: [[tweets]]
:url: https://twitter.com/lencx_/status/1711298689921343787
:image-url: https://pbs.twimg.com/profile_images/1085701406470750208/iG_bM0AH.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
#程序员 #养生 我个人脱发严重，最近一个月在喝“维生素 d3 10000iu + omega-3 鱼油”（进口，具体牌子不推荐，避免广告嫌疑）。明显感觉落发少了，头皮也隐隐看到很多细小头发在生长。目前时间还太短，很难说是否真正有效。比较焦虑的朋友可以试试，应该会有改善。

理论支持：柏格醫生 Dr Berg 的视频 
#+END_QUOTE\
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
没想到这条帖子会这么多人关注，我并不是这方面专家，只是恰巧之前刷到柏格醫生讲脱发的视频。就尝试了这两个，对我来说似乎有所缓解。

柏格醫生有好多期关于头发的视频，推荐的食物、药物都不一样，大家可以自行决定。

评论区有说他带货神棍啥的，我并不清楚，如果有医学大佬出来说几句就更好了。 
#+END_QUOTE\
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
关于 10000iu 的问题，这个貌似争议很大。我也看过很多相关信息，说啥的都有。有说一天 2 万 iu 也没事的，也有说每天只需几百 iu 即可的。

这些都不是我擅长的，只能说大家谨慎一点吧。也希望大家多看看评论区，避免踩坑。 
#+END_QUOTE\
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
我也觉得不一定是药物起了作用，一个人的生活作息，心情状态都会对人体产生巨大影响，比如心情愉悦可以增强抵抗力。

在这里聊这个话题，其实会发现，很多说有效果的，可能都是补充了一些维生素族群，微量元素等。所以有部分人可能真的是缺这些才导致了一些身体问题... 
#+END_QUOTE\
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
🚨 评论区提供了一个重要信息，补充 d3 的同时需要补充 k2，原因：
维生素 D3 帮助身体吸收钙，促进健康的骨骼和支持免疫系统。维生素 K2 指导钙进入正确的位置（如骨骼），并防止其沉积在不应该的地方（如动脉）。两者一起使用可以确保钙的有效吸收和正确利用，支持骨骼和心血管健康。 
#+END_QUOTE\
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
再补充一点，维生素摄入过量也会适得其反，大家不要盲目尝试。这个话题越聊越深了，已经远远超出了我的认知。

最后建议：是药三分毒，不能乱吃！ 
#+END_QUOTE\
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
继续补充，掉发和洗头频繁也有很大关系，包括用的洗发水牌子。我近期都是几天洗一次，清水洗头。长时间不洗也不好，可能会造成毛囊堵塞。

就说这么多吧，这个话题已经不是我能掌控的了。都怪我，就不该发这个帖子，本来是好心，但现在可能又让一部分人焦虑了。 
#+END_QUOTE\
** 📌 [[2023-10-10]]
#+BEGIN_QUOTE
评论区总结：如果缺乏维生素，微量元素，千万不要瞎补，它们之间存在依赖关系，一旦打破平衡会得不偿失。最好去正规医院测一下各项指标，谨遵医嘱。命是自己的，请对自己负责！

感谢大家的评论，帖子并不具有指导意义。我可能没回复，但都有在看。后面的评论就不整理了，感兴趣的朋友自行翻阅。 
#+END_QUOTE\