:PROPERTIES:
:title: readwise/07｜职业方向：如何选择一个有前景的职业方向？
:END:


* metadata
:PROPERTIES:
:author: [[geekbang.org]]
:full-title: "07｜职业方向：如何选择一个有前景的职业方向？"
:category: [[articles]]
:url: https://time.geekbang.org/column/article/399771
:tags:[[gt/程序员的个人财富课]],
:image-url: https://static001.geekbang.org/resource/image/3f/e4/3fa7f0d597856cb0d99d4bfd56be97e4.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-20]]
** 📌
#+BEGIN_QUOTE
一个职业方向好不好，可以从两个维度来判断：从长期来说，要看它的“高度”和“容量”；从短期来说，要看它的“供需关系”。 
#+END_QUOTE
    date:: [[2023-04-09]]
*** from _07｜职业方向：如何选择一个有前景的职业方向？_ by geekbang.org
*** [[https://read.readwise.io/read/01gxjck0bvzfctb8new3g1e129][View Highlight]]
** 📌
#+BEGIN_QUOTE
总之，一个好的职业方向，一定是高度很高，容量很大且稳定的方向。 
#+END_QUOTE
    date:: [[2023-04-09]]
*** from _07｜职业方向：如何选择一个有前景的职业方向？_ by geekbang.org
*** [[https://read.readwise.io/read/01gxjckwkbdjp3485tjbz6dyas][View Highlight]]
** 📌
#+BEGIN_QUOTE
如果这时你已经有了转换方向的想法，可能还想问我：在转方向的过程中，我到底要具体做些什么呢？我觉得可以分为三大步骤。

第一，下决心。按照我们刚才说的原则，从“短期”和“长期”两个维度，确定你未来希望从事的方向。

这里我要强调的是，你的决定一定要建立在充分的分析决策之上；而且，一旦做出这个决定，就不要轻易改变。你要清楚，开弓没有回头箭，在接下来至少一年的准备时间里，不要做任何的摇摆，所有的工作、学习行为都要围绕着转方向这个目标。

第二，定目标。在确定自己的目标方向后，至少提前一年去看目标职位的 JD（Job Description），列清我们的具体目标。你需要进行细致的规划，包括需要掌握的工具，需要了解的领域知识，需要准备的面试题等等。然后根据这些具体目标，有的放矢地去扫清转方向过程中的障碍。

第三，攒经验。你当前的工作、学习行为，都应该围绕着新的目标进行调整。比如你现在从事后端岗位，想转到推荐算法岗，那么可以看看现在公司内部有没有推荐系统相关的后端岗位，先跳到相关方向上来。再比如你是一名应届生，想从数学方向转到软件工程师方向，那么就应该马上着手去积攒项目经验，寻找相关的实习岗位。总之，要千方百计地向你的目标岗位靠近。 
#+END_QUOTE
    date:: [[2023-04-09]]
*** from _07｜职业方向：如何选择一个有前景的职业方向？_ by geekbang.org
*** [[https://read.readwise.io/read/01gxjcsq3e9x0ax2g6awyvjbxe][View Highlight]]
** 📌
#+BEGIN_QUOTE
在这一讲的最后，我就把今天的要点重新梳理一遍，帮助你建立严谨的职业方向选择逻辑。

有前景的职业方向有两个特点，一是高度高，二是容量大。

在具体找工作时，不仅要考虑长期发展，还要考虑短期供需关系的影响。

选择后的坚持才是影响你收入的第一要素，因此不建议在没有规划的情况下频繁跳槽。

只要满足这两个典型条件之一，就建议你转换职业方向：第一个是个人转方向的决心非常坚定，对自己非常有信心；第二个是当前职业方向进入了长期下行通道。

转换职业方向，具体可以分为三个步骤：第一步，下决心，开弓没有回头箭；第二步，定目标，提前一年查目标岗位的 JD，确立详细的目标；第三步，攒经验，千方百计地向你的目标岗位靠近。 
#+END_QUOTE
    date:: [[2023-04-09]]
*** from _07｜职业方向：如何选择一个有前景的职业方向？_ by geekbang.org
*** [[https://read.readwise.io/read/01gxjct5hg3rj5jcvr8bykvr3w][View Highlight]]
** 📌
#+BEGIN_QUOTE
分享下我的转方向的经验。 首先推荐看下混沌大学的第二曲线，里面提到两个切换到第二个增长赛道关键点。 一，十倍速变化。 二，击穿阈值。 当要出现新赛道的时候，一般都有一个10倍变化的变量，你一定能发现。我刚12年毕业是oracle dba，但当时注意到mysql的技术文章分享是其他数据库的10倍，评估mysql下一个关键点，主动去学mysql（选择）。 但是要从oracle切换到mysql还是很难的，因为当时mysql dba国内并不多，我自己也没实践，没人带，市面上没系统的课。所以我通读官方文档加阅读源码这条最苦的路子，击穿新赛道的阈值（坚持努力）。 十倍速的变化，大家一定要注意，这是行业变化的一个前置关键点。 击穿阈值，要说的就是只有达到阈值，你的努力才能量变质。 还有其他的一些原理，比如组织心态的束缚，讲的是为啥只有小公司能切换赛道。也许当时我刚毕业是个切换到mysql赛道的好前提，而那些当时的oracle专家基本都没切到mysql赛道。 还有个低端颠覆原理，讲的拼多多，美团如何崛起，也很有意思。我的体会是在运维开发时候，老系统只会越做越倾向高层和领导，比如花大量时间适配老板的pad这个需求，而对普通用户越来越不友好，流程bug甚至忽略，易用性越来越差，oncall只回答领导的提问等等诟病。这是你可提开发一些工具解决这些诟病，慢慢变为系统，最后替代老系统。 
#+END_QUOTE
    date:: [[2023-04-09]]
*** from _07｜职业方向：如何选择一个有前景的职业方向？_ by geekbang.org
*** [[https://read.readwise.io/read/01gxjcvhemm45sxtgbm307t768][View Highlight]]