:PROPERTIES:
:title: readwise/很多时候人们无法行动，都是自己的想法匹配不到自己...
:END:


* metadata
:PROPERTIES:
:author: [[Yangyixxxx on Twitter]]
:full-title: "很多时候人们无法行动，都是自己的想法匹配不到自己..."
:category: [[tweets]]
:url: https://twitter.com/Yangyixxxx/status/1748896933358530824
:image-url: https://pbs.twimg.com/profile_images/583101789483859969/soayV1UA.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-01-21]]
** 📌 [[2024-01-21]]
#+BEGIN_QUOTE
很多时候人们无法行动，都是自己的想法匹配不到自己的能力，心比天高命比纸薄。

没读过什么书，也没做过什么尝试，没怎么了解过用户，也没接触过各类行业，不了解产业生态和产业链结构，没看过不同的商业模式，没和成功过的人取过经，也没有太多对他人赚到钱，做对了哪些事情的观察。

每当遇到一个不确定的事情，就会开始犹豫和踌躇，觉得自己的时间应该投入到产出比更高的地方。但又识别不出来。

没有过任何刻意练习得到反馈，怎么可能光凭书本经验就能做到成功？很多时候就算让那些饱腹经纶有着大量方法论的成功者，换一个时间点再做一次，也不一定会成功。更别说光指望自己看两本书，听两天成功人士的电台，就奢望只要投入时间就能得到确定结果，把其他roi低的选项筛查掉。你不知道的是，相同的一个事情，用不同的模式去做，产出结果是截然不同的。

如果产出不确定，最好的行动方式是让成本变低。
1、找投入成本极低的方法快速试错，很多人总妄想自己去做，要知道你想做的事情大概率都被人做过。去找解决方案试错就好了，远比自己做要快
2、刻意练习，别人做两周你可以做两天。这种刻意练习建立在多看多做上，我曾经做产品设计需要1周，现在只需要1-2小时，只是因为看过的太多了，做的也多了

当成本变低后，行动就容易了：
1、只要你有兴趣，就可以去尝试，这些事情在未来人生的某个时刻会给予你巨大帮助
2、投入5天之内，就可以构建试错，那就去试，没必要思考

做的过程里，开始复盘，去理解如何获取用户促成交易，一方面自己尝试，一方面有了东西就会遇到更多资源，去开拓认知，在这个过程里逐渐就有了一些对于原有书本方法论的理解。

接下来面临的问题才是，每天100个想法，该选择哪个的问题。
这个时候自然会慢慢涌现出判断力。
因为刻意练习慢慢帮助你掌握了该如何判断人们的付费意愿，市场大小，项目风险，等等一系列的信息。你能看到的信息维度和深度都会增加，信息多了就容易获得更全面的判断。

不要好高骛远，自己拿个小茅枪，想跳跃阶段去打最终boss，凭什么？
这种情况能赢，只能凭你死过上千次后，形成的肌肉记忆，100%盾反。 
#+END_QUOTE\