:PROPERTIES:
:title: readwise/纠正下，Steph ango不是Obsidian...
:END:


* metadata
:PROPERTIES:
:author: [[vista8 on Twitter]]
:full-title: "纠正下，Steph ango不是Obsidian..."
:category: [[tweets]]
:url: https://twitter.com/vista8/status/1725161224390754574
:image-url: https://pbs.twimg.com/profile_images/28889602/20070314_b0295ade0c516903fd31D3r1hlye1a1Q.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-20]]
** 📌
#+BEGIN_QUOTE
纠正下，Steph ango不是Obsidian创始人，是现在的CEO， 读了他博客几篇内容，感觉非常有趣，翻译概要总结下：

关于痛苦
痛苦是不可避免的，但苦难可以选择。

选择把焦点放在痛苦本身，还是选择关注积极的反应与应对。痛苦是一种信息。

越早将痛苦转化为知识，就能越早体验下一个有用的痛苦。不要体验同样的痛，去体验新的。

每当痛苦时，想想它提供了什么信息。（像雷·达利奥说的 “ 痛苦+反思 = 进步 ”。）

关于独立软件
独立开发者做的高质量软件对比大厂的流水线App。
很像手工制作的有机果酱 vs 工业玉米糖浆做的果酱。

大厂拥有大量的用户，产品推广成本低，而且也有软件之外的赚钱手段，比如谷歌靠广告、苹果靠高利润硬件、微软靠商业服务。

这带来一个问题，大厂的软件可以免费或很便宜，但独立开发者不行，高质量的软件正大光明，果断收费，不要不好意思。

关于买东西
买东西时，尽量优先考虑每次使用成本。

有时候，也可以考微笑成本、刺激成本、外部性成本和“每课”成本。

使用成本：高质量耐用的产品，大大降低每次使用成本，看标价贵，但实际每次使用成本很低。
微笑成本：能让自己愉悦开心的产品，哪怕单次使用成本高，也可能是值得的。
刺激成本：能带来不一样刺激体验的消费，比如过山车、蹦极等，
外部性成本：比如出于环保信仰选择更贵的有机蔬菜，可能有助于改变社会对事物的价值观，或只是让你感觉良好。

关于个人风格

王尔德说“一致性是缺乏想象力的最后避难所”。

但steph ango认为“风格源于一致性，思维应该灵活，但流程应该可重复。”

一种风格可以是一个系统、一个模式、一套个人指南。

Steph ango的个人风格举例：
① 穿着没有商标的单色服装。
② 在任何地方都用YYYY-MM-DD日期格式。
③ 将标签和文件夹名称变为复数形式。
④ 每年问自己40个问题
⑤ 写简洁的文章，不超过500字。
...

请注意，风格并非一种终身承诺，只是你暂时做事情的方式而已。

他还列举了一些名人的风格：
① 韦斯·安德森在他的许多电影中都使用了Futura字体。
② 史蒂夫·乔布斯每天都穿着同样的三宅一生黑色高领毛衣和New Balance 991鞋。
③ George R. R.Martin在已有40年历史的DOS操作系统上写小说。
④ 贝多芬总是准确地数出60颗咖啡豆来煮咖啡。
... 
#+END_QUOTE
    date:: [[2023-11-17]]
*** from _纠正下，Steph ango不是Obsidian..._ by @vista8 on Twitter
*** [[https://twitter.com/vista8/status/1725161224390754574][View Tweet]]