:PROPERTIES:
:title: readwise/1_发达国家对中国“去风险化”，对中国的中短期影...
:END:

:PROPERTIES:
:author: [[CaminoTexas on Twitter]]
:full-title: "1/发达国家对中国“去风险化”，对中国的中短期影..."
:category: [[tweets]]
:url: https://twitter.com/CaminoTexas/status/1666570016588742656
:image-url: https://pbs.twimg.com/profile_images/1298068958709514243/6O-XlQFx.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-18]]
** 📌
#+BEGIN_QUOTE
1/发达国家对中国“去风险化”，对中国的中短期影响怎样，或者说几年到十年后，中国经济前景会怎样？可以把华为作为一个样本来做个大致不离谱的判断。几年前，华为是中国企业的佼佼者，在5G设备和技术上大有压倒欧美之势，手机势头直逼三星。但天朝选择跟美国正面对抗，让这家企业成为美致命打击的对象。 
#+END_QUOTE
    date:: [[2023-06-08]]
*** from _1/发达国家对中国“去风险化”，对中国的中短期影..._ by @CaminoTexas on Twitter
*** [View Tweet](https://twitter.com/CaminoTexas/status/1666570016588742656)
** 📌
#+BEGIN_QUOTE
2/几轮打击后，如今华为连5G手机也无法正常生产，本来已经占据不小欧美市场份额的电信设备，尤其是5G设备，也几乎丢失殆尽。几年间，从一个国际领先的企业迅速陨落，这还是在天朝官府用行政手段强力支持华为产品的情况下。任老板是中国的天才企业家，见识和能力都了不起，但个人能力再强，扭不过大势。 
#+END_QUOTE
    date:: [[2023-06-08]]
*** from _1/发达国家对中国“去风险化”，对中国的中短期影..._ by @CaminoTexas on Twitter
*** [View Tweet](https://twitter.com/CaminoTexas/status/1666570019097006080)
** 📌
#+BEGIN_QUOTE
3/把中国当成一个大号的华为，可以大致判断一下针对中国的“去风险”持续几年后，中国经济可能会怎样。中国是个比较封闭的国家，十年前本人就这样讲，那时候一些国内朋友还觉得奇怪，认为中国已经很开放。如今，那个时空从比较封闭进入了极端封闭的状态。但长年累月的封闭对人们心智的戕害无处不在， 
#+END_QUOTE
    date:: [[2023-06-08]]
*** from _1/发达国家对中国“去风险化”，对中国的中短期影..._ by @CaminoTexas on Twitter
*** [View Tweet](https://twitter.com/CaminoTexas/status/1666570021072523270)
** 📌
#+BEGIN_QUOTE
4/这也就是国民普遍的精神世界和心灵的封闭。包括不少专业做得不错的人，在谈及世界上一些现象时，分不清事实和传说，对现实的判断违反常识，对国外事务缺少基本的现代文明人见识。到现在为止，还有不少人以为中国可以分化欧洲和美国。华为先是退出美国，挣扎了几年，不得不退出欧洲，如今退出东亚。 
#+END_QUOTE
    date:: [[2023-06-08]]
*** from _1/发达国家对中国“去风险化”，对中国的中短期影..._ by @CaminoTexas on Twitter
*** [View Tweet](https://twitter.com/CaminoTexas/status/1666570023089872896)
** 📌
#+BEGIN_QUOTE
5/ 二战后，欧美在国际事务上大致能协调行动，各国在具体执行时，围绕各自利益，有的加码，有的打折，但有明确的框架，被分化的空间不大。总体上讲，在协调行动方面，欧洲各国比美国慢一拍，要到打打折。这种pattern完美地表现在华为的案例上，可以预见，同样的pattern也会表现在去中国风险进程中。 
#+END_QUOTE
    date:: [[2023-06-08]]
*** from _1/发达国家对中国“去风险化”，对中国的中短期影..._ by @CaminoTexas on Twitter
*** [View Tweet](https://twitter.com/CaminoTexas/status/1666570026025975809)
** 📌
#+BEGIN_QUOTE
6/上面说的是常态下“去风险”有可能出现的局面，不适用于非常状态下的断腕式脱钩。所谓“非常状态”是Carl Schmitt的术语，大致是指战争状态。那种情况一旦发生，欧美日澳的制裁对中国经济的冲击将会是一场接一场的tsunami，跟那幅场景相比，眼下正在发生的“去风险”完全是和风细雨。 
#+END_QUOTE
    date:: [[2023-06-08]]
*** from _1/发达国家对中国“去风险化”，对中国的中短期影..._ by @CaminoTexas on Twitter
*** [View Tweet](https://twitter.com/CaminoTexas/status/1666572682266025985)