:PROPERTIES:
:title: readwise/开窍后的9大表现！别他妈的害怕，开窍了你就是黑马...
:END:


* metadata
:PROPERTIES:
:author: [[BennyLeeBTC on Twitter]]
:full-title: "开窍后的9大表现！别他妈的害怕，开窍了你就是黑马..."
:category: [[tweets]]
:url: https://twitter.com/BennyLeeBTC/status/1767482248482480207
:image-url: https://pbs.twimg.com/profile_images/1760599757456842752/JGYdCoeE.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-03-13]]
** 📌 [[2024-03-13]]
#+BEGIN_QUOTE
开窍后的9大表现！别他妈的害怕，开窍了你就是黑马！

1. 对周围人，只筛选不改变。
不再试图改变任何人，比起之前替别人操心、提各种建议。现在不再执着改变对方，因为人在意识到问题，和解决问题之间有巨大的鸿沟。

2. 眼神特别。
开窍后最明显的一个特征就是眼神，无论是面对世事还是周遭的环境，眼神都显得与众不同，有着一种独特的清醒和冷漠。不轻易展现真实的自己，常常保持一种距离感，不愿意被别人看到自己的情绪和内心。
眼神可以透露出自己的情绪，也可以传递出自己的态度。这种特别而独特的眼神，更容易与他人产生共鸣。

3. 学会及时止损
面对不合适的人或者事情直接淘汰，成年人只筛选不教育。不再心情一好就原谅一切，默默承受未必好事。懂得取舍，懂得只有三观一致才能相互接洽，圈子不同不必强融。

4. 学习不是目的，会用实践起来就是目的。
出手就是终局的思维。学习是一个过程，不能当作目的。学会一个知识，马上去实践得到答案，得到结果。

5. 习惯孤独的常态
学会了和自己独处，享受安静的生活。不再愿意与他人交流和分享，而是专注于自己的兴趣和爱好。
这种状态，可以更好地专注于现实生活中的事情，享受自己的私人空间。同时，也学会了独立和自我管理，不再被他人的眼光左右。

6. 明白真正强大不是对抗，而是接受
允许世事无常允许遗憾，允许有人不喜欢自己。远离负能量和消耗自己的人事，不轻易被外界看法和言语动摇。

7. 乐观面对生活
珍惜生活每一天，虽然知道人情淡寡，世态炎凉却仍然热爱生活。处世不惊，福祸相依，否极泰来，换个角度看问题，开心不开心就是一念之间。

8. 生活有目标，有复盘
知道想过什么样的生活，在自己能力范围内为之努力，不虚高追求，不贬低自己。定期在复盘的过程中，对自己越来越了解，目标也越来越清晰。

9. 回归真正的自己
回归到本我的个性，活出自己独一无二的特质。只有回归到真实的自己，才能真正地了解自己的需求、价值和梦想，并坚守自己的原则和价值观。这种个性可以让我们更好地理解自己，过上真正属于自己的人生。 
#+END_QUOTE\