:PROPERTIES:
:title: readwise/\# Automating Software En...
:END:


* metadata
:PROPERTIES:
:author: [[karpathy on Twitter]]
:full-title: "\# Automating Software En..."
:category: [[tweets]]
:url: https://twitter.com/karpathy/status/1767598414945292695
:image-url: https://pbs.twimg.com/profile_images/1296667294148382721/9Pr6XrPB.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-03-13]]
** 📌 [[2024-03-13]]
#+BEGIN_QUOTE
# automating software engineering

In my mind, automating software engineering will look similar to automating driving. E.g. in self-driving the progression of increasing autonomy and higher abstraction looks something like:

1. first the human performs all driving actions manually
2. then the AI helps keep the lane
3. then it slows for the car ahead
4. then it also does lane changes and takes forks
5. then it also stops at signs/lights and takes turns
6. eventually you take a feature complete solution and grind on the quality until you achieve full self-driving.

There is a progression of the AI doing more and the human doing less, but still providing oversight. In Software engineering, the progression is shaping up similar:

1. first the human writes the code manually
2. then GitHub Copilot autocompletes a few lines
3. then ChatGPT writes chunks of code
4. then you move to larger and larger code diffs (e.g. Cursor copilot++ style, nice demo here https://t.co/u8ueY0mGxZ)
5....
Devin is an impressive demo of what perhaps follows next: coordinating a number of tools that a developer needs to string together to write code: a Terminal, a Browser, a Code editor, etc., and human oversight that moves to increasingly higher level of abstraction.

There is a lot of work not just on the AI part but also the UI/UX part. How does a human provide oversight?  What are they looking at? How do they nudge the AI down a different path? How do they debug what went wrong? It is very likely that we will have to change up the code editor, substantially.

In any case, software engineering is on track to change substantially. And it will look a lot more like supervising the automation, while pitching in high-level commands, ideas or progression strategies, in English.

Good luck to the team! 
#+END_QUOTE\