:PROPERTIES:
:title: readwise/13｜实战知识：让我们编程计算下怎么还房贷最合适
:END:

* metadata
:PROPERTIES:
:author: [[geekbang.org]]
:full-title: "13｜实战知识：让我们编程计算下怎么还房贷最合适"
:category: [[articles]]
:url: https://time.geekbang.org/column/article/405898
:tags:[[gt/程序员的个人财富课]],
:image-url: https://static001.geekbang.org/resource/image/2d/1d/2d2879a68789c872a706bd3bd5dyyd1d.jpg
:END:
* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
言归正传，定义清楚了问题，我们还得弄明白影响家庭财富的主要变量有哪些，这样才能编程去优化它。从我自己的经验出发，我觉得主要有下面六项：

房产总价

房产升值速度

房贷利率

工资收入

理财收入

家庭生活支出 
#+END_QUOTE\
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
有心的同学可能会问了：那其他变量呢？比如个人收入、生活支出的改变，会导致结论反转吗？很简单，你再用我们的程序模拟一下就行了，我这里就直接说结论了：不会。只有理财收益率和房贷利率的关系，是影响房贷方式的终极要素。

用一句话总结就是，如果你的稳定理财利率能够高于房贷贷款利率，那么首付少付、还款年限长合适；反之，如果你的稳定理财利率低于房贷贷款利率，那么首付多付、还款年限短合适。 
#+END_QUOTE\
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
拿我自己的例子来说，我在做买房决策的时候会做两件事：

第一件，是根据自己掌握的资金，严格地控制购房预算。

比如，假设我现在有 200 万购房款，我要把房价和购房款的比例控制在两倍以内，那我的购房预算就是 400 万。

第二件，是尽量少付首付，留一些流动资金。比如我在真正贷款的时候，即使可以付 50% 的首付，也会按照 35% 的比例付首付。

一方面，这是因为我对自己的理财能力有足够的信心，相信自己有能力实现超过 4.65% 的理财收益；另一方面，我目前在美国工作，这里的房贷利率比在国内低得多，只有 2.65%。在这种利率情况下，如果理财能力强的话，就应该寻求高贷款加理财的组合方案。 
#+END_QUOTE\
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
如果你的稳定理财利率能够高于房贷贷款利率，那么首付少、还款年限长合适；反之，如果你的稳定理财利率低于房贷贷款利率，那么首付多、还款年限短合适。 
#+END_QUOTE\
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
激进的可以参考 深房理 那种证券化玩法（很危险）。还会坐牢。只是可以看看涨涨见识。 
#+END_QUOTE\
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
通货 是要适当考虑。但是现在有点妖魔化了，人们有点过度焦虑。 记得我投资老师跟我说的，大部分人不是死在通货膨胀下的，而都是死在害怕通货膨胀而导致的胡乱投资上的。 还有一句话对我影响特深，就是在讲 股市长线法宝 和 投资组合理论 两本书的时候，一个结论：股市短期波动大，但长期收益最大并且风险最小，是唯一能战胜通货膨胀的资产。现金 和 债券 都是短期波动小，但长期收益跑不过通货。这种短期风险比和长期风险比的错配，是股市反人性的一大特点。 
#+END_QUOTE\
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
最后分享个 投资中的不可能三角模型。一种投资品，不可能兼顾 收益 风险 流动性 三个优点。比如股市：长线价值投资 就是 放弃流动性 追求 收益和风险。短线 就是 保证 流动性和收益，追求控制风险（止损）。房子就是 放弃流动性 追求 收益和风险。 货币基金就是 放弃收益，追求流动性和 风险为0. 当拿到一种新投资品时候一定要想清楚 他舍弃什么 追求什么。比如p2p,及保证流动性 又保证无风险，还保证10%以上的高收益，就要小心，他一定是隐藏了什么，其实就是隐藏了极大的风险。那数字货币了？其实也可以思考下。 
#+END_QUOTE\
** 📌 [[2023-04-10]]
#+BEGIN_QUOTE
推荐B站的纪录片，房东到家 
#+END_QUOTE\