:PROPERTIES:
:title: readwise/1、大部分成年人的开窍都是经历痛苦，折磨，负债，...
:END:


* metadata
:PROPERTIES:
:author: [[NPC888666 on Twitter]]
:full-title: "1、大部分成年人的开窍都是经历痛苦，折磨，负债，..."
:category: [[tweets]]
:url: https://twitter.com/NPC888666/status/1719685437588119685
:image-url: https://pbs.twimg.com/profile_images/1696731370150825984/8-1Y3zr_.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-11-02]]
#+BEGIN_QUOTE
1、大部分成年人的开窍都是经历痛苦，折磨，负债，耻辱，大彻大悟才开窍的，没有贵人高人的指点，肯定是要经历磨难的。

人只有看清社会的妖魔鬼怪才能理解人道，被暴力打击，オ能看清现实。

等你熬过去，回头看，才发现这些磨难和挫折最终都是为了成就你，度化你。 ​​​

2、真正称得上好福气的人，往往都是那些前半生吃尽了苦头，后半生才开始反转的人。老人言，前福为虚，后福为实，人的一生，酸甜苦辣大体上是平衡的，先把不好的经历了，接下来，就是后福无量了。记住了，好饭不怕晚，后福才是福。

3、过度劳碌是一种减寿行为

人是一支可燃尽的蜡烛，什么事情都要亲力亲为，没有尽头的加班做事，不是能者多劳，是不配享福气。

破解法是放权，抓大放小，只把握大方向不偏离，其他事交给其他人，要允许别人做的没你好，允许别人出差错，允许别人成长。

4、常常心存善念，诸恶莫作，好运来的时候，才能接得住，才能对一些福报受之坦然，而不会因为无意识的自责自罪搞砸一些事、推开一些机会，以为是外来的惩罚，其实是自己跟自己过不去，自己不允许自己幸福。 ​​​

人的姻缘不要看急，如果30岁前还没遇到另一半，只要不是阴差阳错日生的，那就是自己还不够强大，成婚越早变数越大，因为不太成熟，酿成苦果，往往有些人的格局注定适于晚婚，如果你的一生没有婚姻，那就代表你来人间的使命不在于生儿育女，你前世没有感情债和儿女债，是一件好事，你的使命在别的六亲缘里面，每个人进入人间以前，三生石上的内容都看过，所有的剧本都是自己认可的。

5、让人三尺，度己一生，世间所有的福报，都是你日积月累的善良与慈悲，但行好事，莫问前途。

6、开悟不算什么，开悟以后落地生活，才重要。

高维不算什么，不把这些维度和概念当作自傲的资本，跟人都能好好说话，才重要。 
#+END_QUOTE\