:PROPERTIES:
:title: readwise/第一次被裁员、第一次绩效不及格……很多类似经历都...
:END:


* metadata
:PROPERTIES:
:author: [[CatChen on Twitter]]
:full-title: "第一次被裁员、第一次绩效不及格……很多类似经历都..."
:category: [[tweets]]
:url: https://twitter.com/CatChen/status/1779733226145427512
:image-url: https://pbs.twimg.com/profile_images/1157952088/Cat.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-04-19]]
** 📌 [[2024-04-15]]
#+BEGIN_QUOTE
第一次被裁员、第一次绩效不及格……很多类似经历都跟第一次分手一样，多几次就习惯了。这些经历本身不是问题，问题在于大家都不会跟别人说，因此大家都以为这事情只发生在自己身上，然后开始从自己身上找原因，最后被 shame 或者 guilt 吞噬。这些事情都跟 dating 一样，发现不合适就赶紧 move on！ 
#+END_QUOTE\
** 📌 [[2024-04-15]]
#+BEGIN_QUOTE
工作上遇到什么样的老板和什么样的项目，我一直说这跟桌游摸牌没什么区别：你摸到一张跟你其它手牌配合得好的牌，你就想办法留着；你摸到一张不想要的牌，你就弃牌重摸。弃牌是一种战略，不要为摸到不好的牌然后打得不好而在自己身上找原因。 
#+END_QUOTE\
** 📌 [[2024-04-15]]
#+BEGIN_QUOTE
我在 FB 拿到第一个绩效不及格也很崩溃啊。那时候还没有绿卡，连续两次不及格就 GG 了，所以胆战心惊地求生存。我才刚升到 E5，老板就给我一个「做成了就升 E6，做不成就挂 E5」的项目给我，做不成是正常的。后来我发现这种错配并不罕见，只是大家都不敢说而已，觉得是自己的问题，怕说出来丢脸。 
#+END_QUOTE\
** 📌 [[2024-04-15]]
#+BEGIN_QUOTE
现在我拿到绩效不及格也没什么所谓了，了解清楚 feedback 都涵盖什么，计划好将来做事情的方式要怎样改变，如果真的合不来就换组、换老板或者换公司。这不一定是谁的错，换到合得来的我能拿很好的绩效，所以不要花太多心思思考那些合不来的。 
#+END_QUOTE\
** 📌 [[2024-04-15]]
#+BEGIN_QUOTE
我被 Robinhood 裁员的时候，我连段子都想好了！「35 岁裁员在美国是不存在的，你们看我可是 36 岁才被裁的！」裁员后两个月我聊了 50 家公司、认真面了 10 家并且收了 7 个 offer，包括薪水更高和级别更高的 offer。所以说不合适就别挣扎，也别从自己身上找问题，还有更好的选择等着你。 
#+END_QUOTE\