:PROPERTIES:
:title: readwise/14｜基金投资：如何让专业人士帮你赚钱？
:END:

:PROPERTIES:
:author: [[geekbang.org]]
:full-title: "14｜基金投资：如何让专业人士帮你赚钱？"
:category: [[articles]]
:url: https://time.geekbang.org/column/article/406509
:tags:[[gt/程序员的个人财富课]],
:image-url: https://static001.geekbang.org/resource/image/5c/7b/5cc17394255ac9dacccce5346a2cbb7b.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-18]]
** 📌
#+BEGIN_QUOTE
因为本质上来说，基金并不是一种具体的投资标的，而是一种投资工具。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdf0cnfenyadj02qs1kvjz)
** 📌
#+BEGIN_QUOTE
比如，根据投资标的的不同，基金主要分为以下四种：

投资于股市的股票型基金；

投资于债市的债券型基金；

股市债市都投的混合型基金；

投资于短期货币市场的货币基金。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdff4gyqhrkz7xfn8mhw09)
** 📌
#+BEGIN_QUOTE
基金还可以按照投资地点分类，比如分别投资于美国、欧洲、日本的不同 QDII（Qualified Domestic Institutional Investor，合格的境内机构投资者）基金。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdfqvm3z01vzbd1m22hznt)
** 📌
#+BEGIN_QUOTE
我们还可以按照投资的特点，来对基金进行分类，比如完全按照指数比例被动配置的指数型基金，和根据基金经理的理念主动配置的主动型基金等等。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdfytzmwzzmytjvhkp8kcz)
** 📌
#+BEGIN_QUOTE
所以，选基金的过程，像极了董事长或投资人创建公司和选择 CEO 的过程。你想想，一位投资人想创建一个公司，他会按照怎样的步骤来呢？我想典型的步骤就两步：

1. 选择行业和方向。

2. 选择合适的 CEO 管理我的公司。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdggp65kfng37wcnpkj5ja)
** 📌
#+BEGIN_QUOTE
第一步，基于资产配置组合或支点投资法，选择一个你认可的投资赛道。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdgsm446zq4rtad8v4h1qy)
** 📌
#+BEGIN_QUOTE
所以，在进行基金投资的时候，要先明确你的投资判断位于投资理财金字塔的哪个层级，是投资标的大类级别，还是行业级别，还是更细分的赛道级别。然后，选择对应层级上的基金，这样才能精确地对应你的投资逻辑。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdjwcavxfqyss8kmm45sf1)
** 📌
#+BEGIN_QUOTE
第二步，选择一名优秀的基金经理。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkdk71tfsn0hepsz3z6390r)
** 📌
#+BEGIN_QUOTE
对于任何主动型基金，基金经理的历史业绩远远比基金本身的历史表现重要。为什么会这样呢？

这主要还是由基金公司的运作模式决定的。对所管理的基金，基金经理几乎拥有绝对掌控权，而其他支持性的团队（比如投研团队）只起到辅助作用。基金的盈利与亏损，责任几乎完全由基金经理来承担。所以，如果一只基金更换了基金经理，那么就意味着这只基金的灵魂被更换了，就算它的历史业绩再光鲜，都不具备很强的参考价值。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkgpr65gthf98a2dqjc98fe)
** 📌
#+BEGIN_QUOTE
在“基金经理是一只基金的灵魂”这个前提下，我们就可以得到两条非常有价值的推论了：

新的基金尽量不要购买。如果要一定要购买的话，就必须先调研清楚这只新基金的经理的历史业绩，并且要重点查看这位基金经理是不是操盘过同类的基金。

更换了基金经理的基金等同于一只新基金。如果一只基金更换了基金经理，那么它所有的历史评级、历史业绩都不具备很强的参考价值，几乎可以看成一只新基金。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkgq05abedg09cxt4m2q1r3)
** 📌
#+BEGIN_QUOTE
基金经理是为你服务的，不是为你背锅的 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkgq5w1f3hmnvdqdz5vws4t)
** 📌
#+BEGIN_QUOTE
其实牛逼的基金经理就那几个。 进攻型：谢治宇，张坤，朱少醒，傅博鹏，何帅，董承非 防守型：林乐峰，欧阳凯，张清华，李轶 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkgrefnt23pqghkjq2hqkw9)
** 📌
#+BEGIN_QUOTE
但是还是那句话，基金赚钱，散户基本拿不住。董承非有次采访说过我的基金涨了5年7倍，但是赚到钱的客户只有12%。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkgrrzqabprsxa9cnwtygfx)
** 📌
#+BEGIN_QUOTE
基金不适合频繁交易，有一个原因是申购费跟赎回费，申购费一般比较低，经常会有打折，但短时间内进行赎回的赎回费率为1.5%，以天天基金中任意一只基金为例，申购最低额度的基金费率为0.15%，持有时间最短的赎回费率则为1.5%，是申购费的十倍，由此可见，影响基金收益的一个主要原因是频繁交易产生的较高赎回费。 证监会规定，持有基金时间较短的赎回费率不低于1.5%，以易方达基金为例，小于等于6天的赎回费率为1.5%，大于等于6天，小于一个月的为0.5%，一年以上的为0.25%，两年以上则免收赎回费，基金持有时间太短，不仅损害长期利益，还会使现有盈利下降，假如我近段时间盈利1000，而5天后想赎回，那么赎回费率是1.5%，也就是15块，而6天以后再进行赎回，那么赎回费率是0.5%，也就是5块，赎回费用足足多了两倍，如果能多忍耐一天，就不会有这个损失了。翻看它的盈利概率可以发现：长期持有基金的盈利概率要大于短期持有基金的盈利概率，任意翻看一只基金，都是长期持有基金的盈利概率要大于短期持有基金的盈利概率，可以理解为基金投资是靠长线赚钱的，而非短线，因此频繁交易，大量赎回的做法并不可取。 其实，只要搞清楚基本的投资逻辑就能明白为什么长期持有基金才会有更好的收益。设想一下：一个人投资1000能获得100的收益，要是全部亏损，则损失1000，风险较大，这个时候如果既想保住同之前一样的收益，又不想加大风险，就只能通过同他人合资，加大投资总额，拉长时间线的方式来实现了，在投资总额不变的情况下，就只有单人投资金额跟投资人数两个是变量了，单人投资金额越小，则投资人数需越多，反之，投资人数越少，单人投资金额需越大。而在基金投资中，每个人都想在减少风险的情况下获得同之前高风险下同等或更高的收益，那么，在单人投资金额较少，但投资人数足够多时，可操作的资金越多，越容易产生较大收益，而在发生大量赎回行为，可操作资金减少时，还想在较短时间内获得同之前相同的收益，那就只能加大资金投入了，随着投资力度的加大，盈利所产生的收益也会变大，但一旦赔了，就需要后续投入更多资金把上次赔掉的赚回来，此种情况在投资人投资金额变少，而投资人数又不够多时，无疑加大了投资风险。在资金总额较少，而又加大资金投入时，可用的投资次数相应地也会减少，翻盘的机会也随之变少，一旦运气不好，就有可能把之前赚的全部赔掉，显然这时候采取小额投资，拉长时间线的方式，则可以在后面数次的投资机会中将原先损失掉的赚回来。这样看来，大量可投入资金，长时间线的小额投资，能够最大限度帮助盈利，这就是为什么基金长期持有才会有更好收益的原因。 一般来说，进行频繁赎回的这类人，都有着见不得一点损失，急功近利的心态，当看到下跌时，匆匆忙进行赎回，将赎回的资金用于其他走势大好的盈利资产项上，这将严重影响资产配置的平衡，风险集中在少数资产项上，可能导致大面积亏损，假如你投资的这份资产项持续向好，那自然最好，如果下跌了呢？那估计亏损也不少，可以说频繁的赎回行为会有损长期收益，加大亏损风险。这一切看起来像是由于投资者惧怕损失，急功近利引起的，但确切地说是由于没有一个科学挑选基金的方法引起的，一只不好的基金会有长期大量下跌，从而导致频繁赎回的行为，而经过科学的方法挑选出来的基金，则会表现良好，没有太多下跌，从而不会引起频繁赎回的行为，与其说投资者惧怕损失，倒不如说缺少科学的选基金技能，这时候最应该做的是锤炼选基金的技能，以避免坏基金带来的频繁赎回行为。可以说，挑选一只好基金，长期持有，才能最大限度保证盈利。 
#+END_QUOTE
    date:: [[2023-04-10]]
*** from _14｜基金投资：如何让专业人士帮你赚钱？_ by geekbang.org
*** [View Highlight](https://read.readwise.io/read/01gxkgtfh7cyj4qmz3aw1xftps)