:PROPERTIES:
:title: readwise/我今年结构性错过的赛道是比特币生态，这是需要反思...
:END:

:PROPERTIES:
:author: [[jason_chen998 on Twitter]]
:full-title: "我今年结构性错过的赛道是比特币生态，这是需要反思..."
:category: [[tweets]]
:url: https://twitter.com/jason_chen998/status/1725341408540905709
:image-url: https://pbs.twimg.com/profile_images/1653068718321336321/grq9EkXA.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-18]]
** 📌
#+BEGIN_QUOTE
我今年结构性错过的赛道是比特币生态，这是需要反思的。在今年3月份的时候就写过比特币NFT与Token，但因为种种原因不论认知还是偏见错过了，这几天思考和探讨逐渐的将一些困惑梳理清楚了，当然我肯定依然有理解错误不到位的地方，只是分享一下我的拙见。
之前在我眼里比特币生态有两条发展方向，姑且称之为主流和非主流吧。主流即闪电网络、BTC二层、智能合约这些，即想办法提升比特币网络的可用性，非主流则是BRC20铭文这些在比特币网络中发行资产，如果单独拆开看这两条路，会感觉每一条都“不靠谱”，但现在这两条路正在交汇中...
我之前也在推特聊过，我认为以太坊能坐稳当前的位置，很重要的原因就是17年ICO让它成了一条资产链，大量群魔乱舞的资产发行在以太坊上，尽管潮水退去留下的不多，但是资金在哪，用户在哪，开发者在哪，项目就在哪。
这么多资产被发行在以太坊链上，自然要有对应的设施和应用去服务它，从而为后面的Defi Summer打下了基础，让以太坊实现从资产到应用的跃迁。
钱是这个行业的大爷，大家都围着钱转，如果以太坊当年没有经历ICO，也不会有现在的curve、aave这些想办法盘活资产的，更不会有OP、ARB这些想办法提效资产的。
那回到比特币生态，在BRC20没有出现之前，很多人认为比特币就老老实实做数字黄金吧，也没有多少人真的想用比特币来做支付，所以当时闪电网络、智能合约的主流这条路是没有“需求”来驱动前进的，发展也比较缓慢。
而随着BRC20在比特币生态也进行了一波“群魔乱舞”般的资产发行，潮水退去后也一定会有大量归零的，但是多少会留下核心资产，那这些资产以后的盘活要靠谁？是否会出现比特币的Defi？并且也正因为之前没有人真的想“用”比特币，使得比特币网络的性能差其实也没多大影响，但是随着现在资产发行与转移的需求爆发式增长，一个铭文要转半小时，这些有钱的大爷们需求摆在这里，谁来服务？是否会推动比特币二层的发展？所以比特币是否会重现以太坊ICO-Defi-Layer2这条路？
以及二级市场散户已经厌接盘久矣，凭什么一个从谷歌微软出来的人搞了条公链，一帮VC站台啥应用都没有就估10亿美金，然后发到二级让散户去接盘呢？当然只要在金融市场本质上都是接盘，只是接谁的盘，盘能接多久的区别，Fair Lunch也是接盘，但是是接消息的盘，接社区的盘，接共识的盘。
以太坊一定会继续存在，ETH也肉眼可见的会5000、8000、10000，比剩以落的现象我认为不会存在，我也并不贬低以太坊，我依然会持续的关注以太坊生态并研究写文章，主流金融世界在应用层面对于以太坊的支撑力度依然巨大，但是以太坊确实变得更加无趣了，10年发展规划也都写在了地图中，Vitalik的一篇文章也能引的市场“地动山摇”，以太坊基金会稍微卖点币Vitalik都得跑出来澄清自己从没有因为个人利益出售过ETH。
最后借用昨天Odos兄的一句话，挨打就要立正，错过就要复盘，放下偏见，找到机会，跑步入场。
请注意当前铭文已经进入到了动物园阶段，风险极大。 
#+END_QUOTE
    date:: [[2023-11-17]]
*** from _我今年结构性错过的赛道是比特币生态，这是需要反思..._ by @jason_chen998 on Twitter
*** [View Tweet](https://twitter.com/jason_chen998/status/1725341408540905709)
** 📌
#+BEGIN_QUOTE
行业的赛道太多不可能抓住所有，也不能心猿意马猴子掰苞米，但是错过复盘还是需要的，从而避免下一次更多的错过，人只能赚认知内的钱，需要做的是扩大自己的认知 
#+END_QUOTE
    date:: [[2023-11-17]]
*** from _我今年结构性错过的赛道是比特币生态，这是需要反思..._ by @jason_chen998 on Twitter
*** [View Tweet](https://twitter.com/jason_chen998/status/1725350117534990362)