:PROPERTIES:
:title: readwise/纽约时报：Sam Altman，探讨人工智能的未...
:END:


* metadata
:PROPERTIES:
:author: [[dotey on Twitter]]
:full-title: "纽约时报：Sam Altman，探讨人工智能的未..."
:category: [[tweets]]
:url: https://twitter.com/dotey/status/1731115143738667054
:image-url: https://pbs.twimg.com/profile_images/561086911561736192/6_g58vEs.jpeg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-12-03]]
#+BEGIN_QUOTE
纽约时报：Sam Altman，探讨人工智能的未来挑战

2023 年 12 月 2 日， 作者：Maureen Dowd

在《黄昏地带》这部剧中，我最喜欢的一集是外星人来到地球，带来了一本书作为和平的象征。这本书让政府的密码专家费尽心思去翻译。他们首先译出了书名：“To Serve Man”，似乎预示着一切都是安全的，人们甚至开始乘坐星际穿梭航班。

然而，随着翻译的深入，他们震惊地发现，这本书竟然是一本食谱。

这个故事与 OpenAI 的历史颇有相似之处。

OpenAI 成立于 2015 年，初衷是作为一个非营利组织，保护人类不受日益发展的人工智能技术的威胁。他们的目标是确保这项技术有足够的安全措施，就像在人工智能成长的关键时期设置一个紧急制动按钮。

当我 2016 年在他们旧金山的临时办公室采访 OpenAI 的创始人 Sam Altman、马斯克、Ilya Sutskever 和 Greg Brockman 时，他们自称是我们的守护者，保护我们免受失控、邪恶人工智能的威胁。他们面对的是滥用技术的不法分子和恶劣的机器人，以及那些幻想着像玛丽·雪莱一样创造出新物种的云端领袖们。

Sutskever 当时表示：“我们的目的绝不是为了个人利益。”

Brockman 的想法也很崇高：“我们不能只是发明这项技术，然后就撒手不管。我们的工作不是这样结束的。我们需要让世界理解并妥善使用它。”

但现在 OpenAI 正在面临新的挑战。马斯克已经离开，Altman 不再是那个站在人类一边的守护者。他现在正领导着一家盈利公司，专注于开发人工智能的潜能。他对投资者的兴趣超过了对潜在危险的关注。正如 Robert Oppenheimer 所说：“当你发现某项技术非常有吸引力时，你就会去实现它。”

虽然政府试图细微调整监管政策，但 AI 技术的发展速度远超过慢吞吞的立法者和官僚。在硅谷，似乎没有人知道该如何控制这股势头。

OpenAI 最近的一次混乱事件，看似荒唐，实际上却揭示了一个可怕的事实：我们完全受制于硅谷那些拥有先进玩具的年轻人，他们的自我、脾气、野心和贪婪在不断碰撞。

关于马斯克最近的行为失控，大家的看法各异——无论是他的狂热情绪，具争议的推文，还是他设计的奇特、棱角分明的 Cybertruck 卡车。但不可否认的是，他始终热衷于抵制恶意 A.I.。为了实现 A.I. 发展与保护人类价值观相协调这一可能有些理想化的目标，马斯克经历了不少不眠之夜和友情的破裂。

马斯克力邀俄罗斯籍顶尖工程师 Ilya Sutskever 从谷歌加盟 OpenAI，这让谷歌联合创始人、AI 加速主义者 Larry Page 感到愤怒，最终与马斯克决裂。Page 认为马斯克偏袒人类，在 AI 问题上持有“物种主义”观点。

马斯克还与 Altman 发生了冲突。正如 Walter Isaacson 在《Elon Musk》一书中所述，马斯克曾在二月份召见 Altman，并要求他带来 OpenAI 的创始文件。不久后，马斯克 在Twitter上表示困惑：“我捐赠了1亿美元的非营利组织，怎么可能变成了市值300亿美元的营利公司？如果这是合法的，那为什么不是每个人都这样做呢？”

在接受 Kara Swisher 采访时，Altman 称马斯克为“混蛋”。

正如莎士比亚所描绘的那样，个性冲突在 AI 领域的生死斗争中扮演了重要角色。Altman 减少了 Sutskever 在公司中的作用，这可能是引发对他的反叛的导火索。

关于这一事件的具体细节，我们仍然一无所知。是不是董事会发现了 AI 算法的某些重大进展，从而决定解雇 Altman，因为他们担心他在没有充分考虑安全措施的情况下推广产品？

显然，AI 技术正在变得更加精湛，推理能力加强，错误减少，幻想现象（即编造事实）减少，甚至能够解决复杂的数学难题。

马斯克最近对 Sutskever 表示赞赏，认为他具有“良好的道德指南针”。这位年轻工程师曾加入董事会的悲观派，并在改变主意前向 Altman 传达了坏消息。他在谷歌的导师 Geoffrey Hinton 是否对他产生了影响？

人工智能之父 Hinton 对 OpenAI 的杰作 ChatGPT 感到震惊，他意识到我们可能离 A.I. 智能超越人类只有几年时间。Hinton 在 10 月接受《60 分钟》（60 Minutes）采访时表示忧虑，担心 A.I. 可能会恶意地反抗人类，利用它从所有书籍中学到的知识操纵我们，包括马基雅维利（Machiavelli）的著作。

与马斯克不同，后者据 Isaacson 描述，有时会显得尴尬甚至进入“恶魔模式”，Altman 在与投资者、技术人员和立法者的交流中显得更为自如，即使是穿着 T 恤和牛仔裤也自在从容。一位硅谷顶尖科学家将 38 岁的 Altman 描述为“奇特地可爱”。他与众多记者关系良好，成为了 A.I. 未来乐观面孔的代表。

但我们真的需要一个对 A.I. 抱有阳光态度的人吗？不，尤其是考虑到马斯克上周四的警告：“世界末日可能随时到来。”

原文：Sam Altman, Sugarcoating the Apocalypse
https://t.co/JL54STSWtz 
#+END_QUOTE\