:PROPERTIES:
:title: readwise/国内大企业出海更习惯在Mobile App上发力...
:END:


* metadata
:PROPERTIES:
:author: [[0xthefool on Twitter]]
:full-title: "国内大企业出海更习惯在Mobile App上发力..."
:category: [[tweets]]
:url: https://twitter.com/0xthefool/status/1776020433516859597
:image-url: https://pbs.twimg.com/profile_images/1749127093391425536/3KlfmY5b.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-04-08]]
** 📌 [[2024-04-05]]
#+BEGIN_QUOTE
国内大企业出海更习惯在Mobile App上发力，一是因为团队积累人才属性，二是过去十年电商和游戏把APP的路趟明白了很多，在较为熟悉的领域作战。

但是国内外的生态还是很多不同的，用户习惯增长模式变现模式都有很多可以研究的地方，不过从数字开始最容易建立正确的认知。分享一下我整理的关于获客、留存、变现以及AI类APP你要知道的最关键的信息。

【获客】
\- 全球安卓平均获客成本：下载$1.2，注册用户$2.2，订阅用户$45.9，app内购用户$86.7。
- 全球苹果平均获客成本：下载$3.6，注册用户$7.6，订阅用户$33.1，app内购用户$77.5。
- 在掏钱之前，安卓的获客成本都远低于苹果，但是要让安卓用户掏钱的成本就明显高于苹果了。这一点和生态有关（ios的内置付费更友好），和用户习惯有关（安卓用户付费习惯差），但是也受到行业内灰产影响（安卓大量刷数据作弊行为）
- 拉美的下载成本可以做到$0.3，亚太是$0.9，中东是$1，美国直接飙升到$5.3。但是尤其根据我们合作过的AI产品来看，美国用户的付费转化比例要远高于其他地区。

【留存】
全市场平均来看，安卓应用一日留存是21.1%，月留存是2.1%。苹果稍高一些，日留存是23.9%，月留存是3.7%。
行业越垄断月留存率越高，新闻最高，购物其次，工具类型中下，留存最低的三个品类是游戏、教育和摄影录像产品
每个国家的月留存也有不同，日本可以做到5.1%，南非3.4%，美英法都在2.9-3%之间，印度1.9%，巴西1.7%，中国最低仅有1.5%。留存和用户消费习惯有关，也和市场竞争有关。

【营收】
全球市场中最常见的定价：每周$5，每月$10，每季度$30，每半年$40，每年最常见的定价反而是$20。这一点因产品品类和所在地区波动极大
全球市场中平均定价：每周$6，每月$8，每季度$26，每半年$32，每年$37。更为接近心理预期。

【AI产品】
23年全球AI类APP产品，全年营收40.6%来自于美国，英国和中国各占5%，日本4%。
23年全球AI类APP产品的总下载量中21%由美国贡献，印度贡献6%，巴西5%。可以明显看到美国的付费比例和付费贡献远高于其他国家。但是我怀疑这个数据不够准确，个人体感认为印度 俄罗斯 中国的下载量被严重低估。 
#+END_QUOTE\
** 📌 [[2024-04-05]]
#+BEGIN_QUOTE
大量数据整合自 https://t.co/dN0V6hmAlD，很好用的信息和数据平台。 
#+END_QUOTE\