:PROPERTIES:
:title: readwise/《权力必然让人智商降低》 这看起来特别像标题党...
:END:


* metadata
:PROPERTIES:
:author: [[Ansel_Flipradio on Twitter]]
:full-title: "《权力必然让人智商降低》 这看起来特别像标题党..."
:category: [[tweets]]
:url: https://twitter.com/Ansel_Flipradio/status/1768159344254951453
:image-url: https://pbs.twimg.com/profile_images/1634026807367458817/g30XvyQh.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-03-19]]
** 📌 [[2024-03-15]]
#+BEGIN_QUOTE
《权力必然让人智商降低》

这看起来特别像标题党，但其实是非常严肃的社会学分析。

我写这个的动因是本次农夫山泉的事件，其内容和指控方式匪夷所思，甚至动机都很难理解。又让我联想到网络上很多地方评论区的内容，质量低下但响应者众。本身是很有意思的现象。同样的情况在文革中也相当普遍，文革以及后期由大学者们炮制的各种文章，同样荒腔走板。

其基本原因是这样的。在我们与他人讨论问题的时候，面对分歧可以依靠道理，也可以依靠权力。例如环境保护与工业发展，本身是个很严肃和复杂的问题，但这问题在国内有非常简单的答案，即“环保”是西方设计用来限制发展中国际的议题，再随意引用几个丁仲礼和柴静采访的截图，这个问题就完结了。行政这种简单共识依靠的不是道理，而是权力，柴静才国内已经被封杀，而丁仲礼已经高升为人大副委员长，讲环保话题的回形针已经被猎巫到销声匿迹。权力不只像福柯一样，发明“知识”，权力当然还会直接采取奖惩的方式。这种奖惩在中国已经形成社会的“自我机制”，例如在福岛核排水事件，官方开足马力谴责日本，民间响应者众。机核网一位负责任在朋友圈以自我方式发布对这件事的吐槽，引发网络舆情后，机核网不得不将其开除。这件事不可能有上级的质疑，而只是机核网恐惧于自己将成为第二个回形针。

权力直接越过理性、说理、科学、数据为社会发明的“意识形态纪律”。而人又醉心于输赢，这里不是是否选择说理的问题了，而是说理变得不可能，几乎唯一可行的公共舆论，就是基于意识形态的猎巫概念游戏。在任何讨论中，“外国人”三个字，或“境外势力”四个字，或“西方”两个字就基本等于错误，请注意这不是个观念，因为在中国意识形态问题不只让你在网上被惩处，更会实际影响人的身体安全，带来线下的惩罚，因此这些词汇形成的是一种生理性的恐惧，让人对这些领域敬而远之。我亲见那些自文革而来的长辈，直到改开后，依然对一切政治话题和领域噤若寒蝉。

这些意识形态猎巫术就像一种魔法，只要喊出“咒语”，就可以刺激响应者的反应，甚至召唤铁拳下场。魔法都学会了，谁还花力气呢？连自诩“冰冷理性”的王志安，都在节目里像吴京一样热情地表达：我是中国人，维护国家主权是天然的。“中国人” + “国家主权”，一种类似火焰系魔法一样的狂热法术。如果我们要谈这个问题呢？「国家主权对普通人重要吗？」我相信都不必进入到具体的道理，绝大多数中国人看到这10个字，就能感受到触电般的危机。这根本不是允许被讨论问题，这个问题被“边防战士”、“烈士鲜血”、“一点都不能少”，以及《反分裂国家法》和《英烈保护法》等结界魔法重重包围。你的理性在被自我审查后即告停止。

因此，你目睹中国人的网络讨论，就明白了。他们使用的不是理性，而是魔法，他们讲出的不是有逻辑的话，而更像是一些咒语。只要在一句话里涉及意识形态词汇，加上“本质”、“民族情感”、“基本良知”、“资本家”一段煽动性的话语就完成了。这种魔法的场域，背后由权力用大量金钱与人力，由网信办、公安局、国安局、中宣部等部分密密麻麻编织的权力之网结成。在这个场域里，你不需要使用智商，你需要的更多是背诵。这决不仅仅对于社会，对于政治环境和官员也是一样，当他可以不以理性和奖惩施加治理，而是依靠政治忠诚、惩罚体系完成治理，自然他的生活也就远离了智商，而需要靠背诵和咒语。多看看中国官员面对新闻媒体的反应，你肯定明白我在说什么。

权力天然反对理性，因为如果理性良好运转，那么理性便成为了权威，权力作为权威的构造，很大程度上就是依靠“不合理”，我能让人接受不合理的命令，颁布不合理的禁忌，发放不合理的奖励，这就是权力的逻辑。如果一个人决心玩这个游戏，玩这场被权力塑造的对错、关注度、流量、风险的游戏，他必须放弃智商和理性，学会熟悉这些咒语和结界。久而久之，这个人也就发生了根本的改变。不必高估自己的决心和自控力，能用魔法轻松完成的事情，我们大概都不会动脑子。大学里的正常学者为什么理性能力都很强，因为几百上千个同行都等着用“同行评议”挑你的刺，看你的笑话。你不用120%的脑力，早就被戳破脊梁骨。

所以权力一旦形成任何环境内聚的场域，这个场域自然就让人少动脑子，智商下降。祝大家找到开放性的，迎接足够挑战的场域，让你不能依靠任何词汇的“天然好坏”，连“理性”和“科学”和“客观”都不天然正确的环境，必须依靠细节的说理传达你的观点，这让你可以多一些智商，也能够走得更远。 
#+END_QUOTE\