:PROPERTIES:
:title: readwise/23｜对冲思想：这个世界上有稳赚不赔的生意吗？
:END:

* metadata
:PROPERTIES:
:author: [[geekbang.org]]
:full-title: "23｜对冲思想：这个世界上有稳赚不赔的生意吗？"
:category: [[articles]]
:url: https://time.geekbang.org/column/article/414528
:tags:[[gt/程序员的个人财富课]],
:image-url: https://static001.geekbang.org/resource/image/22/9e/222bd1ebed18fe600c213bcda1b9dc9e.jpg
:END:
* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-04-11]]
#+BEGIN_QUOTE
今天我要介绍的“对冲思想”，就是来解决你的这个疑虑的。这种投资思想，通过同时持有一组对主要风险因素具有反向暴露的不同标的，来降低或消除投资组合的整体风险。这一讲，我会和你一起看下怎么具体运用它规避风险，更稳健地进行投资。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
阿尔弗雷德找到了这种方法。他创造性地设计出了一种对冲结构，也就是在卖出一组烂股票的同时，买入相同金额的一组能够代表大盘的好股票。在这样的对冲架构下，如果股票指数（下面简称为“股指”）出现了短期快速的上涨，那么他多头组合（做多的股票组合）那一边赚取的盈利，就可以挪过来弥补空头持仓上的亏损，这样就不会爆仓了；反过来说，如果股指快速下跌，那他在空头持仓上就会产生大量盈利，可以用来弥补多头组合上的亏损。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
运用了对冲思想的股票组合，成功的关键就在于投资者选股的能力：想要盈利，你选的烂股票就要在下跌时比大盘下跌得更猛烈，选的好股票要能在上涨时比大盘涨得更多。就是基于这样的对冲思想，阿尔弗雷德管理的基金从 1949 年到 1968 年，累计回报率达到了惊人的 5000%，他本人也被称为“对冲基金之父”。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
经典的对冲组合 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
案例一：配对交易

可以用一句话来概括配对交易这种策略的基本逻辑：两个基本面非常接近（所属行业相同，行业地位相当）的公司，它们的股票价格应该有“均值回复”的特征。什么叫均值回复呢？放在这里，就是说这两个公司的股价在长期来看，应该维持在一个很稳定的比值之上。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
案例二：索罗斯的宏观对冲基金狙击英镑的故事 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
案例三：对冲思想在私募基金行业的应用 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
我想讲的第三个例子是对冲思想在私募基金行业的应用。这里面最经典的应用，就是号称能够不受市场波动影响，同时回撤极小、盈利稳定的“市场中性基金”。

市场中性就是对冲掉市场波动的意思。中国市场上的市场中性基金的投资组合一般由股票多头组合和股指期货空头构成，并且股指期货空头的市值跟股票多头市值相等。这样，市场整体波动在股票多头产生的盈亏就恰好与它在股指期货空头产生的盈亏大小相等，方向相反。

市场中性基金的这一特点，就使组合整体收益对市场波动免疫，只赚取纯净的股票多头组合的超额收益。下面是市场中性产品的收益结构：

股票多头：指数收益 + 超额收益

股指期货空头：-100%×指数收益

产品整体收益：超额收益 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
这些私募基金一般会基于这些量化选股模型，开发两种类型的基金产品：一种是指数增强型产品，目标是持续跑赢指数：在大盘指数上涨的时候，比指数涨得多；在大盘指数下跌的时候，比指数跌得少。但它的缺陷是，要承担和大盘指数同样量级的波动或回撤。另一种是市场中性型产品，也就是我们常说的量化对冲型基金。

这两种基金的股票组合本质上是一样的，区别就在于是否做了对冲。采用对冲的市场中性产品，会通过做空股指期货的操作，来对冲掉市场风险。下面这幅图中我就给出了一家真实的量化私募机构的这两种产品，它们的底层都是同样的一套选股模型，区别就在于是否做了对冲。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
听我们这门课的同学，大部分都是在 IT 领域工作的程序员。程序员们的收入水平当然是跟 IT 行业的发展密切相关的。每个行业的发展，都受到市场大环境、国际关系，甚至经济发展客观规律的影响。你可能会有这样的危机感：如果 IT 行业发展不好，在未来的某一天，我收入水平大幅下降怎么办？

其实这个问题，我们就可以利用今天的对冲思想来解决。比如，我们可以把自己的一部分理财资金用来做空购买纳斯达克指数，它代表了美国市场上的科技股。这笔钱就相当于你的一笔行业保险。当科技行业整体下行的时候，这可是一笔“保命钱”，让行业问题不至于大幅影响你的家庭财富。这样，就通过对冲的做法规避掉了行业风险。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
在房价问题上，我们也可以用对冲思想去处理。很多同学看了谈买房的12 讲 后，在评论区里留言：我也清楚，如果不买房的话，就抵御不了房价进一步上涨的风险，但实在是买不起啊。这个时候，对冲思想就又可以派上用场了。就算买不起房，但我们总归买得起一些房地产的产业基金吧？只要把自己资产的一部分配置到房地产的行业基金里面，就相当于一定程度上对冲掉了房价上涨的风险。

最后，再举一个职场选择的例子。我知道，很多同学会纠结于如何规划自己的职业生涯，觉得无论怎么选，都会浪费一些宝贵的机会。这个时候，我们还是可以用对冲思想来看这个问题。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
对冲思想，是一种通过同时持有一组对主要风险因素具有反向暴露的不同标的，来降低或消除投资组合整体风险的投资思想。

对冲思想诞生于 1949 年由阿尔弗雷德·琼斯管理的对冲基金。

经典的对冲策略包括配对交易、宏观对冲和市场中性策略等。

在市场中性策略的例子中我们看到，进行对冲掉市场风险的操作后，可以把产品最大回撤降低到 5% 以下，让净值曲线从波动上升变成稳健上升。这证明对冲思想确实能改造投资策略的风险收益特征。

对冲思想的应用是非常广泛的，你可以灵活地运用对冲思想，来规避财富管理道路上的风险。 
#+END_QUOTE\
** 📌 [[2023-04-12]]
#+BEGIN_QUOTE
我更多轮动策略。比如历史两个收益差不多的主动基金，一个近期长的特别好（广发稳健），一个近期特别一般（南方成长），我就会调仓，卖出涨的好的，换到最近不行的上面。 还有种对冲就是买，相关性低的标的。这里举个选老婆时候，看重工作的故事。 我是技术男，相当于前期收益高，涨幅高，波动大，风险大 类似于股票资产。而我更希望找个 公务员，老师，医生，类似债券，收益一般，涨幅一般，基本无风险，稳定。所以我找了个医生当媳妇，给整个家组成了类似股6债4的资产组合。对冲了医生前期收入不高的风险，也对冲了我40以后技术男中年危机的风险。 还有一种小概率长尾风险，比如意外疾病，这就靠保险为全家保驾护航了。夫妻两个要配齐，重疾，人寿，医疗，意外。老人要配齐医疗，意外。消费险就好，别陪分红万能险深坑。

作者回复: 哈哈，非常系统地家庭组合 
#+END_QUOTE\