:PROPERTIES:
:title: readwise/Vc视角香港参会小作文（充满偏见）： 1️⃣....
:END:


* metadata
:PROPERTIES:
:author: [[dov_wo on Twitter]]
:full-title: "Vc视角香港参会小作文（充满偏见）： 1️⃣...."
:category: [[tweets]]
:url: https://twitter.com/dov_wo/status/1777003404621177150
:image-url: https://pbs.twimg.com/profile_images/1608376439002529792/GOxrlbBF.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-04-08]]
** 📌 [[2024-04-08]]
#+BEGIN_QUOTE
VC视角香港参会小作文（充满偏见）：

1️⃣. 牛市产品不重要，叙事和情绪更重要。meme已经在反复反复证明这一点。融资的钱至少一半拿来拉盘

2️⃣.  本轮牛市最核心的能力：操盘能力和喊单能力。如果你没有操盘能力，请去练习喊单能力，我也在帮一些项目方找KOL做推广，欢迎来接我给的商单。有很多binance、OKX都投了的项目找不到合适的国内/海外推广渠道，虚假繁荣/买盘就是刚需。

3️⃣. VC的地位越来越差，解锁慢、估值高，散户不认。如果不能给项目方带来额外的资源（如交易所关系、某特定地区的资源和社区、经济模型设计、推广能力等），大部分纯财投VC只能当大怨种。

拿最近找我的某个项目举例，给KOL轮的额度估值比VC还低，且解锁比VC还好。（本项目由西方某顶级VC领投）

KOL > VC不是空穴来风，是真实存在的。所以我也在做一个小的精品的KOL agency来卖卖铲子。

4️⃣. 最火的活动是bera chain、solana、BTC；ETH生态相对不太活跃，很大的一个meme梗为layer 69（solana自己拍的搞怪恶搞eth的视频）

5️⃣. Side Event人非常多，这次活动可能有几百场Side Event。反而主会场没有什么人；项目方们或许需要反思昂贵的主会场展台是否还值得；比如berachain、solana都是没有主会场展台的，而是自己办活动。OKX是展台活动全都有，最顶级状态，反观币安继续是一个活动没有。

6️⃣. 普通人一定要当KOL，找好自己的定位，比如喊土狗就只喊土狗，好好做分析就好好做分析。都能接到不错的商单的。我找喊土狗的KOL喊单，每条价格从200U-2000U不等。不会喊单的VC活不下去，不会喊单的KOL赚不到钱。你有流量，会有大量的项目方主动找你合作，你会有更好的信息和更多的资源。请再看一遍第二条。质疑带单老师，理解带单老师，成为带单老师。

7️⃣. 今年hk聊合规、牌照的少了，聊操盘和攒资源多了（也可能是因为我走到了更高的阶段能听懂和参与了）。主会场一进门最大的是OKX和DWF的展台，谁有资源和谁有钱大家都知道了吧。 
#+END_QUOTE\