:PROPERTIES:
:title: readwise\硅谷对“快速行动，打破常规（move Fast...
:END:

:PROPERTIES:
:author: [[dotey on Twitter]]
:full-title: "硅谷对“快速行动，打破常规（move Fast..."
:category: [[tweets]]
:url: https://twitter.com/dotey/status/1732591351487676695
:image-url: https://pbs.twimg.com/profile_images/561086911561736192/6_g58vEs.jpeg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-15]]
** 📌
#+BEGIN_QUOTE
硅谷对“快速行动，打破常规（move fast and break things）”理念的新演绎

\- 硅谷出现了一个新的流行口号。
- 这句口号最早是 Sam Altman 在 2021 年提出的，但近期被许多重要人物频繁引用。
- Altman 的这一观点，让人联想到 Mark Zuckerberg 曾经的口号：“快速行动，打破常规”。

硅谷虽然还没有完全摒弃它的 “快速行动，打破常规” 思维模式 — 但它现在有了一个更贴合 AI 时代的新口号。

早在 ChatGPT 面市之前，Sam Altman 在 2021 年就在推特上写道：“行动要更快。任何地方的慢动作都能成为其他地方拖延的借口。选择 2021 而不是 2022，选择这周而不是下周，选择今天而不是明天。快速行动的效应远超过人们的想象。”

Altman 在这条推文之后再次发文，强调在快速行动时需要“极其深思熟虑”。

虽然他当时可能并未预见到 AI 将如何改变世界，但接近三年后，Altman 的这番话在科技圈依旧广为流传。

这种对速度和创新的强调，如同他的话所示，受到了众多创业者和 CEO 的欢迎，在像 X（原 Twitter）这样的平台上引起了广泛关注。

Vercel 的 CEO Guillermo Rauch 在去年 11 月对 Altman 的推文作出回应，表示：“我经常思考这个问题。这应该成为你的默认工作方式。”

这种观点在随后的去年关于 OpenAI 的 Microsoft 内部备忘录中也得到了呼应，据《纽约时报》报道。

Microsoft 的高级执行官 Sam Schillace 在 ChatGPT 发布后写给员工的信中说：“速度比任何时候都更重要。”他表示，在这个时刻担心那些可以稍后解决的问题将是“绝对致命的错误”。

Altman 的观点和实践方式，让人想起了 Mark Zuckerberg 那个著名的口号：“快速行动，打破常规”。这一硅谷口号由 Facebook 在其早期推广，象征着硅谷快速创新、颠覆和热情的精神。

这种工作方式强调速度和实验，几乎不考虑任何可能的负面后果。对于 Facebook，现在的 Meta，这些后果包括用户隐私问题、安全问题和意外的社会影响。

面对一系列丑闻，这家科技巨头后来将这句口号修改为“快速行动，拥有稳定的基础设施”，试图表达出对更负责任的进步方式的认识。

如今，在 AI 领域的竞争激烈之际，科技界再次聚焦于速度和迅速推出产品。

Altman 此后也发表了类似的评论。

他说：“在创业公司中，动力就是一切。”“成功的初创公司会继续成功，而失败的公司则会继续失败。”

Altman 所领导的 OpenAI 凭借其 AI 驱动的聊天机器人 ChatGPT 取得了巨大成功。这款机器人的空前受欢迎程度令 Google、Meta 和 Tesla

等大型科技公司感到震惊。

Microsoft 对这家 AI 实验室的大笔投资和紧密合作激发了其老对手的竞争热情，尤其是 Google。在 ChatGPT 发布后，科技界的焦点从之前的稳健 AI 发展转向了快速推出产品的激烈竞争。

然而，正如 Zuckerberg 的口号忽略了一些紧迫问题，各大科技公司急于推出不可预测的 AI 驱动产品，也导致了一些尴尬的失误。

ChatGPT 的第一版远非完美，在最初几周里就被发现产生了种族主义和性别歧视的内容。

它也很容易被技术娴熟的用户轻松破解。其中一种方法就是让聊天机器人忽略其内容审查。

Microsoft 急于在 Google 搜索方面取得优势，推出的AI 驱动的 Bing一开始就相当令人不安。在 Google，该公司首次公开展示其 ChatGPT 竞争对手 Bard时，也犯下了一个令人尴尬的错误。

这两家公司产品中的失误凸显了围绕这项技术的一系列严重问题，包括 AI 偏见、安全性和误传信息的风险，但两家公司都不急于放慢开发步伐。

Zuckerberg 的 “快速行动，打破常规” 口号可能在 Meta 的 2019 年剑桥分析丑闻之后被宣布终结。

考虑到当今的大型 AI 参与者们仍在加速开发，尽管对其快速步伐存在越来越多的担忧，我们不得不怀疑，硅谷似乎并没有从过去的错误中吸取教训。

转译自：Silicon Valley has a new version of its beloved 'move fast and break things' mantra
 https://t.co/u3nlVZb8nb 
#+END_QUOTE
    date:: [[2023-12-07]]
*** from _硅谷对“快速行动，打破常规（move Fast..._ by @dotey on Twitter
*** [View Tweet](https://twitter.com/dotey/status/1732591351487676695)