:PROPERTIES:
:title: readwise/今天中国统计部公布cpi和ppi数据。基本上没有...
:END:


* metadata
:PROPERTIES:
:author: [[Alex_perception on Twitter]]
:full-title: "今天中国统计部公布cpi和ppi数据。基本上没有..."
:category: [[tweets]]
:url: https://twitter.com/Alex_perception/status/1722595055800881607
:image-url: https://pbs.twimg.com/profile_images/1692350922599596032/Hz0cOlcE.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-20]]
** 📌
#+BEGIN_QUOTE
今天中国统计部公布CPI和PPI数据。基本上没有什么意外的两科全挂了，现在的情况其实没有什么好奇怪的更没有什么好争论的。如果说我再加上点背景，许多人都在说中国统计局为了让数据好看而修改数据，这点绝大部分门内的人都清楚，但即便是下功夫修改之后却依旧是这样，足可见实际可能比我们想象的更深。另外，其实很多身边的案例就可以反映出现实状况，大家其实可以仔细留意一下身边的商业的变化，从我的视角来看现在的衰退是很明显的，当然我就不拿餐厅，商场之类的举例子了，这些现象但凡还出门都应该能看到。

众所周知PPI作为CPI的部分上游，对于工业生产出厂价格而言，环比是挂零，同比是负数，去年整体基数可不算高，即便如此同比依旧是负数，这就是很说明问题了。至少现在PPI项下的品类整体都是严重衰退，关键的问题这个同比数据在统计局给的列表中从去年到今年全是负数啊。
工业生产者购进价格也是一样的基本全都挂科了（除了有色金属材料和电线类价格上涨3.7%），这也在说明上游垄断要素的国央企也无法向下传导加价了。终端需求急剧萎缩已经承受不起了。

这次的CPI更是没什么可争的= =本身从今年4月开始同比已经下降至0.1%了，环比在2月就进入负数了。有人提到10月猪肉价格大降拖累CPI，但是10月正好是过长假，这种秋日天的节日正是吃喝的好时节，我记得国庆的时候我发过几个帖子讲了国庆期间惨淡的消费数据，这不正好对上了吗？

这次数据确实没什么好解的，该说的早就说过很多次，这点大家可以翻看我的帖子记录，直接搜索往期相关分析即可。在整个消费结构里，通常的主力军是以下层+中层为主，上层人是有钱但是再怎么能吃能造，生活上的事儿也花不了多少钱，更何况这样的人太少了。中国的问题在于底层太穷，前总理李克强在2020年两会后的记者会上说过中国有6亿人每个月的收入也就在1000元，再叠加上中国很多伪中产，即如果抛去所持有的房子净现金流根本到不了中产水平，大家要想明白自己的住的房子再值钱，只要不卖掉或者出租掉它不产生现金流，而这些人的日常消费则来自于其现金流，而且如果是依靠租赁房屋获益的群体，那么问题是在经济衰退的当下租金并不会再随着通胀紧密上涨了，甚至一些区位优势差的地方早就开始出现降价的现象了。

很多时候解读经济是不困难的，解读数据最怕的是一直在数据里待着，其实出去走走看看并不是很困难，在中国人丰富且漫长饮食观念下，大家多去看看人们怎么选择吃饭，再跟自己以前的记忆对比一下，其实很多争论都是没有意义的。另外我相信那些商业综合体中关闭的店铺也十分能说明问题，换位思考一下，对于一个经营多年的商家而言，关门是个非常艰难的决定，这意味着多年的经营积累的名誉和客源会损失不少，若非万不得已谁会选择闭店？

今年初的时候我认为这种能被普通人看见的衰退应该发生在明年2-3月，但没想到的是提前到了今年10-11月就出现了。往后日子只能是越来越差，中国内部有两个问题，一个是个人和企业债务负担较重，这俩正是创造财富的部门，让企业和居民部门负重前行的结果就是，即便现在有点钱也不会大手大脚的花，因为还有债务啊。而如果没法放开手脚花钱，就没有办法重新开启企业-居民的财富创造循环。第二是政府利用通胀从居民手中转移购买力去投资，关键是现在基建的效益已经快等于0了，这种模式不但解决不了问题反而是加剧衰退的根源。现在即便中美，中欧恢复了一些关系，但在消费国们自己还未恢复的当下又能贡献多少消费？关键大家都知道恢复关系是不可能的，产业链多元化战略的实施是有成本的，对方已经开始实施就代表部分订单是不可能再回来的了。内需不断被阉割，产业部分转移，外需也跟着转移了一部分，这种情况下经济根本是没法恢复的。 
#+END_QUOTE
    date:: [[2023-11-11]]
*** from _今天中国统计部公布cpi和ppi数据。基本上没有..._ by @Alex_perception on Twitter
*** [[https://twitter.com/Alex_perception/status/1722595055800881607][View Tweet]]