:PROPERTIES:
:title: readwise/ChatGPT Is Getting 65 Mi...
:END:


* metadata
:PROPERTIES:
:author: [[moritzkremb on Twitter]]
:full-title: "ChatGPT Is Getting 65 Mi..."
:category: [[tweets]]
:url: https://twitter.com/moritzkremb/status/1665343897957203968
:image-url: https://pbs.twimg.com/profile_images/1679831685985075202/rmC9eVnN.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
ChatGPT is getting 65 million visits per day.

But almost everyone's STUCK in beginner mode.

Here are 10 threads to level up from ChatGPT beginner to expert: 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
1/ Learn the basics: This will help you understand the different types of prompts. 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
2/ Brainstorming is ChatGPT's strongest capability. Master it. 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
3/ ChatGPT is a language model. It excels at helping you write better. 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
4/ Teach ChatGPT to write like you and take your content creation to the next level. 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
5/ Speed up your content creation with these techniques. 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
6/ A heavily underestimated skill of ChatGPT: Text formatting. 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
7/ Use ChatGPT as your coach for everything. In this example: Negotiation coach 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
8/ Study these powerful marketing prompts 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
9/ Everyone needs these effective sales prompts. 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
10/ Prompts that will increase your productivity 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
If you enjoyed this, you'll love my weekly newsletter.

My mission is to transform you into an AI prompt expert, by providing:
· valuable tips
· powerful secrets
· unconventional hacks

Join 5800+ subscribers here:
https://t.co/v4w5hJGsLL 
#+END_QUOTE\
** 📌 [[2023-06-05]]
#+BEGIN_QUOTE
Thanks for reading!

I hope you've found this thread helpful.

If you did, I'd really appreciate if you would:
1. Follow me @moritzkremb for more.
2. Like/Retweet the tweet below to share it with others: 
#+END_QUOTE\