:PROPERTIES:
:title: readwise/这两天没看书，熬夜把《大明王朝1566》看完了，...
:END:

:PROPERTIES:
:author: [[Pandazhq on Twitter]]
:full-title: "这两天没看书，熬夜把《大明王朝1566》看完了，..."
:category: [[tweets]]
:url: https://twitter.com/Pandazhq/status/1685736934881026048
:image-url: https://pbs.twimg.com/profile_images/872021763839803392/drXxtmlB.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-18]]
** 📌
#+BEGIN_QUOTE
这两天没看书，熬夜把《大明王朝1566》看完了，的确是神剧，且与中国政府当下的财政困境特别相符。

电视剧是从内阁年底算账开始的，所有的账算下来财政亏空了几百万，为了补亏空就开始在浙江推行“改稻为桑”，但是农民不愿意，推行很艰难。

为了尽快推行，端午节暴雨时，地方官员授意官兵掘开前一年刚 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736934881026048)
** 📌
#+BEGIN_QUOTE
这两天没看书，熬夜把《大明王朝1566》看完了，的确是神剧，且与中国政府当下的财政困境特别相符。

电视剧是从内阁年底算账开始的，所有的账算下来财政亏空了几百万，为了补亏空就开始在浙江推行“改稻为桑”，但是农民不愿意，推行很艰难。

为了尽快推行，端午节暴雨时，地方官员授意官兵掘开前一年刚 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736934881026048)
** 📌
#+BEGIN_QUOTE
修的防汛堤坝，要把那些不愿意种桑的稻田全淹了，那么农民受了灾必然会低价卖田活命，做政府生意的大商人，再通过远低于市场价的价格，买下受灾稻田来种桑。这样一来地方政府就可以在极低成本下，完成50万匹丝绸的任务，进而填补中央财政的亏空。

但是呢，这个事儿被派到淳安当知县的海瑞联合胡宗宪给 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736936470679552)
** 📌
#+BEGIN_QUOTE
搅黄了。不但改稻为桑推行不下去，还把浙江高官和江南织造局给办了。

浙江巡抚和布政使是严嵩的人，江南织造局是首席大太监吕芳的人。与此同时，浙江福建沿海又有倭寇进犯，国库却空空如也。为了补充前方用度，政府抄了浙江首富沈一石的家。人人都算计着从首富家里至少能抄上千万两银子，够打仗用一段 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736937808621568)
** 📌
#+BEGIN_QUOTE
时间了，可是抄完才发现沈一石的钱都肥了各级政府官员，除了一堆堆账册也就几万两银子，根本不够打仗用。

看到这里我就想起曾经的首富许家印和恒大的2.4万亿债务，这2.4万亿债务里当然有上下游供应商的钱，又有多少是送给地方官员的呢？恒大如果从一开始就破产清算，得牵扯多少地方官员啊。可以，到现 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736939138220033)
** 📌
#+BEGIN_QUOTE
在为止，却不曾有一个官员因恒大而倒下，足见牵扯的官员不是没有，而是太多。

抢了浙江首富没弄到钱，又查抄了浙江巡抚和布政使，钱还是不够，又开始巡盐。盐作为政府专营，一直是税收的大头。但严嵩一手提拔的鄢懋卿，一去江浙就收了500多万两，但他跟严嵩贪了近两百万两，运到北京的只有330万两。得 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736940333645824)
** 📌
#+BEGIN_QUOTE
知他们如此疯狂贪污，且抗倭战事告一段落后，嘉靖帝终于开始筹备倒严。

倒严后民间饥荒需要钱，前方战事需要钱，各级官员欠得薪水需要补上，嘉靖帝修宫殿也需要钱。本来内阁的账本里没有修宫殿的钱，其他各项算下来勉强够用，但嘉靖不答应。所以内阁不得不从饥荒、欠俸、前方粮草里匀出150万两给嘉靖 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736941705142272)
** 📌
#+BEGIN_QUOTE
修宫殿。

后来宫殿修好了，文官却大规模闹起事儿来，北京周边也饿殍遍地，嘉靖还逼迫所有官员必须为他搬迁宫殿写贺表，否则谁都做不了事，然后就有了海瑞痛骂嘉靖的檄文。

我觉得它是神剧，不是因为海瑞如何抨击时弊，而是导演如何通过故事来展现集权帝制的制度性弊端。

这种逆淘汰制度，不是换个皇 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736942980190209)
** 📌
#+BEGIN_QUOTE
帝或出个清官就能改变的，也不是有多少个理想主义者能改变的。

每一次嘉靖帝在皇宫里发狂的时候，导演都在暗示观众，皇帝（最高权力）需要一个笼子，一个非常结实的笼子。只是没有人知道，这个笼子到底在哪里。所以他就一直在发狂，折磨自己也撕咬别人，直到帝国崩溃时…

剧里有很多细节也很有意思， 
#+END_QUOTE
    date:: [[2023-07-31]]
*** from _这两天没看书，熬夜把《大明王朝1566》看完了，..._ by @Pandazhq on Twitter
*** [View Tweet](https://twitter.com/Pandazhq/status/1685736944699863040)