:PROPERTIES:
:title: readwise/科技爱好者周刊（第 285 期）：为什么 PPT 不如备忘录
:END:


* metadata
:PROPERTIES:
:author: [[ruanyifeng.com]]
:full-title: "科技爱好者周刊（第 285 期）：为什么 PPT 不如备忘录"
:category: [[articles]]
:url: https://www.ruanyifeng.com/blog/2024/01/weekly-issue-285.html
:image-url: https://readwise-assets.s3.amazonaws.com/static/images/article2.74d541386bbf.png
:END:

* Highlights first synced by [[Readwise]] [[2024-01-12]]
** 📌 [[2024-01-12]]
#+BEGIN_QUOTE
那么，为什么一定要当事人提交六页的备忘录，而不是现场主讲 PPT 呢？

贝佐斯说，**书面的备忘录要比 PPT 演示，效果好得多**，主要有以下几点原因。

（1）PPT 的设计目的是说服，这是一种销售工具。但是在公司内部，你想要的是真相，而不是业务主管的推销。

（2）PPT 的缺点是，它对作者相对容易，对观众来说却很难抓住要点。备忘录正好相反，写好一份六页的备忘录，对于作者是很难的。

你可能需要两周的时间，先写出初稿，然后再重写，不断加工，确保你的文字是准确和可靠的。所以，备忘录对作者非常困难，但对观众就好多了，半小时的阅读就能搞清楚事情的来龙去脉，也看得出作者对这个问题的熟悉程度。

（3）备忘录可以节省会议时间。如果是 PPT 演示，高管们会不停地打断提问，结果发现答案就在下一张幻灯片。

但是，阅读备忘录时，你必须先把所有问题写在空白处，当你读到最后一页时，发现很多问题已经得到了解答，这就节省了当众提问的时间。

（4）PPT 演示过程中，主讲人也许会根据现场情况，临时决定隐藏或修改一些讲法。备忘录就没有这个问题，主讲人必须事先给出完整描述，你更能了解他的真实想法。

（5）PPT 通常只是一些要点，不是完整的句子，有利于隐藏很多草率的想法。而备忘录是完整的段落，必须有主题句，有动词和名词，你很难隐藏自己的草率思维。

备忘录迫使作者处于最佳状态，你能得到一个人真正最好的想法。如果 PPT 演示，你们可能要讨论很久，发言人才能进入最佳状态。从长远来看，备忘录节省了你的时间。

以上就是贝佐斯不允许使用 PPT 的五点理由。 
#+END_QUOTE\