:PROPERTIES:
:title: readwise/《未来十年的投资组合建议实践篇》 *此推文为超...
:END:


* metadata
:PROPERTIES:
:author: [[erchenlu1 on Twitter]]
:full-title: "《未来十年的投资组合建议实践篇》 *此推文为超..."
:category: [[tweets]]
:url: https://twitter.com/erchenlu1/status/1690182200808124416
:image-url: https://pbs.twimg.com/profile_images/1416598932952596480/xP1YukEz.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-26]]
** 📌 [[2023-12-25]]
#+BEGIN_QUOTE
《未来十年的投资组合建议实践篇》

*此推文为超长文，建议先收藏，再阅读

普通人一定要手握能够至少穿越下一个10年的资产/投资品。

这些资产和投资组合应当具备多样性，涵盖不同属性和类型，跨足多个领域和维度，以应对未来十年中可能出现的各种情况。

无论是最理想的情形，如和平，还是最糟糕的情形，如中美脱钩或战争。

房产：

在大城市核心城区，至少应保留1-2套房产。

即使经济状况不佳，房价开始下滑，但大城市核心地段的房产仍然被视为相对稳定的投资选择，具备较强的保值和抗跌能力。

此外，长期来看，至少在中国的近代历史周期内，大城市核心地段的房产往往表现优于大多数A股股票。

除了这一点，这些地段房产出租带来的租金，还能为普通人提供被动收入和稳定的现金流，为个人带来持续的经济安全感，从而避免陷入极端焦虑和困境之中。

股票：

美国的指数基金，指数基金，指数基金，重要的事情强调了三遍，而且需要将它们作为自己投资组合中的重要部分。

这是一个长期以来一直被我反复谈论的话题。

以标普500指数基金为例，在10年至15年的投资时段内，它能够胜过95%的由基金经理管理的主动大型基金，不论是涉及对冲、量化、alpha、beta，还是其他种种复杂的基金策略。

对于持有海外银行账户的投资者，可以通过美国券商购买标普500指数基金/ETF。

其中规模较大的一个选择是VOO（Vanguard S&P 500 ETF），其管理资产规模高达数千亿美元（相当于数万亿人民币）。

而对于没有海外银行账户的投资者，也可以通过支付宝购买以人民币计价的跟踪标普500指数的基金。

购买过程非常简单，只需在支付宝基金页面搜索标普500即可。

在美国公司股票方面，特别值得关注的是微软和特斯拉。

在这次LLM大语言模型革命的生态圈中，微软扮演了极其重要的角色。

例如，开发了引领革命的ChatGPT的OpenAI背后，有微软的投资支持。

除了ChatGPT，微软的生态圈中还孕育着其他AI应用，如Copilot等。

这些AI应用在未来将融合到微软旗下的软件/应用生态中，例如Bing、Word、Powerpoint、Excel、Teams、Skype、Github等。

微软在OpenAI公司内享有分红权。

在第一阶段，微软享有整个公司75%的分红权，这一比例将持续到获得130亿美元的投资额；

在第二阶段，微软的分红权将降至49%。

随着时间的推移，微软的生态圈价值无疑将继续增长。

关于特斯拉，未来应当关注马斯克旗下其他公司的Boring地下隧道与特斯拉汽车的深度整合，以及Cybertruck、特斯拉机器人（Tesla bot）等产品的发布与不断迭代。

特斯拉人形机器人一旦成功大规模量产并持续优化，有望将特斯拉打造成全球最大的机器人公司。

这一产品的推出将颠覆现有的劳动力市场和劳动成本格局。

此外，随着特斯拉无人驾驶技术的成熟，其未来还有可能进军无人配送物流领域，这一趋势同样值得密切关注。

中概股方面：我只推荐瑞幸咖啡。

关于具体的投资逻辑，我已在2022年初在我的同名公众号（卢尔辰）发表了3篇和4篇的分析文章中详细阐述并进行了预测。

自那时以来，瑞幸咖啡股票已经实现了超过150%-200%左右的上涨（印证了我的预测和判断）。

有兴趣的可以阅读下：

https://t.co/n7uJvqtK5J

记住，即使中美之间未来不发生冲突，两国之间的高科技领域的制裁和限制也会是大趋势。

瑞幸咖啡这类消费品，可以完美的避开中美科技领域大制裁的影响。

区块链：

比特币：

比特币是当代的数字黄金（digital gold)，不仅具有高度的稳定性和稀缺性，而且共识性也随着时间慢慢递增。

每一次央行印钞机的开动，都会让更多的人意识到比特币的价值。

传统黄金存在一个显著的不足，即难以大量携带，尤其是跨境移动。

而比特币作为数字黄金，完美地解决了这一难题。一把私钥在手，你可以轻松地携带BTC在全球任何地方自由流动。

以太坊：

如果比特币是黄金，那么以太坊在某种意义上就是新时代的“能源”。

无论是DeFi, NFT, GameFI, 转账，还是新智能合约的生成， 都需要燃烧“以太坊”。

以太坊在区块链世界中的重要性，类似于人类对于电等能源的依赖性一样高。

以太坊在转PoS之后，质押以太坊作为验证节点的人，可以享受大概3-5%的年化收益，这标志着以太坊成为了类似于互联网债券（internet bond) 的资产。

其意义非常重大，《富爸爸，穷爸爸》里有个经典语句：“资产”是让钱为你工作的事物。而“工作”则是你为钱而工作。 ​​​

一定要意识到，比特币和以太坊都是人类物质文明级别的创新，类似于古腾堡的活字印刷技术。

传统避险资产：

黄金：

黄金作为一种硬通货，已经存在于人类社会中数千年，经历了多个时空的考验，成为少数几种历史悠久的资产之一。

直至今日，不论是美国、中国还是俄罗斯，都将黄金视为国家战略储备的一部分。

黄金因其卓越的稳定性、可塑性和珍贵性而备受推崇，成为机构和国家之间不可或缺的坚实储备。

即便在战乱时期，黄金仍然是首选的避险资产之一。

普通人可以购买黄金实物 或者法制健全稳定国家的黄金ETF。 
#+END_QUOTE\