:PROPERTIES:
:title: readwise/昨晚和一位设计师朋友喝咖啡，聊聊设计协作的问题。...
:END:


* metadata
:PROPERTIES:
:author: [[5key on Twitter]]
:full-title: "昨晚和一位设计师朋友喝咖啡，聊聊设计协作的问题。..."
:category: [[tweets]]
:url: https://twitter.com/5key/status/1688021208389054464
:image-url: https://pbs.twimg.com/profile_images/1177924061596225539/wLC8H298.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-20]]
** 📌
#+BEGIN_QUOTE
昨晚和一位设计师朋友喝咖啡，聊聊设计协作的问题。想起之前在专栏里写过的一段话，算是这些年折腾设计协同产品的一些感受吧。

1. 识别问题，远比捣腾工具有效
有些时候我们会因为某一款新工具（或个功能）而产生想要一些对工具自研的“幻想”。但这些想法往往只是对新功能的价值的假想，而忽略了团队中真实需要解决的问题。

所以，不要急着有了新想法就往里扎。先好好思考一下它是不是一个真需求。

2. 工具不一定要自己造，选择一个合适的先开始
我们经常会陷入到个性化需求的“陷阱”中，总想着针对性的为自己争取资源定制开发。这样往往会陷入大量的时间和资源的消耗，而且未必能达到预期的效果，最终可能给自己埋下一个又一个坑。

所以，不妨先挑选一个合适的工具先进行尝试，等到摸索出一段时间，验证后再考虑自己研发。

3. 与上下游达成一致，不要自嗨
协同不仅仅局限在团队内，更重要的还有上下游的相关人员。在探索协同效率的时候一定不要沉浸在自己的世界里，先将想法和上下游相关的同学聊一聊。

相信我，没有上下游的支持，自己搞设计协同是玩不转的。

4. 不要盲目改进，给自己制定一个目标
协同的目的是为了提升效率，这就意味着我们需要有一个明确的可衡量的目标，否则我们很容易陷入盲目的改进和迷失方向。

一定要先给这件事情定义一个清晰且有意义的目标（无论是定量还是定性），通过设定目标来持续监测改进的效果，并根据实际的情况进行调整和优化。 
#+END_QUOTE
    date:: [[2023-08-06]]
*** from _昨晚和一位设计师朋友喝咖啡，聊聊设计协作的问题。..._ by @5key on Twitter
*** [[https://twitter.com/5key/status/1688021208389054464][View Tweet]]