:PROPERTIES:
:title: readwise/那么今天众多拿着 LLM 满世界找应用的人，难道...
:END:


* metadata
:PROPERTIES:
:author: [[skywind3000 on Twitter]]
:full-title: "那么今天众多拿着 LLM 满世界找应用的人，难道..."
:category: [[tweets]]
:url: https://twitter.com/skywind3000/status/1773393351217426933
:image-url: https://pbs.twimg.com/profile_images/786485788468850688/OA9vAxsy.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-04-08]]
** 📌 [[2024-03-29]]
#+BEGIN_QUOTE
那么今天众多拿着 LLM 满世界找应用的人，难道也是在拿着锤子找钉子？也是乔帮主口中的反面例子吗？是他们做错了么？还是乔帮主说错了？问题出在哪里？只能说 it depends，乔帮主的话是有先决条件的，任何一个行业发展都遵从：技术主导->产品主导->运营主导 的脉络，不同时期不同的人作用最大，贡献最大的利润率。

就像游戏行业，2000 年初会做游戏的整个广东就只有一家工作室，你想做不去找他们的人你做啥呢？2004 年能做 3D 游戏的整个华南可能找不出两个以上的团队，那时就是技术主导，所有公司名册里技术都排在最前，行业内出名的都是技术人员；

等到 2007 年以后，技术不在成为壁垒，基本都是人手一套 3D 引擎了，如何挖坑挣玩家的钱又变成了最核心的问题，于是产品成为主导；而 2011 年以后，天下玩法一大抄，游戏玩法无创新天天换皮的时候，行业又变成了运营主导的天下，谁能精细化运营，设就能赢得用户，首充号，充值返利，工会带量，渠道，棋牌游戏房卡模式，这些都不是玩法创新，而是运营和营销思路创新，而各个公司的高管也越来越多运营出生的人得到提拔，为啥？因为这时他们的工作贡献了最大的利润，业内今年成名的人再难以见到产品，更别说技术。

那么是不是所有行业的稳定态都是运营/营销主导的状态么？也不是，一旦技术/产品有创新，就又能将行业拉回到技术/产品为主导的时候，比如当年诺基亚和摩托罗拉产品创新已经枯竭了，天天都在换壳玩营销，架不住 iPhone 出来重新把行业拉到产品+部分技术主导的年代，今天 AI 技术革命，又再次将死气沉沉的互联网/IT 拉到了原点。

所以乔帮主的话也没有错，只是他这么说的时机刚好被他拉回产品主导的年代而已，而今天四处推广 AI，拿着 LLM 四处找钉子的人也没错，因为如今 AI 就是技术主导，不同职位的人在过去取得了成就，但随着时间推移，过去使他们成功的性格和技能，在今天可能让他们陷入困境；就像很多产品同学们前几年一时半会接受不了自己主导地位的下降，天天和运营吵架，就像当年程序接受不论地位下降天天和产品吵架一样。

解法无外乎两种：顺应变化，或者积蓄力量努力创新，作为技术人员，想要长久发展，可以尽量远离没有技术基因的产品和公司，或者寻求转行。 
#+END_QUOTE\