:PROPERTIES:
:title: readwise/大部分中产阶级的消费力，源自于他们对上流社会的想...
:END:


* metadata
:PROPERTIES:
:author: [[jike_collection on Twitter]]
:full-title: "大部分中产阶级的消费力，源自于他们对上流社会的想..."
:category: [[tweets]]
:url: https://twitter.com/jike_collection/status/1752885744904065365
:image-url: https://pbs.twimg.com/profile_images/985403677350346752/tw6tRCVW.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-02-06]]
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
大部分中产阶级的消费力，源自于他们对上流社会的想象力。

今早晨练听了一期播客，标题叫《贝果、酸奶碗，口味的阶级：白人中心主义下的中产想象》，里面提到了几个蛮有意思的观点，我摘录了一下。 
#+END_QUOTE\
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
培根、速食香肠、牛奶，是欧美国家在战后为了快速提升国民身体素质，才开始宣扬的饮食理念，其实论蛋白质的吸收率，有很多食物是比牛奶要强的，但是家长还是会逼迫孩子去喝牛奶，即便有些人有乳糖不耐； 
#+END_QUOTE\
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
在新西兰，几乎是一个全民健身的国家，并不是什么健康生活理念使然，单纯是健身卡便宜，低至6元一天，如今国内兴起的户外瑜伽、徒步、飞盘，在国外也是平价健身的代名词；

酸奶碗和酸奶碗上的莓果、燕麦，在国内成了轻奢、中产、健康生活的代名词，但这些东西在国外是很便宜的。

…… 
#+END_QUOTE\
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
恰好最近在写一篇关于中产消费陷阱的稿子，突然联想到一个观点，叫，中产阶级的消费力，来自于他们对上流社会的想象力。

在这个逻辑架构上，我觉得需要区分两个概念，一个叫做，中产，另一个叫做，精英。这两者之间最显著的区别在于，大部分中产在效仿，而精英会创造。 
#+END_QUOTE\
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
其实这些年国内的中产消费骗局数不胜数，除了播客里听到的这几个，我还能随手举出很多，说个最经典的吧，米其林。

作为中产小资标配的米其林餐厅，米其林出现的背景其实很有意思。 
#+END_QUOTE\
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
19世纪中期，英法率先完成工业化，而当时法国的政权制度，决定它是一个高度集权的君主制国家，所以当其他国家还在工业化的轰鸣声中灰头土脸的匍匐前进时，法国上流社会已经开始了红酒香槟的高端假面舞会。

法餐，作为配套，开始席卷西方上流社会 
#+END_QUOTE\
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
有了这个前提，你就不难理解，为什么一个法国的美食评选团，可以在全世界到处给餐厅打分，而当地消费者依然趋之若鹜多年。

回到一开始的问题，中产只会效仿，而精英会创造。 
#+END_QUOTE\
** 📌 [[2024-02-02]]
#+BEGIN_QUOTE
认为吃米其林就能跻身上流、认为学钢琴就能逆转人生、认为出国水个硕博回来就能在职场上畅通无阻，这些，其实都是一代代中产无力且狭隘的想象。

中产只会模仿，而大部分精英，已经在靠给中产造梦，完成原始积累了。这很残酷，但这就是博弈的真相。  #你不知道的行业内幕 
#+END_QUOTE\