:PROPERTIES:
:title: readwise/转译：还有什么能阻挡英伟达的老黄吗？ 他已成为...
:END:


* metadata
:PROPERTIES:
:author: [[dotey on Twitter]]
:full-title: "转译：还有什么能阻挡英伟达的老黄吗？ 他已成为..."
:category: [[tweets]]
:url: https://twitter.com/dotey/status/1774993628739313809
:image-url: https://pbs.twimg.com/profile_images/561086911561736192/6_g58vEs.jpeg
:END:

* Highlights first synced by [[Readwise]] [[2024-04-08]]
** 📌 [[2024-04-02]]
#+BEGIN_QUOTE
转译：还有什么能阻挡英伟达的老黄吗？

他已成为我们这个时代的生成式 AI 领航者

黄仁勋不仅是一个肩负使命的人，他还是一个能在自己的小故事中找到乐趣的讲故事高手。去年春天，当他的半导体公司 Nvidia 正在迅速成为生成式人工智能（AI）领域的新宠时，他和妻子在湾区添置了新居。但是，忙碌的他几乎没时间在买房前去看看自己的新家。他后来带着一丝幽默遗憾地说，结果是打了个大大的喷嚏，原来新家周围的植物让他过敏了。

老黄经常用自嘲的幽默来调节气氛。3 月 18 日，在 Nvidia 的年度开发者大会上，当他走上舞台，迎来一片欢呼、闪光灯闪烁和像摇滚明星般的狂热崇拜时，他开玩笑提醒大家这并不是一场音乐会。他向大家承诺的，是一场充满科学、算法、计算机架构和数学魅力的盛宴。有人情不自禁地喊了出来。

事前，Nvidia 的粉丝们在华尔街已经将这一盛会誉为“AI 的伍德斯托克”。实际上并非如此。出席者大多是穿着商务休闲的中年男性，而非身着串珠装扮和彩绸的嬉皮士。但作为主角，黄仁勋确实有几分吉米·亨德里克斯（Jimi Hendrix）的风采。他身着标志性的皮夹克，展现出激动人心的表现力。他是让复杂变简单的大师。面对媒体，他以表演者的姿态即兴发挥。在那光鲜的外表下，他那改变世界的雄心壮志令人着迷。如果说有谁在无所畏惧地推动“生成式 AI”走向极限，那无疑是老黄。这不禁让人思考：他究竟面临着哪些挑战呢？

这场会议旨在回答一个简单的问题，答案是：没有。我们正站在一场新工业革命的门槛上。按照老黄的视角，Nvidia 走在构建未来“人工智能工场”的前列。对于 Nvidia 的图形处理单元（GPU）——AI 模型开发者最偏爱的处理器，需求之大以至于供不应求已成常态。但 Nvidia 并未因此止步，公司宣布将在今年晚些时候推出一款名为 Blackwell 的新一代超级芯片，性能将远超现有 GPU，为构建更大、更智能的 AI 开辟新天地。得益于 AI 技术的应用，老黄指出，去年全球数据中心的投资已达 2500 亿美元，并正以年均 20% 的速度增长。Nvidia 计划抓住这一增长机会的大部分。为了加大竞争难度，Nvidia 把 Blackwell GPU 的售价定在每个 30,000 至 40,000 美元，这一定价在华尔街看来颇为保守。

为了深耕“加速计算”所带来的益处，Nvidia 正努力拓宽其客户群。目前，其 GPU 的主要客户包括云计算巨头，如 Alphabet、Amazon 和 Microsoft，以及生成式 AI（Gen-AI）模型的开发者，比如 ChatGPT 的开发者 OpenAI。然而，Nvidia 看好的是，从医疗保健到零售，从制造业到你能想到的每一个行业，都蕴藏着巨大的需求潜力。公司相信，众多企业将从简单试用 ChatGPT 转向部署自己的生成式 AI 解决方案。为此，Nvidia 将提供可以即插即用或根据客户需求定制的一站式软件解决方案，名为 NIMS（Nvidia 推理微服务）。这一举措，将进一步让客户依赖于 Nvidia 的 GPU，加深他们与 Nvidia 硬件和软件生态系统的绑定。

截至目前，情况似乎充满变数。但在 Woodstock，不全是和平与爱的景象。回顾一下疫情期间的供应链问题以及随后爆发的中美芯片战，我们不难发现潜藏的危机。Nvidia 当前的 GPU 产品线正面临上游供应链的瓶颈。南韩制造的高带宽内存芯片，这些芯片被用于 Nvidia 的产品中，供应商已跟不上需求。世界最大的半导体制造商 TSMC，负责生产 Nvidia 的芯片，目前也在苦苦应对如何足够生产将 GPU 与内存芯片紧密结合起来的先进封装技术。更何况，Nvidia 的大型集成系统包含大约 60 万个部件，其中许多来自中国，这凸显了如果美中之间的紧张关系继续升级，美国可能面临的地缘政治风险。

问题也可能出现在下游。AI 芯片对能源的需求极大，需要大量冷却设备。随着装满 GPU 的数据中心对电网造成的压力，人们越来越担忧可能出现的电力短缺。Nvidia 的 CEO 黄仁勋希望通过提高 GPU 的能效来解决这个问题。他表示，最强大的 Blackwell 系统，简称 gb200nvl72，训练一个比 ChatGPT 更大的模型时，所需的电力仅为当前最优处理器的四分之一。

尽管如此，这仍是早期 AI 之前数据中心服务器的近 20 倍，Crusoe Energy Systems 的 CEO Chase Lochmiller 表示。Crusoe Energy Systems 是一家提供低碳云服务的公司，它已经决定购买型号为 gb200nvl72 的服务器。不论其能效如何，GPU 的体积越大，利用这些 GPU 训练出的人工智能就越有可能表现得更好。这一现象不仅将推动对 AI 的需求增长，也间接推动了对 GPU 的需求。正如经济学家们在 19 世纪末期的工业革命时期所指出的，效率的提高实际上可能会增加而非减少能源消耗。“与芯片供应的快速增长相比，我们几乎无法同样快速地增加能源供给，”分析公司 New Street Research 的 Pierre Ferragu 说。作为时代的一个标志，亚马逊网络服务——这家在线零售商的云业务部门——最近购买了一座核能数据中心。

’Scuse me while I kiss AI

即便如此，老黄并没有忽视这些风险。他对于人工智能的普遍担忧——比如它会摧毁工作岗位或者消灭人类——持一种较为轻视的态度。他认为，这项技术最终将提高生产力、带来利润并创造工作机会，从而有益于人类的进步。亨德里克斯曾经深信音乐是唯一能改变世界的力量。对于老黄而言，改变世界的力量则蕴含在科学、工程和数学的激动人心的融合之中。■

来源：https://t.co/QbRapTjIdD 
#+END_QUOTE\
** 📌 [[2024-04-02]]
#+BEGIN_QUOTE
注：“’Scuse me while I kiss AI”是一句充满智慧和幽默感的语句，它在字面上模仿了吉米·亨德里克斯 (Jimi Hendrix) 的著名歌词“’Scuse me while I kiss the sky”from the song "Purple Haze." 这句歌词原本是对自由和挑战极限的赞美，经常被引用于表达超越传统边界的意图和高扬的精神状态。

将这句话应用于 AI（人工智能），既是一种对 AI 技术探索无限可能性的诙谐表达，也隐含了一种对于科技进步和人类探索未知领域的乐观态度。它借用了亨德里克斯歌词中的风格和情感，将音乐和科技的革新巧妙地结合起来，表达了对 AI 技术将带来的正面变革的期待。

https://t.co/3gxOQEC30i 
#+END_QUOTE\