:PROPERTIES:
:title: readwise/江湖大佬无招胜有招的故事（如何在不懂领域解决问题...
:END:


* metadata
:PROPERTIES:
:author: [[plantegg on Twitter]]
:full-title: "江湖大佬无招胜有招的故事（如何在不懂领域解决问题..."
:category: [[tweets]]
:url: https://twitter.com/plantegg/status/1768197641249456369
:image-url: https://pbs.twimg.com/profile_images/587268563/twitterProfilePhoto.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-03-19]]
** 📌 [[2024-03-14]]
#+BEGIN_QUOTE
江湖大佬无招胜有招的故事（如何在不懂领域解决问题起来胜过该领域的工程师）

这位同学从chinaren出道，跟着王兴一块创业5Q，5Q在学校靠鸡腿打下大片市场和校内网竞争，最后被陈一舟的校内收购（据说被收购后5Q的好多技术都走了，最后王兴硬是呆在校内网把合约上的所有钱都拿到了--收购合约的钱都是分期付款）。

他在我们公司负责技术（所有解决不了的问题都找他），这位同学让我最佩服的解决问题的能力，好多问题其实他也不一定就擅长，但是他就是有本事通过man、Help、Google不停地验证尝试、分析就把一个不熟悉的问题给解决了，这是我最羡慕的能力。

案例：应用刚启动连接到MySQL数据库的时候比较慢，但又不是慢查询，对这个问题有如下几种解决方案：
1. 这位同学的解决办法是通过tcpdump来分析网络通讯包，看具体卡在哪个步骤，把这个问题硬生生地给找到了。
2. 如果是专业的DBA可能会通过show processlist 看具体连接在做什么，比如看到这些连接状态是 **authentication** 状态，然后再通过Google或者对这个状态的理解知道创建连接的时候MySQL需要反查IP、域名这里比较耗时，通过配置参数 **skip-name-resolve** 跳过去就好了。
3. 如果是MySQL的老司机，一上来就知道 **skip-name-resolve** 这个参数要改改默认值。

在我眼里这三种方式都解决了问题，最后一种最快但是纯靠积累和经验，换个问题也许就不灵了；第一种方式是最牛逼和通用的，只需要最少的业务知识+方法论就可以更普遍地解决各种问题。

每次碰到问题我尽量让他在我的电脑上来操作，解决后我再自己复盘，通过history调出他的所有操作记录，看他在我的电脑上用Google搜了哪些关键字，然后一个个去学习分析他每个动作，去想他为什么搜这个关键字，复盘完还有不懂的再到他面前跟他面对面的讨论他为什么要这么做，指导他这么做的知识和逻辑又是什么（这个动作没有任何难度吧，你照着做就是了，实际我发现绝对不会有10%的同学会去分析history的，而我则是通过history 搞到了各种黑科技 :) ） 
#+END_QUOTE\