:PROPERTIES:
:title: readwise/\# 苹果正在讨论使用谷歌的 Gemini 引擎为...
:END:


* metadata
:PROPERTIES:
:author: [[dotey on Twitter]]
:full-title: "\# 苹果正在讨论使用谷歌的 Gemini 引擎为..."
:category: [[tweets]]
:url: https://twitter.com/dotey/status/1769606442640687573
:image-url: https://pbs.twimg.com/profile_images/561086911561736192/6_g58vEs.jpeg
:END:

* Highlights first synced by [[Readwise]] [[2024-03-19]]
** 📌 [[2024-03-18]]
#+BEGIN_QUOTE
# 苹果正在讨论使用谷歌的 Gemini 引擎为 iPhone 提供生成式 AI 功能

*   正在考虑一项基于现有搜索合作的 AI 协议
*   苹果最近还就此事与 OpenAI 进行了洽谈

苹果正致力于开发基于自身 AI 模型的新功能，作为即将推出的 iOS 18 的一部分。

据消息人士透露，苹果公司正与谷歌商讨一项可能重新定义 AI 行业规则的大型合作协议，以将谷歌的 Gemini 人工智能引擎集成到 iPhone 中。

这两家公司正就许可 Gemini——谷歌一系列生成式 AI 模型——到 iPhone 软件中，以支持今年将推出的新功能进行积极磋商。消息人士表示，考虑到谈判的敏感性，他们选择保持匿名。此外，苹果最近还与 OpenAI 探讨了合作的可能性。

苹果首席执行官 Tim Cook 已承诺，今年将发布一项重大的 AI 新闻。

如果苹果和谷歌能够敲定这项协议，不仅能加深双方在搜索服务上的合作，还能为 Gemini 打开通往数十亿用户的大门。然而，这项合作的讨论也暴露出苹果在 AI 领域的进展可能不如外界期待的那样顺利，同时也可能加剧两家公司面临的反垄断审查风险。

Apple 正在为其下一代 iPhone 操作系统 iOS 18 引入基于自家 AI 模型的新技术。但这次升级重点在于增强设备内部功能，而非云端服务。因此，Apple 正在寻找合作伙伴，共同开发能够响应简单指令来创作图像和文章的生成式 AI 功能。

Apple 和 Google 的代表拒绝发表评论，而 OpenAI 对于评论请求也未立即回应。

从去年初开始，Apple 就在测试一种名为 Ajax 的大语言模型 —— 也就是生成式 AI 的核心技术。同时，一些员工也在试用一款简易的聊天机器人，暂时命名为 Apple GPT。然而，据内部人士透露，Apple 自研的技术仍不敌 Google 及其他竞争者，寻求合作似乎成了更理想的选择。

与 Apple 达成合作将成为 Google 在 Gemini 项目上最重要的里程碑，也可能大大推动其 AI 项目的发展。Apple 拥有超过 20 亿的活跃设备，这些设备未来可能会装载 Google Gemini 技术。今年 1 月，三星就发布了搭载 Gemini AI 功能的新款智能手机。

但这两个硅谷巨头的合作可能会引起监管机构的关注。Google 与 Apple 在搜索服务上的协议已经成为美国司法部的诉讼焦点。政府指控二者在移动搜索市场形成了实质上的垄断。这两家公司辩称，Apple 认为 Google 的搜索服务质量超过其他竞争者，并且 iPhone 用户可以轻松更换搜索服务提供商。

Alphabet 的首席执行官 Sundar Pichai 表达了对 Gemini 在处理 AI 生成图像方面的失误表示了强烈不满，称之为“完全不可接受”。摄影师：David Paul Morris/Bloomberg

在欧洲联盟的压力下，Apple 与 Google 的合作受到了挑战，该联盟要求 Apple 降低用户将默认搜索引擎从 Google 更改为其他选项的难度。随着监管压力的上升和人工智能技术的普及，现行的搜索服务协议对双方的益处可能会减少。新的围绕 AI 的协议有可能补偿这一损失。

美国联邦贸易委员会正在审查 Microsoft Corp. 对 OpenAI 的投资，以确定该交易是否违反了反垄断法。

尽管 Apple 和 Google 之间的谈判仍在继续，但预计任何协议的公布都要等到 6 月，届时 Apple 将举办其年度全球开发者大会。存在不达成任何协议的可能，或者 Apple 最终可能会选择与 OpenAI 等其他生成式 AI 提供者合作。理论上，Apple 可以像其网页浏览器的搜索服务那样，与多个合作伙伴合作。Anthropic 等其他生成式 AI 提供商，提供了一个名为 Claude 的聊天机器人。

Gemini 虽然吸引了消费者和商业的关注，但也引发了争议。最近，用户发现该系统在处理 AI 生成图像中的个体种族问题时存在不准确之处。Google 的首席执行官 Sundar Pichai 对此表示了强烈的不满，称其为“完全不可接受”，并已暂停了图像生成的功能。

苹果公司 CEO Tim Cook 承诺，今年将宣布一个关于 AI 的重大进展。他向投资者透露，公司即将推出的变革性新功能将开拓新领域。这一计划对投资者尤为关键，因为在今年早些时候取消了自动驾驶汽车项目后，他们正寻找 iPhone 制造商的新增长点。该公司已将部分从事该项目的工程师转移到人工智能部门。

去年，Cook 表示他个人使用了 OpenAI 的 ChatGPT，但也指出存在一些需要解决的问题。他承诺，苹果平台上将谨慎推出新的 AI 功能。通过与其他公司合作开发生成式 AI 功能，Cook 也在尝试减少平台可能面临的责任风险。

据了解，讨论中的生成式 AI 功能理论上将融入 Siri 和其他应用之中。同时，基于苹果自研模型的新 AI 能力还将被整合进操作系统，重点在于主动向用户提供信息，并在后台代为执行任务。

https://t.co/QOcoc3wVv6 
#+END_QUOTE\