:PROPERTIES:
:title: readwise/腾讯科技的潜望栏目组这个月的ai访谈系列真是质量...
:END:


* metadata
:PROPERTIES:
:author: [[foxshuo on Twitter]]
:full-title: "腾讯科技的潜望栏目组这个月的ai访谈系列真是质量..."
:category: [[tweets]]
:url: https://twitter.com/foxshuo/status/1768638228607979966
:image-url: https://pbs.twimg.com/profile_images/1550395556685819910/qnbrCfBf.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-03-19]]
** 📌 [[2024-03-16]]
#+BEGIN_QUOTE
腾讯科技的潜望栏目组这个月的AI访谈系列真是质量爆炸，而且行文都是最清晰的问答结构，信息呈现非常干净，采的杨植麟、朱啸虎、王小川刚好是中国AI行业3个不同站位、不同判断、不同目标的人选，甚至有种连续剧的节目效果，很推荐作为合订本收藏。

杨植麟是第一篇：月之暗面杨植麟复盘大模型创业这一年：向延绵而未知的雪山前进（https://t.co/4mDWPIe6dw）

他的身份是创业者，中国顶级优秀的那拨年轻人，包括我见到的几乎所有机构，都对他的才能和为人充满了溢美，Kimi在我看来也是极为少有的在部分场景能够提供比GPT-4和Claude 3更优解的工具。

杨植麟的观点，用四个字总结，就是「还来得及」，现在全球大模型还处在一个突变期，变数很大，关键是要跟着跑下去，要坚定不移的去拿资源，千万不要自我怀疑，事在人为。

在他看来，创造符合未来需求的AI组织会是一项巨大的登月工程，现在各家都还处于火箭原型的测试阶段，不要着急，第一步已经走出去了，中美之间的实际差距在缩小，短时间里的市场份额没那么重要，还是要瞄准第一性原理，AGI是核心，第一个拿到AGI门票的可以从那一刻起降维打击，实现赢家通吃。

杨植麟的理想主义——以及他确实拥有做这些判断的的技术才学——本来在很大程度上给国内略显低迷的AI行业起到了激励士气的作用，然后就有了第二篇对话朱啸虎的反差感出来：朱啸虎讲了一个中国现实主义AIGC故事（https://t.co/xKqCCzODVH）

朱啸虎是投资人，媒体长期以来都很喜欢跟他聊，因为嘴上不怎么把关，什么心里话都能往外说，朱啸虎的这场采访，也可以用四个字来总结，那就是「拉鸡巴倒」。

排开情绪化的部分，朱啸虎的核心观点其实也不复杂：大模型研发没戏，干不过美国，等开源追上来，直接拿开源做应用层创新，去做能够直接创造经济效益的服务出来，底层技术搭便车就好，让美国在前面烧钱试错，跟在后面的成本和风险至少低一个数量级。

朱啸虎的身份决定了他看项目都是财务视角，比较隐晦的暗示了现在投大模型很难有退出通道，美元越来越少，人民币只能找大厂接盘，问题是大厂的FOMO心态一旦过去，就很难说了。

不过他举的例子也挺难崩的，比如说美国大模型是牛逼，现在中国也投不进去，但是中国的AI创新可以让王一博的数字人给粉丝打电话卖货，转化率翻好几倍，美国干不来这样的创新。

「繁花那个时代大家是真的可以搏一下，现在就别了，先活下去。」

再就是昨天，第三篇对王小川的采访也发出来了：王小川想提出中国AGI第三种可能性（https://t.co/PyENsWNn8m）

王小川的表述，四个字可能不够总结，要用五个字，「李彦宏傻逼」。

好吧，事实上是，王小川认为李彦宏被自家团队给忽悠了——竟然真的相信文心一言比GPT-4要强——而这种盲人摸象的现象，其实也广泛存在于AI行业里，大家都在用局部的认知做出宏观的评价。

除此之外，王小川自认选择的技术和商业的中间路线，既不同于杨植麟把AGI当做唯一终点，也不像朱啸虎那样把AI当成一门生意，他相信垂直模型的爆发会来得更早。

美国有钱有算力，所以可以直线本着AGI而去，但在中国很容易变成说服资本的游戏，如果能用AI为中国增加100万医生，这将是天文级别的价值，所以要为场景去开发产品。

不过我自己看下来王小川这篇是最虚的，很符合他这个人养生玄学上的追求，基本可以算是AI行业的边缘经验，别人是在盲人摸象，他可能是在几万米开外找象⋯⋯

反正这个系列（还在更新）都还挺推荐阅读的，除了AI产业的信息密度管饱之外，采访对象的延伸输出也很有可看性，比如朱啸虎痛惜当年错过字节跳动B轮的表达就特别有画面感：

「看在师姐的面子上勉强跟他（张一鸣）聊了十几分钟，没觉得这人多牛，说话也不行，前面他又连着创业失败了三次，真看不出来他还能成，哎⋯⋯」 
#+END_QUOTE\