:PROPERTIES:
:title: readwise/\#英语学习  为什么我一听英语就犯困，每次打起精...
:END:

:PROPERTIES:
:author: [[yiqifacai on Twitter]]
:full-title: "\#英语学习  为什么我一听英语就犯困，每次打起精..."
:category: [[tweets]]
:url: https://twitter.com/yiqifacai/status/1714909911103201399
:image-url: https://pbs.twimg.com/profile_images/1659067563647827973/BuHY5YM1.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-18]]
** 📌
#+BEGIN_QUOTE
#英语学习  为什么我一听英语就犯困，每次打起精神学习，但很快就懈怠，而且这种懈怠又导致对自己自控力的自责，形成了恶性循环？
   这并不是你的错，因为你除了要对抗人类百万年进化的本能-逃离非母语族群保平安。还要抵抗大脑的10分钟下滑的“专注力曲线”，你的学习材料和训练材料太长，就会导致这个问题。
    另外要明白懈怠感的本质的心理问题是语言学习是没有尽头的，即使你突飞猛进词汇过万，也离母语高等教育人群依然有很大差距。学了不知道学没学，不知道有没有提高，感觉提高了，一刷单词很多又不会，这个情况会大大损害你的积极性。
   你还记得自己刷抖音怎么上瘾的吗？为什么一个个视频停不下来。因为你的attention curve像技能冷却一样，不断在被抖音刷新。其实解决办法就在抖音的机制里。
解决方案：
限制学习材料的长度：

初级：BBC 6 mins English 六分钟英语，刻意的慢速和刻意的讲一个主题里的新词。
中级：TED  里的serials 系列，每个视频4分钟，提供双语字幕。学一些理财，生活小技巧，一些社会现象和科学技术的由来等等。
高级：TikTok 里的情感咨询故事，采访陌生人等节目，有很多博主会解读读者的来信，婚内八卦，工作八卦，采访路人过去的故事，房租生活成本等等。很有趣而且时间都是10分钟最佳专注力范围内。到了这个阶段，你会刷的停不下来，等你完全忘记自己在学英语，开始为这些故事有了情感的反馈，算是到了一个比较高级的阶段。

更改奖励机制：不要给自己设目标。可以用番茄🍅时钟，定一个25分钟的学习计划（刷3个视频左右）
每天统计自己攒了几个番茄就好。例如你想2年内，彻底无字幕刷tiktok听人家闲聊。可以限定自己每天攒2-3个番茄。例如你想考雅思托福，可以每天攒6-10个番茄，材料也做调整。
让大脑放弃抵抗情绪，积极融入思考，主动唤起情感共鸣。语言这种传递信息的震动和波动，就会不断的在你的脑皮质上留下神经的链接，最后这种链接足够多，你就会融汇贯通，思考模式和用词用语日益接近母语者。 
#+END_QUOTE
    date:: [[2023-10-19]]
*** from _#英语学习  为什么我一听英语就犯困，每次打起精..._ by @yiqifacai on Twitter
*** [View Tweet](https://twitter.com/yiqifacai/status/1714909911103201399)