:PROPERTIES:
:title: readwise/《欲望的演化》 书评 比《亲密关系》更为出色的...
:END:


* metadata
:PROPERTIES:
:author: [[OdysseysEth on Twitter]]
:full-title: "《欲望的演化》 书评 比《亲密关系》更为出色的..."
:category: [[tweets]]
:url: https://twitter.com/OdysseysEth/status/1713725212452389300
:image-url: https://pbs.twimg.com/profile_images/1495019639264452613/kWM2KtWc.png
:END:

* Highlights first synced by [[Readwise]] [[2023-12-22]]
** 📌 [[2023-10-16]]
#+BEGIN_QUOTE
《欲望的演化》 书评

比《亲密关系》更为出色的作品，爱不释手。

开篇就模仿叔本华的名言写道：“拥有爱情时，我们被爱的感觉催眠；没有爱情时，我们被爱的幻想占据。” 进而作者谈及每一种性策略的背后都有着特定的心理机制。读毕此书仿佛当年第一次戴上眼镜，整个世界都清晰了。

现代社会要么把男女两性当作不同的物种加以偏见，要么倾向波伏瓦的想法 —— 女人是后天形成的。作者在择偶策略上，深刻的道出了男女两性的不同，以及不同的原因。微妙之处令人不禁发笑，并在微笑后深思。

性策略可以简单分为长择与短择，男性无意识地会倾向于寻觅更多的女性，并且审美会倾向指向生育能力的外表信号，比如年轻、皮肤光滑、腰臀比低。而女性无意识地会倾向于丰富的资源、并且在某些情况倾向于混合策略，比如从一位男性从获取资源，从另一位男性身上获取基因。

真诚和承诺是女性频繁寻求的特征，这和女性未来能否保障后代抚育息息相关，即使时过境迁，现代女性未必生育，但这一审美依旧留了下来。并且女性更为多变的情绪蕴含着深层理性 —— 这不仅是对男性承诺的测试，而且也迫使男性投入更多的时间，从而减少出轨的机会。

历史看似是父权社会的男性书写的，但更长远的历史来看，男性是女性的育种试验品。男性喜欢玩的地位游戏和获取资源的动力，至少部分源于女性的偏好。

信号角度来理解 “旱的旱死，涝的涝死” 很有意思。被漂亮女人围绕着的男性会对其他女性产生更多的吸引力。就像是排队多的地方会吸引来更多人排队一样哈哈。

而女性未必拜金，金钱本身带来的影响要小于其他带来资源的元品质，比如地位、智力、报复、稳定的情绪。有意思，这似乎暗示着女性在千万年的竞争中成为了卓越的潜力股投资者。

长期承诺可以大幅度提升男性的配偶价值，并且这对男性在演化史上也有好处，男性也获得了排他性的性接触。真有意思。颇有点合作的进化之感。广撒网的策略中演化出了专一策略。

作者还部分反驳了审美是后天建构的理论，认为美的许多部分，是存在于先天的。比如低腰臀比其实暗示了没有怀孕 —— 裙子和束腰的审美由此诞生，光滑的皮肤暗示了年轻和健康 —— 礼仪性的皮肤裸露也因此流行。

我之前认为性滥交只是男性的倾向，聊到随意性关系的章节，第一句就让我瞪大了眼睛 ——“如果有史以来女性总是拒绝男性的乱交欲望，那么男性的乱交特性就不可能进化出来。” 的确，女性并不如男性一样会天然更喜欢性的多样性，但是性本身也是女性的策略。

一些小知识也很有意思，比如男性捕捉妻子不忠信号以后，精子量也会增加哈哈，而女性没有达到性高潮的话，会排出更多的精子。女性和情人性高潮的次数几乎是和丈夫的两倍。

不过女性的短择策略还是和男性大不相同。比如女性几乎不可能和刚认识的男性发生关系。并且女性的短择策略有时还是作为长择策略的手段，即先用性来深入了解对方，或者是性作为之后上位的垫脚石。（吓得我对艳遇想都不敢想了）

也理解了一些女性在恋爱中受到困扰的原因，恰恰就是男性对女性短择和长择的回应不同。男性在短期关系中会大幅放宽标准，几乎不受到女方除了容貌和要求承诺以外的因素阻碍。因此女生很容易就可以和价值更高的男性进入短期关系，但很难进入长期关系。这里有意思的点在于，被认为性生活放荡的女性会降低男性和她长期关系的吸引力，但却会增加男性和她进入短期关系的吸引力。以及在短期关系中，男性并不在意女方是否成婚，因为这样还可以避免自己的承诺，甚至可以留下自己的基因。难怪人妻这个标签在某些网站上挺火的。

以及男性对同样的配偶性欲会逐渐下降，对不同的配偶会重燃性欲，因此换妻这种行为几乎都是丈夫提出。这种对数量，对新鲜感的追求，也让人理解了群交，以及网络色情背后的性心理基础。作者进一步聊到男性的性幻想，迷人的女性、裸露的皮肤、容易接近而且不要任何承诺。感觉这本书真是 Pornhub 观看指南了。反过来，女性的性幻想常常出现熟悉的伴侣，出现温柔、浪漫和感情中的回应，而不仅仅是视觉画面。“韩剧是女性的 pornhub” 一说虽有偏颇，却也道出了两性的性幻想差异所在。

并且男性更容易对错过的性机会后悔万分，而女性更可能对已经发生的错误性关系后悔不已。这也阐述了人们认知偏差其实蕴含着深层理性 —— 比如男性容易高估女性对自己的喜欢，这种高估带来的一次成功，就足以抵消 99 次愚蠢。

作者继续阐述了一些行为背后的深层理性，比如在短期关系中，男性容易在性高潮之后觉得对方就不再迷人，这可以减少男性卷入承诺的风险。难怪有那句话，看一个人爱不爱你，要看他是否在做爱之后仍然和你一起入睡。

作者也解释了卖淫普遍存在的原因在于男性对代价低的随意性关系的渴望，以及一些女性寻求资源的需要。

更有意思的是，女性在短期关系中，非常看重对方是否慷慨送出资源，以及是否奢侈，并且在一开始就送出礼物，在她身上大量花钱。原来一些男性的这些看似愚蠢的行为，和女性的选择有关，太有意思了！当然，女性在长期关系中并不太在意这些。

男女的差异还在于，女性对短期关系和长期关系都渴望类似的对象，比如高大强壮，浪漫幽默，善解人意。而男性的偏好有所区别。

关于备胎的理性策略也很有意思。毕竟生命无常，配偶出事了再临时抱佛脚，那可就来不及了。但男女两性在备胎的倾向上还是有所不同，女性的外遇更多发生在对现有关系不满时，而男性可以在满意婚姻时照样外遇。并且由于在短择时可以让男性放宽标准，女性更可能和地位更高的男性发生外遇。以及在短期关系中，女性更看重男性的外貌。

童年时父亲缺位的女性，更可能处在短期关系中，因为她并不相信男性的可靠性。想想这层心理因素，也不禁为之感伤。而另一种可能是，有些女性无法在长期关系中吸引到心仪对象，从而选择无忧无虑的短期关系。

性选择如此深刻地塑造了两性 ——“因为女性祖先渴望男性拥有较高地位，男性便进化出了获得地位、炫耀地位的动机。因为男性祖先渴望潜在伴侣年轻和健康，女性便进化出了显示年轻、健康的动机。” 行走在街头，这个论断真是入木三分。

女性希望得到承诺，而承诺的强烈信号就是男性的坚持。这也让女性误判了一些死缠烂打的对象，想起一些听闻的例子，当时不理解那些女孩怎么做出这么愚蠢的选择，现在理解并且叹息。

对小猫小狗的关怀也暗示了对孩子的关怀，这也成了女性眼中的加分项 —— 同时也成了一些男性的欺骗手段。最为吸引女性的，还是对她们遇到问题的同情和理解。除此之外，坦率、诚实、做自己，都让女性喜欢。这个角度看，长期关系很简单，却也不容易。

让我好笑的一点是，我理解了许多男性的夸夸其谈、以及说教式风格，因为这个在短期关系中真的非常有效哈哈。超乎寻常的自信，其实拥有地位和资源的信号，或者至少是可以假装拥有的信号。甚至，女性取笑其他女性的外貌，这种策略在男性眼中很有效。难怪难怪。换句话说，如果你觉得某个性别特征愚蠢，那么往往是另一个性别选出来的。

窃偶策略也很有意思，比如有的人的策略就是先和那对情侣交朋友，然后再伺机上位。一下子理解了各种狗血剧情。而投入大量精力改善外表的男性，竟然还可能会损害竞争优势，真有趣。

女性的消费和美容，也蕴含着深层理性，因为这的确能够帮助到她们获得想要的事物。感慨。有些场景就像是男性试图学投资然后有可能当了韭菜？

女性的欲擒故纵策略很有效，因为男性喜欢这种忠诚的信号。以及，男性喜欢女性的性挑逗，下意识推己及人的做出相同行为，不曾想女性对这种行为甚至会倒胃口。

女性有时会表现得顺从，伪装愚蠢来吸引短期配偶。一下子理解了不少女性为什么想表现得像是只知道吃的吃货的深层内涵。

男性的幽默也是重要的吸引信号，因为幽默暗示着智力、默契和同理心。这个角度看，其实可以看看你讲的笑话对方会不会笑哈哈。

高学历女性面临最激烈的竞争，因为她们不仅远多过适合的男性，而且还有和学历不高的迷人的女性竞争。这个点真是... 换个角度看，所谓 “剩女” 一词，描绘的其实是进化现象。

人们为什么会嫉妒？因为性和情感就是相关的。人们更可能和发生过性关系的人发展感情，也更可能和情感亲密的人发生性关系。但两性对倾向依然不同，男性更注意配偶在性背叛上的线索，以及注意地位资源上的竞争者。

在情感遇到危机时，人们可以通过爱和关切，以及提供资源，甚至增加容貌的吸引力留住对方，但如果这些都不奏效，那么增加绝望的情绪、引起性嫉妒、给配偶做出公开标记（婚戒或社交媒体状态或微信头像）、甚至幽禁（伊斯兰面纱），乃至暴力要挟，贬低配偶，乃至于杀妻... 都是可能的。一下子又理解了好多行为。

强奸基本由男性发起，并且往往是最高层男性和最底层男性。前者是犯罪成本低，后者是择偶失败孤注一掷。作者也为男性正名，即绝大多数男性在不会被捕的情况下也不会这么做。并非 “每一个男人都是潜在的强奸犯”。作者指出女性并不像男性认为的那样喜欢被强暴（又一个 Pornhub 男性性幻想），并且强奸对女性造成的心理伤害非常大。

两性的欺骗和反欺骗也是无孔不入。区别在于女性更容易成为性欺骗者，而男性更容易成为承诺欺骗者。让人叹息的是，许多女性在被虐待之后依然留下，其实就是因为男性在虐待后频繁的道歉和承诺。

作者强调，女性在短期关系中如果觉得自己只是性爱对象时，会有很消极的反应。以及如果女性受害者在经历痛苦并呈现厌恶反应时，男性的性唤起会被抑制。记得以前看过一个说法，似乎是这种场景下拉屎到裤子上或是呕吐把自己弄脏会很有效，当然那时候能不能拉出来就是另一回事了。

作者也指出了女性对可能强奸的陌生环境有特殊的恐惧，比如晚上的街道，从而避免了自己处在危险的环境之中。从而在数据上，多数强奸案都是熟人发生的。甚至更进一步，女性对强壮男性的偏好，也是因为这样的男性可以保护她们不被其他男性侵犯。

人们的分手，往往源于有了更好的替代者，或是对方不再迷人，或是能力和资源下降。并且关系是否幸福，也部分取决于现有配偶和潜在配偶的差异。感慨婚姻不过是起点，共同成长才是维持关系的唯一途径。

在分手过程中，人们往往会打破现有配偶对自己的幻想，变得冷酷、不近人情。唉这又是一个结果上的深层理性策略，自己之前还疑惑为什么这种行为如此普遍。这个过程中还会包括性拒绝和不继续提供资源。而前者对男性尤为有效。而最有效的竟然是和他人发生关系并被伴侣撞破！！！我真是目瞪口呆。以及在现代社会的策略还有不回消息，人间蒸发...

分手后女性的疯狂购物，也是一种无意识的理性，因为这可以增加她重新进入择偶市场的价值。

女性在繁殖价值最快要消失的时候，婚外情发生的可能性最高。这个点也是某种心理机制的投射。

作者结尾的几句话引人深思：

“两性资源不平等的原始推动力 —— 女性的配偶偏好和男性的竞争策略 —— 也是今天资源掌控不平等的推动力。”

“两性的首要竞争对手是同性成员。”

“人们总是会责难频繁更换配偶和乱交行为。但是，通常对他们最有好处的，就是在他人心中培养这种道德观点。”

“只有不断探索复杂的人类性策略库，我们才能了解我们从哪里来；只有深入了解为什么这些人类策略能够进化出来，我们才能把握我们将往哪里去。” 
#+END_QUOTE\