:PROPERTIES:
:title: readwise/刚刚读完“妈妈测试”——当每个人都对你撒谎时，如...
:END:


* metadata
:PROPERTIES:
:author: [[seclink on Twitter]]
:full-title: "刚刚读完“妈妈测试”——当每个人都对你撒谎时，如..."
:category: [[tweets]]
:url: https://twitter.com/seclink/status/1779756450056921441
:image-url: https://pbs.twimg.com/profile_images/1709859553414893568/a_eQ9NYf.jpg
:END:

* Highlights first synced by [[Readwise]] [[2024-04-19]]
** 📌 [[2024-04-15]]
#+BEGIN_QUOTE
刚刚读完“妈妈测试”——当每个人都对你撒谎时，如何与客户交谈并了解你的生意是否是个好主意

“妈妈测试”是指以连妈妈都无法对我们撒谎的 方式提出问题。

1）不要提前分享我们的想法
人们会撒谎来保护我们的感情。

相反，应该专注于了解他们当前和过去的行为。这是一次实况调查任务，而不是一次自我感觉良好的会议。

2）询问过去的具体情况，而不是假设/一般的未来
好的：

“你最后一次使用食谱是什么时候”

“你为什么用它”

“您是否尝试过其他方法，例如观看 Youtube 烹饪视频”

“您目前如何处理这个问题”

“你为什么要麻烦”

坏的：

“你会使用食谱应用程序吗”

“你愿意为此付钱吗”

“你喜欢这个主意吗？”

意见可能是错误信号。我们希望获取事实来了解用户的痛点和行为。

3）避免不良数据
赞美

绒毛（泛型、假设、未来）

想法（了解想法建议背后的动机，而不是仅从表面上理解该想法）

锚定你的讨论并巧妙地摆脱这些。

4) 准备 3 个学习目标清单
你想从这个人身上学到的最重要的三件事。

如果你不知道自己想学什么，那么在进行这次对话之前不必费心

5) 休闲咖啡聊天代替正式会议
在会议室的正式面试中，人们往往只是走过场并勾选复选框。你希望他们感觉自己正在向朋友分享/发泄。

6）细分您的客户并与合适的人交谈
不要只与最资深和最重要的人交谈。

[个人经验] 当我的团队为商场业务提供咨询时，我们对购物者行为的最佳洞察来自于与礼宾部、客户服务和商店销售人员的交谈。

7）成功的学习可以是“X不是问题”
不要与我们的问题结婚。你在这里戴上调查员的帽子：有痛点吗

8) 对于B2B
带着不是试图推销而是寻找行业和客户顾问的心态去参加会议。

作者提出了一个 Vision-Framing-Weakness-Pedestal-Ask 框架，并举例如下：

“嘿皮特，

我正在努力让新企业的办公桌租赁不再那么痛苦（愿景）。我们刚刚起步，没有任何东西可卖，但希望确保我们正在构建真正有帮助的东西（框架）。

我只是从租户的角度来看这个问题，而且我很难从房东的角度理解它是如何运作的（弱点）。你出租办公桌已经有一段时间了，实际上可以帮助我拨开迷雾。 （座）。

接下来几周你有时间聊天吗（问）。”

\---

顾客并不总是知道他们想要什么。但毫无疑问，他们知道自己的痛点和问题。提出错误的问题并得到错误的信号可以说比不与客户交谈更危险、成本更高。 
#+END_QUOTE\
** 📌 [[2024-04-15]]
#+BEGIN_QUOTE
以下是一些符合妈妈测试原则的示例问题：

询问过去的具体情况，而不是对未来的假设或意见：

 \- “你能告诉我你上次遇到这个问题是什么时候吗？”
 \- “你之前尝试过什么方法来解决这个问题？”
 \- “为什么这个解决方案不令人满意？”

关注他们当前的行为：
 \- “你目前如何处理这个任务/问题？”
 \- “你现在使用什么工具或方法来处理这个问题？”
 \- “对于您当前使用的解决方案，您认为最令人沮丧的是什么？”

探究细节和细节：
 \- “你能告诉我你上次做X的事情吗？”
 \- “上次你尝试解决这个问题时到底发生了什么？”
 \- “您采取了哪些措施来尝试解决这个问题？”

提出开放式问题以避免引导他们得出具体答案：
 \- “在与X打交道时，您遇到过哪些挑战？”
 \- “解决这个问题对你来说有多重要？”
 \- “你理想的解决方案是什么样的？”

询问他们的目标和动机：
 \- “你想通过做 X 来实现什么目的？”
 \- “对于 X 来说，什么会让你的生活变得更轻松？”
 \- “为什么解决这个问题对你来说很重要？” 
#+END_QUOTE\