:PROPERTIES:
:title: readwise/I’m Excited to Introduce...
:END:


* metadata
:PROPERTIES:
:author: [[jerryjliu0 on Twitter]]
:full-title: "I’m Excited to Introduce..."
:category: [[tweets]]
:url: https://twitter.com/jerryjliu0/status/1726999782105973231
:image-url: https://pbs.twimg.com/profile_images/1283610285031460864/1Q4zYhtb.jpg
:END:

* Highlights first synced by [[Readwise]] [[2023-12-20]]
** 📌
#+BEGIN_QUOTE
I’m excited to introduce RAGs - create a “ChatGPT over your data” purely with natural language 💬

Setup and use a full RAG pipeline over files/web urls in three simple steps:
1️⃣ RAG Builder: Describe your RAG pipeline in natural language (data, parameters like top-k, system prompt), and let the builder agent build this for you.
2️⃣ View Config: View the generated RAG configuration and make edits to it if you want to update the agent.
3️⃣ RAG Agent: Ask the agent anything and it’ll answer the question!

Of course, this is heavily inspired by GPTs from <a href="https://twitter.com/OpenAI">@OpenAI</a>. The goal here was to build a similar natural language interface but tailored around RAG - retrieval parameters, prompts, data sources, all through conversation. Have an agent help you setup QA over your data instead of you writing code.

We built the app with <a href="https://twitter.com/llama_index">@llama_index</a> + <a href="https://twitter.com/streamlit">@streamlit</a>. It currently supports the following: 
\- LLMs: Supports our 20+ LLMs for builder agent (uses OpenAI by default) and currently supports OpenAI for generated agent (not too hard to extend).
- Embeddings: Supports OpenAI ada embeddings and <a href="https://twitter.com/huggingface">@huggingface</a> models.

There’s so many things we want to do. In the meantime if you have feedback/suggestions let us know!

Check out the attached video, blog post, and repo.

Blog: https://t.co/Sft1fXmA6C

Repo: https://t.co/RGAFsMWKDS<video controls><source src="https://video.twimg.com/ext_tw_video/1726999674555641856/pu/vid/avc1/824x720/FwJT4j8joFh5BeLs.mp4?tag=12" type="video/mp4"><source src="https://video.twimg.com/ext_tw_video/1726999674555641856/pu/pl/4UZ2c8orPqg8wRCd.m3u8?tag=12&container=fmp4" type="application/x-mpegURL"><source src="https://video.twimg.com/ext_tw_video/1726999674555641856/pu/vid/avc1/412x360/j811zXp6MgGv-Hmh.mp4?tag=12" type="video/mp4"><source src="https://video.twimg.com/ext_tw_video/1726999674555641856/pu/vid/avc1/308x270/lnNvwlXcBhRzxjx6.mp4?tag=12" type="video/mp4">Your browser does not support the video tag.</video> 
#+END_QUOTE
    date:: [[2023-11-22]]
*** from _I’m Excited to Introduce..._ by @jerryjliu0 on Twitter
*** [[https://twitter.com/jerryjliu0/status/1726999782105973231][View Tweet]]