:PROPERTIES:
:title: Start-Up Life = Hard Won... (highlights)
:author: [[@joulee on Twitter]]
:full-title: "Start-Up Life = Hard Won..."
:category: #tweets
:url: https://twitter.com/joulee/status/1609583986896171008
:END:

* Highlights first synced by [[Readwise]] [[2023-01-04]]
** Start-up life = hard won insights. Here are my top 10 for this year.

1. Doing well at a start-up is not simply about skill, it is about mentality.

A start-up mentality values action over correctness, results over process. It suits those that value autonomy over clarity. ([View Tweet](https://twitter.com/joulee/status/1609583986896171008))
** 2.  Start-ups operate in wartime, not peace.

Founders must therefore lead from the front -- charge into the mud, make decisive calls, and survive to battle another day. ([View Tweet](https://twitter.com/joulee/status/1609583989580525569))
** 3.  To maximize learning, you need to doubt your knowledge.

To maximize creative production, you need confidence in your knowledge.

The inner game is maintaining this in balance. ([View Tweet](https://twitter.com/joulee/status/1609583992290037761))
** 4.  Transparency and vulnerability are the fastest ways to earning trust.

Don't hide problems. Run towards them, expose them to light and conversation, and marvel in the power of communal support. ([View Tweet](https://twitter.com/joulee/status/1609583994974400514))
** 5.  Top performers like accountability.

Accountability means caring, it means excellence matters, it means a commitment to something greater than ourselves. ([View Tweet](https://twitter.com/joulee/status/1609583997616816129))
** 6.  We care about data because we feel a deeply human need to be masters of our own destinies.

Analysis in the face of uncertainty is one way we wrest control from the whims of fate. ([View Tweet](https://twitter.com/joulee/status/1609584000162746374))
** 7.  A great company fulfills a win-win exchange: individuals give their talent, effort and heart toward a purpose they find more meaningful and rewarding than the satisfaction of individual egos. ([View Tweet](https://twitter.com/joulee/status/1609584002851287041))
** 8.  Being "successful" in a particular role at a particular company in a particular chapter of your life is not a reflection of your worth as a person.

We can be objective about the effectiveness of a particular fit while maintaining love and respect for each other as people. ([View Tweet](https://twitter.com/joulee/status/1609584005514690568))
** 9. The price of rapid improvement is repeated failure. Doubt and discomfort are the entry price of excellence.

It's your choice to play this game, of course. But if you do, recognize that there are no shortcuts to hard work and struggle. ([View Tweet](https://twitter.com/joulee/status/1609584008140316677))
** 10. You sometimes feel things earlier than you can logically articulate them.

Trust yourself enough to explore the feeling and learn something from it. ([View Tweet](https://twitter.com/joulee/status/1609584010820485122))