:PROPERTIES:
:title: Youtube 上有 Youtuber 在不出国... (highlights)
:END:

:PROPERTIES:
:author: [[henices on Twitter]]
:full-title: "Youtube 上有 Youtuber 在不出国..."
:category: [[tweets]]
:url: https://twitter.com/henices/status/1713776785416991039
:END:

* Highlights first synced by [[Readwise]] [[2023-10-16]]
** 📌
** #+BEGIN_QUOTE
** youtube 上有 youtuber 在不出国的情况下，将第二外语学习到母语者水平的成功案例。

Makoto 是一位会说中日英三门语言的 Youtuber，他总结自己学习第二外语的成功经验，可以简单地归纳成一句话：掌握第二外语最重要的是必须有大量地道的 comprehensible input (可理解的输入)。

Comprehensible input 是 Stephen D. Krashen 提出的语言习得假说，强调语言学习是获得的，而不是通过学习得到的。听力或者阅读获取的内容都可以是有效的输入，获取内容的语言难度必须略高于学习者的水平。

多大的地道语言输入量才是合适的 ？Makoto 推荐的时长为 1 个小时，30 分钟后休息 5 分钟，然后再继续下一个 30 分钟的学习。  ([View Tweet](https://twitter.com/henices/status/1713776785416991039))
** #+END_QUOTE
** 📌
** #+BEGIN_QUOTE
** Youtuber Makoto  comprehensible input  英语学习具体步骤：

1）使用传统的学习方法，掌握 2000 个单词
2）在 youtube 上看视频，打开字幕边看边听，接受一些搞不懂的内容 (如果大量单词不认识就放弃)
3）在 youtube 上看视频，如果难度不够 (能听懂 80%以上)，就提高难度
4）将口语练习放到最后的步骤，只有输入够了，才能说出地道的外语  ([View Tweet](https://twitter.com/henices/status/1713788303944671614))
** #+END_QUOTE
** 📌
** #+BEGIN_QUOTE
** 从理解内容到流利地说还有一段距离，Makoto 使用的方法是付费真人聊天，算是比较常规的方法。

详细内容可以参考原视频。  ([View Tweet](https://twitter.com/henices/status/1713857416691900539))
** #+END_QUOTE