:PROPERTIES:
:title: 《从gpt小白到专家》 令人震惊，有些老铁甚至... (highlights)
:author: [[bitfool1 on Twitter]]
:full-title: "《从gpt小白到专家》 令人震惊，有些老铁甚至..."
:category: [[tweets]]
:url: https://twitter.com/bitfool1/status/1661902454588596225
:END:

* Highlights first synced by [[Readwise]] [[2023-05-26]]
** 《从GPT小白到专家》

令人震惊，有些老铁甚至从未使用过 ChatGPT。

使用 ChatGPT 作为我的助手，我的工作效率增加了2倍。

以下是使用 ChatGPT从小白到专家的方法： ([View Tweet](https://twitter.com/bitfool1/status/1661902454588596225))
** 1. Prompt风暴

Google Chrome 扩展程序，投喂提供最佳Prompt，让你轻松玩转ChatGPT 和 Google的Bard。

https://t.co/Sf3556cMWO https://t.co/XvpN2QvVAC ([View Tweet](https://twitter.com/bitfool1/status/1661903366598057984))
** 2.提示词训练营

关于与AI 的免费开源课程。

他们还有一个庞大的Discord 社区，由其他人学习如何提示。

https://t.co/aWxgQtLPgR https://t.co/2moCUpSnkF ([View Tweet](https://twitter.com/bitfool1/status/1661903818324590592))
** 3. Prompt作弊器

我创建了一份关于我在工作流程中使用的最先进的 ChatGPT 技术的文档。

当您注册我的 AI 时事通讯时，我会立即免费自动将其发送给所有人。

https://t.co/5sEdk0WeWS https://t.co/meVzfvwwzQ ([View Tweet](https://twitter.com/bitfool1/status/1661904351542247424))
** 4. ChatGPT 开发者Prompt

由 DeepLearning 和 OpenAI 提供的 1.5 小时的简短 ChatGPT 课程。

该课程教您使用大型语言模型 (LLM) 和最佳实践构建应用程序。

https://t.co/PWsjlGnzwu https://t.co/ME5rnYOoGV ([View Tweet](https://twitter.com/bitfool1/status/1661904623173763072))
** 5.FlowGPT

分享、发现和了解最有用的 ChatGPT  Prompt。

他们还偶尔举办提示黑客马拉松，让您通过提交最佳Prompt来赚钱。

https://t.co/D98Zrblf4h https://t.co/bhUo2qN9Ld ([View Tweet](https://twitter.com/bitfool1/status/1661905857171587072))
** 6. AI PRM

ChatGPT 主页的一体化提示工具包。

获取适用于营销人员、客户支持、销售等的提示模板列表。

https://t.co/wAA7Y3jqmM https://t.co/kGgkwDk0av ([View Tweet](https://twitter.com/bitfool1/status/1661906145567707137))
** 7. Prompt工程师指南

免费提示课程，帮助您更好地与ChatGPT沟通。

用于提示工程的指南、论文、讲座、笔记本和资源。

https://t.co/uWq2wnA9vt https://t.co/lLzyUa9ulP ([View Tweet](https://twitter.com/bitfool1/status/1661906594538622983))
** 8. Prompt大英雄

通过 Stable Diffusion 和 Midjourney 等模型搜索数百万 AI 艺术图像。

在一处浏览用于创建这些图像的所有提示。

https://t.co/0NKb3oOxVr https://t.co/ZQnoxXNSj3 ([View Tweet](https://twitter.com/bitfool1/status/1661906824923344897))
** 本文由令人钦佩的AI大神@rowancheung授权傻哥翻译至中文社区。

AI的浪潮你跟上了吗？不想掉队？抱紧傻哥@bitfool1

https://t.co/j5AIfGNQqg ([View Tweet](https://twitter.com/bitfool1/status/1661907216193175554))