:PROPERTIES:
:title: 如何让 GPT-4 帮你写Prompt？ 很多... (highlights)
:END:

:PROPERTIES:
:author: [[dotey on Twitter]]
:full-title: "如何让 GPT-4 帮你写Prompt？ 很多..."
:category: [[tweets]]
:url: https://twitter.com/dotey/status/1716700422763618653
:END:

* Highlights first synced by [[Readwise]] [[2023-10-25]]
** 📌
** #+BEGIN_QUOTE
** 如何让 GPT-4 帮你写Prompt？

很多人苦于不知道如何写高质量的Prompt，尤其是如果要用英文表达更是吃力，不容易表达准确。

可以试试让ChatGPT帮你写，尤其是GPT-4，生成的质量还是不错的。

如果你只是简单要求它写一个英文Prompt，它很可能只是把你的要求翻译一遍，这样效果可能不够理想。要让Prompt质量高，可以让Prompt遵循一个好的结构，并应用一些好的策略，例如思考链、慢思考等等。

以前OpenAI分享过：《GPT best practices》https://t.co/6BA0QdUmlF，里面就介绍了很多优秀实践，我也分享过一些参考的结构。

基于这些可以写一个Prompt来让它写Prompt😄

首先给它设定一个角色：“Prompt Engineer，擅长写 GPT-4 能理解并输出高质量结果的”，让它明白它擅长写Prompt，生成时生成高质量Prompt内容的概率能高一点点。

然后告诉它要求，例如要考虑Cot、慢思考，提供样例。

再告诉它输出的格式应该遵循一个结构。

这样它就能生成还不错的Prompt内容。

但是要注意的是，这种方法类似于让ChatGPT写代码，如果你自己不能提供清晰的步骤，ChatGPT不一定能将Prompt科学的拆分成合理的步骤。

比如说我让它写一个翻译的Prompt，它不会写出先直译再意译的Prompt，只有你明确要求它分成两步翻译，它才能写出先直译再意译的Prompt。

参考聊天会话：https://t.co/G1wmkvomz1  ([View Tweet](https://twitter.com/dotey/status/1716700422763618653))
** #+END_QUOTE
** 📌
** #+BEGIN_QUOTE
** 参考Prompt：

现在你是一个Prompt Engineer，擅长写 GPT-4 能理解并输出高质量结果的，撰写设计Prompt时，优先考虑：
1. Chain of Thought，think step by step，Split complex tasks into simpler subtasks，Tactic: Specify the steps required to complete a task
2. Strategy: Give GPTs time to "think"
3. Tactic: Provide examples

Prompt的结构：
1. 设定一个角色，例如你是一个擅长翻译的助手
2. 设定任务目标
3. 限定输出格式，方便程序解析，例如JSON，或者特殊字符隔开的文本，没有无关信息

这条消息只要回复OK，我将在接下来的消息中提出需要你帮助设计和撰写的Prompt。  ([View Tweet](https://twitter.com/dotey/status/1716700958174970323))
** #+END_QUOTE
** 📌
** #+BEGIN_QUOTE
** 我很喜欢GPT帮我写的一个例子：

Example:

Input English Text:

Life is short, you know, and time is so swift;
Rivers are wide, so wide, and ships sail far, eme.
We pass away, as the fleeting instant of an eye, you know;
We come together, like the meeting of water and the sky, eme.

Output:

Literal Translation:

生活是短暂的，时间非常迅速；
河流非常宽广，船只航行很远。
我们就像眼睛转瞬即逝的瞬间一样消失；
我们相聚，就像水和天空的相遇。

\----

Conveyed Meaning Translation:

生命短暂，时光飞逝；
江河辽阔，船只远行。
我们犹如眨眼间即逝的时光；
我们的相遇如同天际与江水的融合。  ([View Tweet](https://twitter.com/dotey/status/1716701751410086114))
** #+END_QUOTE
** 📌
** #+BEGIN_QUOTE
** 好问题，如果对结果不满意，是可以进一步提要求的，比如我这个会话：https://t.co/zB45Q7l11N

https://t.co/7Bm9Yj0xyT  ([View Tweet](https://twitter.com/dotey/status/1716702094198026362))
** #+END_QUOTE