:PROPERTIES:
:title: 早在2010年，kk就在天涯论坛上发表了一系列关... (highlights)
:END:

:PROPERTIES:
:author: [[FlagofMuskox on Twitter]]
:full-title: "早在2010年，kk就在天涯论坛上发表了一系列关..."
:category: [[tweets]]
:url: https://twitter.com/FlagofMuskox/status/1699406126205563087
:END:

* Highlights first synced by [[Readwise]] [[2023-09-07]]
** 📌
** #+BEGIN_QUOTE
** 早在2010年，KK就在天涯论坛上发表了一系列关于国内房地产发展的帖子，其中详细结合国情，对国内房地产市场的形势做出了独到的判断，站在今天的视角回顾过去十几年的楼市变迁，我们可以清晰地看到天涯KK对于国内房价和社会发展的预言几乎全部兑现

以下是KK大神的部分观点精选:

• 房地产是一个完整的产业链。

• 农产品是基本的食物来源。

• 普通城市白领是最严重受到压榨的群体，他们位于金字塔的底层，需要通过艰难的努力往上爬升。

• 通货膨胀就是剥夺普通老百姓的财富，让权贵的财富更加集中。

• zf会保证绝大多数人民的温饱问题，但也会让中下层群众手中的闲钱基本上花费在特定的商品上。

80年代，民众的消费主要集中在三大物品上：自行车、手表和缝纫机。

90年代，居民消费主要是：彩电、冰箱、电话和空调。

现在，汽车和房地产。

汽车是工业化产品，不具备稀缺性。

房地产则具备投资和生活必需品的双重属性，既可以让金字塔中上层的精英群体依靠房地产保值增值，又可以吸收中下层群众未来几年的结余资金。

• 体制内和体制外。

体制内是统治阶级，维护自身利益，制定各种政策时首先考虑自身利益。违背统治阶级利益的事情即使出台也难以执行。

庞大的国家机器要正常运转，必须使手下和自身的利益一致。如果自己吃肉，手下连汤都喝不上，这个机器就无法运作。

• 北京的房子由全国富人购买，省会的房子由该省富人购买。但当省会城市距离一线大城市在6小时高速路程以内时，省内富人的资金就会流向一线大城市，而不是省会城市。

• 购买房屋取决于目前手头的资金和对未来收入的预期，要充分考虑自身的收入水平。

• 越偏远的地方越黑暗，越缺乏公平。越偏远的地方贫穷群众所占比例越大，越偏远的地方的权贵生活越腐败、越奢华。

资源的稀缺导致权贵更容易垄断资源，以低收入高物价的方式对底层群体进行裸露的掠夺。

• 多了解zf政策，理解zf的意图。通常情况下，如果zf发布的政策不涉及多个部门，尤其是财政部门，那么可以看作是“我们有一个美好的想法”，而不会真正付诸行动。

• 一无所有的人最可怕。

• 房地产昂贵的不是房屋本身，而是地皮。

• 房产税是zf增加收入的一种手段，但实际推行起来会遇到很大阻力，最终可能导致房租上涨。

• 房地产的一级市场包括城市规划、城中村改造、旧房拆迁和城市综合体开发。中央zf参与了房地产的一级市场。

• 公租房是为体制内服务的。

• 私企员工缺乏社会关系和关键客户，完全受制于公司和老板。因此，私企员工的可替代性很强。

• 人的基本物质需求包括衣食住行、医疗和教育。基本食品、教育和医疗是不可触及的。而房产可以，因为租房也能够维持生活。

产权房屋价格上涨所牺牲的主体只是体制外部分都市白领的利益，换来的只是网络上没完没了的抱怨和诅咒。

只有体制外的都市中下层群众才是高房价的受害者，但是这个群体的地位真的很微不足道。

那些既没有稳定工作（低层都市白领失业的概率相当大），又没有自己房产的都市小白领是金字塔底层被压榨的对象，甚至不如交通便利地区的农民。

• 真正反映居住成本的是房屋租金，而不是房价。

• 战争来临时，手中的钱将变成废纸。

• 货币超发，如果资金不流入房地产，那么农副产品作为刚需的价格将上涨，这是不可接受的。

• 在一线城市，当新房价格低于周边二手房价格，并且成交量开始逐渐增加时，就是购房的时机。如果你碰巧遇到国家的调控良机，那么你就需要认真选择房屋，做足功课，并迅速行动。因为在商品房热销期间，很难找到一个满足你户型、位置和楼层要求的房子，根本没有机会进行选择，而在调控期间，虽然房价可能没有大幅下降，但绝对给了你选择的空间。购房时的位置选择要考虑zf的规划，尽量一次到位。未来公园地产将成为稀缺资源。

• 养老问题需要考虑，体制外人员的养老确实是一个问题，做生意赚钱以备养老是明智之举，聪明的人早早地以房产来养老。最糟糕的是那些没有在职场上有所突破且没有特殊技能的私企员工。养老问题确实是一个大问题。

• 不要试图说服别人，这浪费时间。

• 存储资源胜过存储金钱。

• 任何税种最终都会转嫁到社会最底层的群众身上。

• 中国的学者很难抽出时间来从事深入的学术研究，功利性过强。

• 货币泛滥和分配不公是实体经济发展困难、房价居高不下的根本原因。

• 关于通货膨胀问题，体制内的职工工资会随着时间的推移而增长。体制外人员的薪水不取决于通货膨胀，而是取决于行业的利润率、企业的盈利情况和个人的能力和运气。对于竞争激烈、产能过剩的行业中的民营企业普通员工来说，工资增长很难抵御通胀的影响，而且通胀导致的生产成本上涨可能会导致减薪甚至裁员的风险更大。

• 提高首付主要是为了防范金融风险，zf的调控目的从来不是解决穷人买房的问题。相反，金融风险来自于让穷人购房，因此提高首套房的首付比例、阻止穷人购房，才是有效应对金融风险的手段。同时也会推升租金上涨，zf推出的公租房才能有市场，有利可图。

• zf初期采取的严厉打击措施往往产生相反的效果，因为zf不可能让房地产崩盘，否则将埋葬现有的体制，社会“和谐”将不复存在。如何实现房地产持续稳定与国内生产总值的同步增长是zf面临的最大难题，这完全取决于领导智慧，但目前来看，实现这一目标是非常困难的。

• 我们实行的是双轨制国家，在经济全球化的今天，国内并不与国际接轨。这就好比互联网，我们重要部门的内网绝不会与外网连接。要改变这种情况只有两种前提，一是外族入侵，二是出现全国性的大饥荒。否则，期望房价崩盘并重建一个新世界是不可能的。

• 垄断企业的低效率、腐败、强制定价和强制消费，这些问题在古今中外都是一样的。

• 股票和房地产不同，不能创造财富，只是财富再分配的工具。但是财富再分配是庄家分配散户的钱，而不是散户分配庄家的钱。因此，要在股市赚钱，需要具备庄家的思维方式。

• 一个没有法治的社会，就会奉行赤裸裸的丛林法则，什么是对的？什么是错的？理由永远站在强者一边，强者可以随意决定弱者的生死。这样的社会是可怕的。

• 炒概念没有实体支撑的房价，就像是一个击鼓传花的愚蠢游戏。

• 25岁不是考虑失业的年龄，35岁之后体制外的人才应该开始考虑失业问题。因此，在年轻时就要买房子，即使起初资金不足，也不要过多计较，先买一个小的，以后有能力再换。如果未来没有在职场上有所突破，至少还有一个自己的住所，不至于租房被人赶出来。

• 不是所有的公务员都能够晋升，也不是所有的公务员都能获得分配的房子，尤其是在二线以上的城市，未来底层公务员住公租房的可能性更大。

• 中国所有的问题都是政治问题，而不是经济问题。离开政治来谈论经济，永远无法找到问题的答案。

• 老龄化社会，养老问题比房子更为重要。

• 如果无法进入体制内，不管是不是大学毕业，只要有头脑、懂得做生意，掌握一门技能，并且不懒惰，生活肯定比一般在公司打工的小白领强。  ([View Tweet](https://twitter.com/FlagofMuskox/status/1699406126205563087))
** #+END_QUOTE
** 📌
** #+BEGIN_QUOTE
** “股票和房地产不同，不能创造财富，只是财富再分配的工具。但是财富再分配是庄家分配散户的钱，而不是散户分配庄家的钱。因此，要在股市赚钱，需要具备庄家的思维方式。”——这一段话值得所有炒股和炒币的朋友反复研究学习，作为著名楼市预言家，KK即便面对另一个市场总结的也如此到位 https://t.co/IntMksULm2  ([View Tweet](https://twitter.com/FlagofMuskox/status/1699411650422710751))
** #+END_QUOTE