:PROPERTIES:
:title: 谈谈最近「211230」 (highlights)
:author: [[Geekinney's Blog]]
:full-title: "谈谈最近「211230」"
:category: #articles
:url: https://geekinney.com/talk/talk-recently-211230/
:END:

* Highlights first synced by [[Readwise]] [[2023-01-31]]
** •   上班累的时候，写个几行字，不定计划。最终目的当然是想写一手好字，并借此拾起与手写相关的兴趣。好的字看起来赏心悦目，让人心情好。不定计划。
    
•   阅读指的是读那些严肃文学或小说名著。阅读的好处自然不用多说。那种精神富足的状态，是我曾经得以窥见的心满意足。阅读是一辈子的事情，当下的我只求养成随手拿起一本便能读下去的习惯，能够享受文字带来的精神上的惬意满足。不定计划。
    
•   写作与阅读息息相关。用文字表达想法，本就是件酣畅淋漓的事情。想写就写，想停就停，不做计划。
    
•   最近想学一门乐器，尤克里里最适合。买了26寸尤克里里、指弹独奏的书籍和手指练习器。我会带着它出差，用空余时间慢慢练习精进。我喜欢这些不会过时的，需要用长久时间来打磨技艺的物件。
    
•   用ledger记账一段时间，最终还是放弃了。每日的整理记录太繁琐，在论坛和有相同经历的人交流后，认识到：我们普通人记账的目的只是对收入和开销有大概的把握，不必像会计那么精确。所以打算一周或一个月集中整理记录一次，忽略那些非常不起眼的收支。
    
•   通勤的时候喜欢听听播客，这是我已经养成的习惯。那些听过的内容，大多是过耳云烟，但也潜移默化在内心留下了印记，我不想把这件事情变得太功利，保持现状就好。
    
•   最近在看《知否知否，应是绿肥红瘦》，很久没有看剧了。好的剧集不仅让人赞叹剧集制作和演员表演，剧情也能引人思考。最重要的是作为消遣，让大脑放松。看电影动漫也是如此。不定计划。
    
•   目前我唱歌最大的问题是：音准，希望尤克里里的练习能够帮我在这方面有所提升。
    
•   口语表达的第一步就是普通话，我的普通话一言难尽。曾经尝试过一些切实可行的练习办法，现在需要重新拾起。
    
•   一直想拾起我这个半吊子英语，尤其是口语。我知道提升的方法途径，但一直没认真考虑这件事。理清必要性后，我觉可以认真定个计划了。 ([View Highlight](https://read.readwise.io/read/01gmcxhkj3a4g0ebjfzqy7zf2w))